### ISSUE TITLE
Migrations do not re-run if appdata is altered

### ISSUE THREAD

**Issue by groob** [kolide/fleet#1198]
Currently, we have an internal package called `appdata` where we set initial data to be added to a database. It was added to simplify support for multiple datastores. 

The problem is that once a SQL migration runs, changing the initial data in `appdata` does not affect a database where migration already ran. Today this caused an issue when we removed the previous licensing public keys from `appdata` and added a new one. The public key was not added to the correct table. 

Because we've now deprecated `inmem` and are only using a single backend, it makes sense to remove `appdata` and move all the initial state directly into migrations. 

This is not a critical issue, but would be nice to get a fix when someone has some downtime, as it will cause bugs in the future.

**Comment by zwass** [comment]
This was completed some time ago. The migrations are now in https://github.com/kolide/fleet/tree/master/server/datastore/mysql/migrations/data.
