### ISSUE TITLE
Add YARA to Fleet

### ISSUE THREAD

**Issue by murphybytes** [kolide/fleet#1221]
Fleet datastore already persists YARA information. 

* Return YARA config in osquery/config endpoint
* Expose the CRUD for YARA config in the Fleet API so when we're ready to add that to the GUI we'll have the infrastructure in place to do that.  
* Handle logging associated with YARA for the osquery logging endpoints. 

See https://osquery.readthedocs.io/en/stable/deployment/configuration/

**Comment by zwass** [comment]
This is now supported by fleetctl.
