### ISSUE TITLE
Add File Paths configuration 

### ISSUE THREAD

**Issue by murphybytes** [kolide/fleet#1223]
Kolide datastore already persists File Paths information. 

* Return file paths config in osquery/config endpoint
* Expose the CRUD for file paths config in the Kolide API so when we're ready to add that to the GUI we'll have the infrastructure in place to do that.  
* Handle logging associated with file paths for the osquery logging endpoints. 

See https://osquery.readthedocs.io/en/stable/deployment/configuration/

**Comment by zwass** [comment]
This is now supported by fleetctl.
