### ISSUE TITLE
"Incoming Host" indefinitely when details are not retrieved after enrollment

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#1438]
In rare situations, a host may enroll, but shut down before returning distributed query results. In this case, we end up with "Incoming Host" forever.

Perhaps a cleanup job that removes enrolled hosts with no details every minute? If these are indeed legitimate hosts, they can re-enroll when they reconnect.

<img width="1090" alt="screen shot 2017-03-20 at 12 21 13 pm" src="https://cloud.githubusercontent.com/assets/575602/24117575/f801e536-0d67-11e7-8650-6f6bd134eda9.png">

**Comment by groob** [comment]
This should help https://github.com/kolide/fleet/issues/1526

**Comment by itsdreese** [comment]
I am currently facing this issue. Is there a timeout option that can be put on the Fleet server so the incoming hosts dont hang forever?
