### ISSUE TITLE
Implement Leveled Logging

### ISSUE THREAD

**Issue by murphybytes** [kolide/fleet#1439]
https://godoc.org/github.com/go-kit/kit/log/level

Right now we have a course grained logging system that probably incurs a substantial performance overhead on a busy server.  In addition, it's hard to filter out noise to find significant events.  We should implement a leveled logging system where the default is to log only errors and possibly info messages,

**Comment by marpaia** [comment]
In #1629, @gjvc said

> ### What did you expect to see?
>
> the ability to enable / disable logging output as required for debugging or general operation.
>
> ### What did you see instead?
>
> Right now, the fleet server is quite chatty on stdout, and there's no way of hushing it up.
>
> ### implementation suggestion
>
> I would set all current log messages at debug level, so that new ones at info are the only ones visible under normal operations.

**Comment by Mazon** [comment]
We are using fleet in kubernetes and having stdout log to graylog and i agree, having anything other then results from scheduled scans and errors is making it difficult for us to use it.

**Comment by zwass** [comment]
I can see a couple of solutions to this:

1) Consider all "request" logs to be debug logs and then set the default log level to info.

2) Log "request" logs to a separate logger, so that these can be toggled independently of other debug logging (and potentially go to a different output).

I'm inclined towards (1) right now as it would be straightforward in terms of configuration and quick to implement.

**Comment by crimsonknave** [comment]
> We are using fleet in kubernetes and having stdout log to graylog and i agree, having anything other then results from scheduled scans and errors is making it difficult for us to use it.

This is exactly what's happening to me, I'd love to see a fix for this. I'd be perfectly happy to have all the "request" logs be debug. As it is, I didn't notice any difference when I turned debug off (unless removing the env var `KOLIDE_LOGGING_DEBUG` didn't do what I thought it would.)

**Comment by TransactCharlie** [comment]
I've raised a PR here: https://github.com/kolide/fleet/pull/2225 . It's a simple modification to move all the logging middleware (essentially debug for each time a handler is called) to the `debug` level unless there actually was an error.

**Comment by zwass** [comment]
Closing this with #2225. That will reduce log verbosity substantially for default settings.
