### ISSUE TITLE
saving new query should have the option of specifying a pack

### ISSUE THREAD

**Issue by groob** [kolide/fleet#1463]
@FritzX6 Not sure about the UX here, but I'm trying to create a bunch of queries and add them to a pack. Right now I have to go to create the queries, then I have to load the packs and add the queries there. 

I should be able to specify that the query I create should automatically end up in one or more packs. 

Of course there's all the targeting/scheduling to consider so this might not be a good idea. I thought I'd bring it up for discussion anyway.

**Comment by zwass** [comment]
Closing this as it will be irrelevant after we move to fleetctl as the primary interface for creating queries/packs.
