### ISSUE TITLE
Frontend uses 100% CPU on Manage Hosts page with ~2.5k hosts enrolled

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#1487]
The constant reloading of all hosts is causing 100% CPU load (on my 2016 Macbook Pro) in the tab that has the manage hosts page open with 2400 hosts. This is also resulting in close to 1MB/s of data transmission from server to the browser. The current strategy of reloading all of the hosts every few seconds was viable when working with just a few hosts, but is no longer viable with more hosts.

We should move to something more efficient for both server and browser -- current consideration is to track when the hosts were updated on the browser, and only send hosts with changes since that time from the server.

**Comment by marpaia** [comment]
This should be resolved with host pagination.
