### ISSUE TITLE
Introduce new fleetctl command 

### ISSUE THREAD

**Issue by groob** [kolide/fleet#1576]
Feature Request: 

I want to be able to manage fleet (import, export query packs) through a CLI. 

Example 
```
# export all queries associated with packs
fleetctl get packs -o json > my_packs.json

# edit the json file and push the packs back to the server. 
#This operation replaces the existing state  of queries and packs in the DB 
# with the updated ones.
fleetctl apply -f my_packs.json
```

**Comment by groob** [comment]
As part of this, [configimporter](https://github.com/kolide/configimporter) should be moved into the CLI.

**Comment by marpaia** [comment]
Would it be ok if the packs format was not compliant with the osquery packs JSON? We also need to able to define which labels/hosts would get which pack.

**Comment by andrewrosezen** [comment]
I vote that it'd be ok provided it was simple enough to strip out the noncompliant structures for anyone who cares to, FWIW.

**Comment by marpaia** [comment]
We could easily make some sort of kolide -> standard osquery conversion tool, but it would be lossy so you wouldn't be able to convert back and forth easily.

**Comment by marpaia** [comment]
This is currently being documented in https://github.com/kolide/fleet/blob/master/docs/cli/README.md, so I'm going to close this.

**Comment by TonyLeeVT** [comment]
Good afternoon, thanks so much for fleet and fleetctl.  Would it be possible to provide an exact link to the documentation for this export feature?  I am putting together an application for Kolide and the following functionality would be very helpful:

```
# export all queries associated with packs
fleetctl get packs -o json > my_packs.json

# edit the json file and push the packs back to the server. 
#This operation replaces the existing state  of queries and packs in the DB 
# with the updated ones.
fleetctl apply -f my_packs.json
```
