### ISSUE TITLE
RFC: Remove edit capabilities for many features from the UI

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1585]
Since open sourcing Fleet, we have gathered feedback from existing users and new users on how Fleet can better suit their needs. This issue proposes a dramatic change that I think we should make to Fleet and I'd like to get some feedback from existing Fleet users as well as potential new Fleet users.

## Problem Definition

We have consistently received the feedback that users want a way to track packs, the queries in packs, decorators, osquery options, etc from source-controlled text files. To this end, we have been reasoning about a CLI tool API and file-format in #1578. We are also reasoning about the new "static packs" server implementation in #1577. Instead of supporting both forms of pack management, I want to completely remove the current UI-based, database driven pack management functionality. 

## Motivation

Removing these capabilities from the UI will reduce cognitive complexity for new users who aren't sure how they should be managing packs. This will also reduce the need for us to maintain a feature which has since evolved into something that more users want anyway.

Note that we may maintain the ability for you to VIEW this data in the UI, just not edit it.

## Migration Strategy

We can provide a tool (as apart of `fleetctl`) that downloads current packs, queries, decorators, and options into source files that can then be source controlled and used with the new management CLI. Existing users will be able to setup their new Fleet config repo seeded with the set of the data that is in their current Fleet instance. Users will then run a set of migrations and begin managing the Fleet configurations via source files.

**Comment by edrolo-paulm** [comment]
Hey, just a drive-by here to see what the current status of this issue is, specifically, the ability to easily import packs from the community. Fleet is a dream to use however not being able to take advantage of new and useful third-party packs is a bit of a downer.

Thanks team Fleet :+1:
