### ISSUE TITLE
Feature Request: Allow different config options for different platforms

### ISSUE THREAD

**Issue by clong** [kolide/fleet#1586]
It would be awesome to have the ability to apply different config options to different platforms within the Kolide console. For example, I would like to keep events enabled on our Mac hosts while also disabling events on our Windows hosts. At this point in time, there is not a way to do that using Fleet.

**Comment by clong** [comment]
As a temporary workaround, agents will respect flags that are defined in the local flagfile as long as those flags have not yet been defined on the server-side.

**Comment by zwass** [comment]
This will be supported in the new `fleetctl` work. See https://github.com/kolide/fleet/blob/master/docs/cli/README.md#osquery-configuration-options

**Comment by marpaia** [comment]
#1792 merged fleetctl into master, resolving this issue for 2.0.0
