### ISSUE TITLE
Configuration for kafka_logger in the UI

### ISSUE THREAD

**Issue by tdesrochers** [kolide/fleet#1596]
```
/ # fleet version --full
 - version 1.0.5-13-gbb43013-dirty
  branch:       master
  revision:     bb430139331590acb5866df04deb8a6d7832518b
  build date:   2017-11-01T20:31:45Z
  build user:   rku924
  go version:   go1.9.2
```
This is built with k8 and running in containers.  All parts server/database/queue are all in containers.
```
cat /etc/*release
3.6.2
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.6.2
PRETTY_NAME="Alpine Linux v3.6"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```
### What did you do?
In the UI under `config` I am configuring osquery to use the kafka_logger instead of the TLS logger.  My use case is I am sending logs from each endpoint in my environment to kafka then from there to many places for many things.  In my osquery config I have currently installed (not using fleet) I have this in my `options` section:
```
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "kafka_producer",
    "logger_kafka_brokers": "aws-elb-hostname:9092",
    "logger_kafka_topic": "osquery",
    "logger_kafka_acks": "1",
    "utc": "true"
  },
```
When I am in the `config` section of the UI I cannot select anything for `logger_kafka_brokers` or `logger_kafka_topic` or `logger_kafka_acks`.  Basically I don't see a way to configure the kafka logger with the UI and I would have to use the configimporter tool to get my desired results (I haven't tried using it yet because I am having other TLS issues but thats my problem nothing fleet related)

I did expect to see options for all of the loggers available in the docs.  If I missed something please advise.

If there is an option in the docs to set values for options then that should be reflected in the UI.

**Comment by marpaia** [comment]
Hey @tdesrochers, so because of the way that the configuration page works now, there is a finite list of options that Fleet allows you to manipulate. This is limiting and not a great implementation for the reason you describe here (you have options you need to define which are not in our predefined (read: old) list).

I'd like to modify how Fleet's osquery option handling works to support this as well as #1586. I messed around with this last weekend for a bit, but I went down some rabbit holes that didn't prove fruitful, I've yet to document the problem and outline a solution though.

**Comment by tdesrochers** [comment]
As a work around will configimporter work for this? Or will I have to use
the flagfile.

**Comment by marpaia** [comment]
As a temporary workaround, you can delete the options from the Fleet UI and specify them in your osquery flagfile. I really want to spend some time refactoring a lot of how options configuration works soon, so hopefully I have a better story for you soon.

**Comment by zwass** [comment]
This is now supported with the `fleetctl` osquery options.
