### ISSUE TITLE
Assumptions about environment where packge-builder is running

### ISSUE THREAD

**Issue by viq** [kolide/fleet#1602]
Currently all the docs point at `package-builder` as the best, easiest, and pretty much only way to deploy `launcher`. You just run those 3 commands and you're done!

Except if you don't have go 1.9+
Or if you're not on a Mac.
Or you don't have osquery already installed (since it's expected for `make test` which is explicitly listed as one of steps to run).
Or you don't have docker installed and running (and even then you may get an informative error like `could not generate packages: could not generate linux packages: could not create deb package: exit status 126`).

**Comment by marpaia** [comment]
Closing in favor of https://github.com/kolide/launcher/issues/206
