### ISSUE TITLE
All Host page (and others) not rendering hosts

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1604]
Initially, when first using the app, the UI will load hosts properly when they're visiting the All Hosts pages or any label (online, darwin, etc. At some instant however, the app will stop showing hosts in the UI. From this point forward, no hosts are able to be shown in the UI as cards or in the list. The sidebar, however, stays correct. Consider the following screenshot. The sidebar indicates that 11 hosts are online, but they are not rendered on the page:

![image](https://user-images.githubusercontent.com/927168/32741054-2b95a382-c862-11e7-9fd9-23c43b8c2590.png)

@groob has debugged this a bit and determined that the response from the server contains the correct host data and has speculated that a new version of a JS dependency may be causing the rendering bug.

No noticeable errors occur in the console when this occurs and there is not currently a reliable set of reproduction steps.

**Comment by zwass** [comment]
I found the issue thanks to a DB dump provided by George Cox (@gjvc) on osquery Slack. It occurs in the [CPU detail rendering code](https://github.com/kolide/fleet/blob/master/frontend/redux/nodes/entities/hosts/helpers.js#L12-L13) when the CPU string is not formatted as expected.

Example expected: `Intel(R) Xeon(R) CPU E5-2420 0 @ 1.90GHz`
Example unexpected: `Intel Core i7 9xx (Nehalem Class Core i7)`

My proposed solution will render output like this 

<img width="673" alt="screen shot 2017-11-13 at 6 45 14 pm" src="https://user-images.githubusercontent.com/575602/32760391-f088fb7c-c8a2-11e7-9c77-0df8eca85709.png">
