### ISSUE TITLE
Add a PostgreSQL datastore implementation

### ISSUE THREAD

**Issue by thedrow** [kolide/fleet#1610]
Some deployments pick one RDBMS and would like to stick with it.
Adding another one to the mix is often a deal breaker.
Could we support PostgreSQL as an alternative to MySQL?

**Comment by marpaia** [comment]
This is totally possible. To add support for a new RDBMS to Fleet, one must implement the [`kolide.Datastore`](https://github.com/kolide/fleet/blob/master/server/kolide/datastore.go) interface. See the [MySQL implementation](https://github.com/kolide/fleet/tree/master/server/datastore/mysql) as an example.

**Comment by thedrow** [comment]
I'm not sure what needs to be changed except `mysql.go`.
Is there a more detailed guide or perhaps we can chat on Slack about this.

**Comment by groob** [comment]
@thedrow `kolide.Datastore` is an interface, which has a mysql implementation. For us to add postgresql, all the methods defined by that interface would need to be implemented using a postgresql driver. 

After that, `main` would have to be changed to allow for specifying which sql driver to use.

**Comment by marpaia** [comment]
So each file in [`server/datastore/mysql`](https://github.com/kolide/fleet/tree/master/server/datastore/mysql) implements a part of the [`kolide.Datastore`](https://github.com/kolide/fleet/blob/3259e7149bcde4695f9aa1bdf9ee49cfaed21509/server/kolide/datastore.go#L4-L31) interface.

In my opinion, most of the interface is pretty basic and wouldn't take too long to implement other than a few components which are definitely likely to be a pain. These are:

- The live query target search currently uses MySQL Full-Text Search (i.e.: [host search](https://github.com/kolide/fleet/blob/4a90414f2e318395100f85e691f1dbf123ce5bef/server/datastore/mysql/hosts.go#L590-L641)). This will actually be much easier with [PostgreSQL FTS](https://www.postgresql.org/docs/9.5/static/textsearch.html) which is known to be much more robust than MySQL FTS.
- The [pack manipulation methods](https://github.com/kolide/fleet/blob/3259e7149bcde4695f9aa1bdf9ee49cfaed21509/server/datastore/mysql/packs.go) and [label manipulation methods](https://github.com/kolide/fleet/blob/3259e7149bcde4695f9aa1bdf9ee49cfaed21509/server/datastore/mysql/labels.go) require a fair-bit of domain knowledge about labels, which is a Kolide Fleet specific concept that is roughly analagous to discovery queries, except there's a schedule of distributed queries calculating all of it serverside.

Additionally, there are a bunch of parts of the Datastore interface that are very UI-centric such as:

- [We calculate online/offline/missing state of hosts in a single database query](https://github.com/kolide/fleet/blob/3259e7149bcde4695f9aa1bdf9ee49cfaed21509/server/datastore/mysql/hosts.go#L317-L348)
- There a whole mess of network interface management intertwined throughout the [host update methods](https://github.com/kolide/fleet/blob/3259e7149bcde4695f9aa1bdf9ee49cfaed21509/server/datastore/mysql/hosts.go#L350-L413).

I think we all agree that having this kind of data tied to the model object of fleet is unfortunate, so I'd definitely be open to trying to reduce the interface of `kolide.Datastore` in concert with this effort.

You may also notice the `migrations` subdirectory of MySQL and the migration methods in the interface. Adding new datastores has the downside that it's another place to maintain future migrations. I don't mind our fork of `goose` which we use to do MySQL migrations, but I would definitely be down to use something else if it were better and allowed us to abstract migrations behind a more generic interface.

All in all, if we could improve the datastore such that it's easy and reasonable to add another RDMS, I would be up for it. I would also be down to deprecate MySQL if the PostgreSQL implementation was a lot easier to operate.

**Comment by zwass** [comment]
Closing this as there are no current plans to build Postgres support. If anyone begins working on this, please reach out.
