### ISSUE TITLE
default query gets sent to fleet server instead of the entered one.

### ISSUE THREAD

**Issue by gjvc** [kolide/fleet#1611]
### What version of `fleet` are you using (`fleet version --full`)?

11:07:38 gcox@nyc01util12:~$ ./fleet version --full
fleet - version 1.0.5-26-ga08d540
  branch: 	master
  revision: 	a08d540333462730996cf9c50abd326a128df4a2
  build date: 	2017-11-14T09:42:54Z
  build user: 	gjvc
  go version: 	go1.9.1

I have a feeling it wasn't there in the version I originally tried, 1.0.5 / baeb80f3b58f4c8c5c92f94f935674d3926907e1

### What operating system are you using?
CentOS Linux release 7.3.1611 (Core) 

### What did you do?
Entered a query on the main page.

### What did you expect to see?
Results of the same query I entered.

### What did you see instead?
Results of the default query which was there in the box as an example.

**Comment by zwass** [comment]
See #1540 and #798 for similar issues. I am able to repro this locally, and I see that the default query text is provided in the body of the POST.

**Comment by zwass** [comment]
AFAICT this is caused by https://github.com/kolide/fleet/pull/1550/files#diff-54f599f639017abfc676c50e9b48e84aR105. I believe deleting that line fixes both this case and the case that PR was trying to fix (in which a saved query is run without modification).

**Comment by barn-stripe** [comment]
Am on 

```
# /usr/bin/kolide version --full
- version 1.0.5-32-g607b914
  branch:       barn-kolide-bug-reporting
  revision:     607b9141eadddb98aeca1690bee9ed64abcf33c9
  build date:   2017-11-16T00:34:43Z
  build user:   barn
  go version:   go1.9.2``` and still seeing this...

```
I1115 18:17:31.157094 14290944 distributed.cpp:133] Executing distributed query: kolide_distributed_query_566: SELECT * FROM users u JOIN groups g WHERE u.gid = g.gid
```

When running an entirely different query. If I stop the query, edit it (delete ; and then add it back) and run it, it runs with the correct query.

**Comment by groob** [comment]
can you try the build I just pasted in slack> i wonder if your deps are not compiling right.
