### ISSUE TITLE
Queries don't return results in master

### ISSUE THREAD

**Issue by barn-stripe** [kolide/fleet#1624]
### What version of `fleet` are you using (`fleet version --full`)?
Was on 923e4e1 (doesn't), then rolled back to 1a3bda5 (works)

```
# /usr/bin/kolide version --full
 - version 1.0.4-63-g1feecba
  branch:       barn-madness-fork-from-master
  revision:     1feecbadfa3a155b2e94c45e3ca43777dc8de587
  build date:   2017-11-15T22:21:24Z
  build user:   barn
  go version:   go1.9.2
```

### What operating system are you using?
14.04.5 LTS, Trusty Tahr

### What did you do?
Try query from GUI, one host (any host/group), hit run. Spinner hangs forever.

websocket getting only:

```
da["{\"type\":\"totals\",\"data\":{\"count\":1,\"online\":1,\"offline\":0,\"missing_in_action\":0...
```
but nothing more.

### What did you expect to see?

Results!

### What did you see instead?

The beautiful spinner

**Comment by barn-stripe** [comment]
> @barn sounds like a regression from `c769bd45a19349ef004576c814820bca323ed7f2` but It's odd that all hosts still loads fast

**Comment by barn-stripe** [comment]
So if I go to /hosts/manage then hosts *don't* load fast, so c769bd45a19349ef004576c814820bca323ed7f2 may be it.

Takes around 5s with ~1000 hosts.

(get the "it's kind of lonely" then the hosts appear.)

**Comment by barn-stripe** [comment]
Tried master again:

```
# ./linux/fleet_linux_amd64 version --full
 - version 1.0.5-32-g607b914
  branch:       barn-kolide-bug-reporting
  revision:     607b9141eadddb98aeca1690bee9ed64abcf33c9
  build date:   2017-11-16T00:34:43Z
  build user:   barn
  go version:   go1.9.2
```

![chrome wss](http://bensmagicals3itch.s3-website-us-west-2.amazonaws.com/Developer_Tools_-_httpskolide.corp.stripe.comqueriesnew_2017-11-15_17-30-15.png) shows the websocket connection and it working.

So this could just be me completely breaking things here and not actually being broken, but the load is very light at the moment.

**Comment by zwass** [comment]
I am having trouble following the thread here... In your final post it looks like the results were pushed over the wire. Did they appear in the UI?

**Comment by barn-stripe** [comment]
Yes, it now looks like it's working, after moving to c769bd45a19349ef004576c814820bca323ed7f2. That's why I'm suggesting it may be PEBKAC.
