### ISSUE TITLE
introduce logging levels

### ISSUE THREAD

**Issue by gjvc** [kolide/fleet#1629]
### What did you expect to see?
the ability to enable / disable logging output as required for debugging or general operation.  

### What did you see instead?
Right now, the fleet server is quite chatty on stdout, and there's no way of hushing it up.

#### implementation suggestion
I would set all current log messages at debug level, so that new ones at info are the only ones visible under normal operations.

**Comment by groob** [comment]
I'm willing to entertain this but some people will find it arguable wether the fact that a user logged in is a debug level log. You might want to collect those logs for audit purposes etc. 

// cc @zwass @marpaia for feedback

**Comment by groob** [comment]
Looks like this is a dupe? https://github.com/kolide/fleet/issues/1439 should we close the old one in favor if this new issue?

**Comment by marpaia** [comment]
Let's close this issue and continue discussing this on #1439 since it already has links and some discussion.

**Comment by Mazon** [comment]
We are using fleet in kubernetes and having stdout log to graylog and i agree, having anything other then results from scheduled scans and errors is making it difficult for us to use it.
