### ISSUE TITLE
add client IP address to client action log entries

### ISSUE THREAD

**Issue by gjvc** [kolide/fleet#1630]
### What did you expect to see?
I would like to see the IP address of the client in the fleet server logs so I know which one is causing problems with a bad enrollment.

### What did you see instead?
An error about a bad enrollment or similar with no IP address with which to go and hunt down the culprit.

**Comment by groob** [comment]
This should happen in HTTP log middleware, which we do not currently have. We only have Service level logs right now. 

I began working on an HTTP log middleware that conforms to the same structured log format but uses the key/values from a typical apache log https://github.com/groob/finalizer/blob/master/logutil/logutil.go
It could be a good start for wrapping our HTTP handlers. 


This data could also be added to the context and propagated to the log middleware in the service.
