### ISSUE TITLE
Cannot initialize empty database

### ISSUE THREAD

**Issue by tonylambiris** [kolide/fleet#1641]
### What version of `fleet` are you using (`fleet version --full`)?
```
fleet - version 1.0.5-42-gc08ba5ed
  branch:       master
  revision:     c08ba5eda90fd1f53543e3bf68170f1f119a1b6c
  build date:   2017-11-20T00:11:26Z
  build user:   tlambiris
  go version:   go1.9.2
```
### What operating system are you using?
Arch Linux (I am the kolide package maintainer)

### What did you do?
Created a new database called kolide and ran `fleet prepare db --config /tmp/kolide.yml` per the documentation.

### What did you expect to see?
The command completing successfully.

### What did you see instead?
Below is the exact output from the above command use a new database without any tables in it:
```
Using config file:  /tmp/kolide.yml
################################################################################
# WARNING:
#   This will perform Fleet database migrations. Please back up your data before
#   continuing.
#
#   Press Enter to continue, or Control-c to exit.
################################################################################

2017/11/19 19:45:38 FAIL 20170306075207_UseUTF8MB.go (alter table file_integrity_monitoring_files: Error 1071: Specified key was too long; max key length is 767 bytes), quitting migration.
```

Another side note, it would be nice if the prepare statement didn't hang if the database defined didn't exist in MySQL yet and instead just created it automatically.

**Comment by groob** [comment]
What version of mysql?

**Comment by tonylambiris** [comment]
Arch uses MariaDB as a drop-in replacement for MySQL:
```
╰ pacman -Q mariadb 
extra/mariadb 10.1.28-1
```

**Comment by groob** [comment]
AFAIK we only support mysql 5.7

**Comment by groob** [comment]
Closing in favor of https://github.com/kolide/fleet/issues/1644 which aggregates a number of mysql version/documentation issues we should fix.
