### ISSUE TITLE
FAIL 20161118212641_CreateTablePasswordResetRequests.go (Error 1067: Invalid default value for 'expires_at'), quitting migration

### ISSUE THREAD

**Issue by WinXprt** [kolide/fleet#1643]

**Comment by groob** [comment]
This works with MySQL 5.7. Please use that version. 

We'll update the docs to make the requirement more explicit as it seems to be a frequent issue.

**Comment by alphamichael** [comment]
I encountered this problem on an Ubuntu 14.04.5 installation running `mysqld  Ver 5.7.20 for Linux on x86_64 (MySQL Community Server (GPL))` - disabling `strict_mode` and `NO_ZERO_DATE` didn't help.

Then I realised the system timezone was set to BST, which meant the default timestamp was being translated to **one hour before** the Epoch.

Switching the timezone to UTC resolved this for me
`timedatectl set-timezone UTC`

**Comment by zwass** [comment]
@alphamichael I'd be really curious if this commit fixes the issue without having to change the system timezone. I created it for other timezone issues folks were experiencing, but I wonder (and don't currently have time to test) whether it would fix this.

https://github.com/zwass/fleet/commit/77ddaead22000dcd1b1f387dded77fc32a0162f5

**Comment by srozb** [comment]
Hi, 
same problem here on fleet 1.0.6 and timezone set to `Europe/Warsaw` (Ubuntu 16.04 LTS). Switching to UTC doesn't solve it.

```sql
CREATE TABLE `password_reset_requests` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,`updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,`expires_at` timestamp NOT NULL DEFAULT '1970-01-01 00:00:01',`user_id` int(10) unsigned NOT NULL,`token` varchar(1024) NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```
Invalid default value for 'expires_at'
```

MySQL server version is:

```
mysql> SELECT @@version;
+-------------------------+
| @@version               |
+-------------------------+
| 5.7.20-0ubuntu0.16.04.1 |
+-------------------------+
1 row in set (0.00 sec)
```

fleet version:
```
./fleet_linux_amd64 version --full
 - version 1.0.6
  branch: 	master
  revision: 	45165aa29aae52346ed1c458f19b89947d315c61
  build date: 	2017-12-04T22:50:27Z
  build user: 	marpaia
  go version: 	go1.9.2
```

```
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by zwass** [comment]
@jamesspi @srozb can you please try building https://github.com/zwass/fleet/commit/77ddaead22000dcd1b1f387dded77fc32a0162f5 as suggested above and let me know if that fixes the issue?

**Comment by jamesspi** [comment]
Hi @zwass, I fixed this by changing the MySQL timezone to UTC as opposed to the CentOS timezone.

Thanks,
James

**Comment by srozb** [comment]
@zwass provide me with a binary or a docker image and I'll be happy to test it for you.

**Comment by lyfak** [comment]
I just had this issue. I would love to know what worked

**Comment by jamesspi** [comment]
Set the MySQL time to UTC, not the system time. That worked for me.

**Comment by NZSmartie** [comment]
> @zwass [...] I'd be really curious if this commit fixes the issue without having to change the system timezone. I created it for other timezone issues folks were experiencing, but I wonder (and don't currently have time to test) whether it would fix this.
> 
> zwass/fleet@77ddaea

Installing fleet for the the first time on an existing server with mysql 5.7(`Ver 5.7.22-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))`) where changing the timezone isn't a feasible solution. I can confirm that your fix works for the initial `fleet prepare db [...]`. ~~I am getting another error later on. but I've yet to find the cause for that.~~ **Edit: unrelated issue**

Could you look at creating a PR for that fix?
