### ISSUE TITLE
redis_address default typo in documentation

### ISSUE THREAD

**Issue by gjvc** [kolide/fleet#1647]
https://github.com/kolide/fleet/blob/master/docs/infrastructure/configuring-the-fleet-binary.md#redis_address

has a "localhost:3306" by accident, as well as the correct "localhost:6379"

**Comment by zwass** [comment]
Verified 6379 as the correct address per https://github.com/kolide/fleet/blob/master/server/config/config.go#L126. PR incoming to fix this.
