### ISSUE TITLE
Add windows network information to cards

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1660]
Originally, we left off network information (IP address, MAC, etc) from host cards because the information wasn't available in osquery (https://github.com/facebook/osquery/issues/2907) but that is no longer the case. Let's add Windows detail queries to populate this information for Windows hosts.

**Comment by deeso** [comment]
@marpaia or @zwass or @monkykap  This issue might be related to #1700 and #1676.  If not, what needs to be done to address this issue.

**Comment by zwass** [comment]
I believe this will be solved by #1700.

**Comment by zwass** [comment]
Closed by #1700
