### ISSUE TITLE
FR: Implement --logger_snapshot_event_type flag in Configuration Page 

### ISSUE THREAD

**Issue by clong** [kolide/fleet#1665]
Flag was added to osquery in this PR: https://github.com/facebook/osquery/pull/3838

**Comment by clong** [comment]
As a workaround (provided via @zwass), you can insert this option directly in the DB: 
`insert into options (name, type, value) values ("logger_snapshot_event_type", 2, "true");`

Tested, and seems to be working! Feel free to close out if you think this feature will be superseded by the upcoming config redesign

**Comment by groob** [comment]
IMO we should mark this as wontfix as this will be resolved with the addition of [a CLI and statically sourced configs](https://github.com/kolide/fleet/tree/master/docs/cli]. The workaround is good enough until then. 

However is someone wants to submit a migration, I'll be happy to review it.

**Comment by zwass** [comment]
This is fixed by the new configuration format in fleetctl.
