### ISSUE TITLE
 /usr/bin/fleet prepare db ERROR

### ISSUE THREAD

**Issue by ghost** [kolide/fleet#1675]
Hello. Error on startup.

 - version 1.0.6
  branch: 	master
  revision: 	45165aa29aae52346ed1c458f19b89947d315c61
  build date: 	2017-12-04T22:50:27Z
  build user: 	marpaia
  go version: 	go1.9.2

OS - Ubuntu 16.04 64bit
Mysql - mysql-server-5.7                    5.7.20-0ubuntu0.16.04.1

Run command: /usr/bin/fleet prepare db --mysql_address=127.0.0.1:3306 --mysql_database=kolide --mysql_username=root --mysql_password=1q1q1q1

ERROR: 2017/12/19 10:50:31 FAIL 20161118212641_CreateTablePasswordResetRequests.go (Error 1067: Invalid default value for 'expires_at'), quitting migration

**Comment by zwass** [comment]
@pushkarevds Do you have the ability to build from source? Can you please build this branch and let me know if the problem persists?

Also, can you please share the results of `select now(), utc_timestamp();` and `show variables like 'sql_mode';`

**Comment by ghost** [comment]
Hello. I set the utc time in OS, everything is working.
