### ISSUE TITLE
Hosts View IP/MAC decorator missing values for Windows Hosts

### ISSUE THREAD

**Issue by monkykap** [kolide/fleet#1676]
### What version of `fleet` are you using (`fleet version --full`)?
fleet:1.0.5

### What operating system are you using?
Windows 10 enterprise 64 bit

### What did you do?
Hi, I am noticing that enrolled Windows Hosts (so far only tested )  are missing IP/MAC information next to their respective icons in the Hosts View (both list and grid). Not sure if interface name ambiguity is a cause or not.

### What did you expect to see?
IP/MAC info in decorator

### What did you see instead?
\-\-

`<span class="host-details__host-content host-details__host-content--mono">--</span>`

**Comment by monkykap** [comment]
Image of issue:

![image](https://user-images.githubusercontent.com/4961844/35367765-fc73350e-0134-11e8-99fb-e742c11b2267.png)

**Comment by zwass** [comment]
If anyone wants to expedite adding this info for windows hosts, you could help out by letting us know what queries need to be run to get the results.

The existing implementation is https://github.com/kolide/fleet/blob/master/server/service/service_osquery.go#L280

**Comment by monkykap** [comment]
so just jotting down observations, windows does not populate the same columns with valid data as other platforms. So the query would need to be based on type (preferring DHCP), has ipv4 mask or !ipv6 mask, ordered by lower metric, and then if still a tie, ordered by interface name (text numbers).

Correction: If only query windows hosts there are many additional columns:  

connection_status | description | dhcp_enabled | dhcp_lease_expires | dhcp_lease_obtained | dhcp_server | dns_domain | dns_domain_suffix_search_order | dns_host_name | dns_server_search_order | enabled
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

as well as friendly_name

**Comment by monkykap** [comment]
okay after playing around with the data more here is some proposed logic:

1. filter out any results with ipv6 masks
2. filter out any results that start with ipv4 address of 127 or 169
3. order by connection_id (which should prioritize names such as local area or ethernet, over wireless,= and vmware/virtualbox, optionally you can first order by type (dhcp will come before manual)

i think this is the right query:

select * from interface_details id join interface_addresses ia on ia.interface = id.interface where mask not like "f%" and address not like "127%" and address not like "169%" order by type,connection_id

Edit: the order by needs work...

**Comment by monkykap** [comment]
Okay here's the best IMO:
select * from interface_details id join interface_addresses ia on ia.interface = id.interface where mask not like "f%" and address not like "127%" and address not like "169%" order by type desc, connection_id asc

will prioritize dhcp over manual and wireless over virtualbox/vmware
if you wanted to prioritize local area or ethernet over wireless you could do connection_id desc since virtualbox/vmware should be type "manual" unless maybe in bridged mode (not sure).


Edit: seems inconsistent when ordering by two columns. I would either order by type desc

**Comment by deeso** [comment]
Looking at the pointer from @zwass and playing with osqueryi on a Windows box, wouldn't it mac sense to be looking at the mac address, e.g.:
```
Query: `select * from interface_details id join interface_addresses ia
                        on ia.interface = id.interface where length(mac) > 0
                        order by (ibytes + obytes) desc`,
```

Am I missing something there?

**Comment by monkykap** [comment]
When i query my fleet of windows machines i don't get legitimate data from some columns including ibytes and obytes so i'm not sure if these columns can be used to sort for an "interesting" interface. I think that's why i suggested some more filtering to remove "uninteresting" interfaces since we can't rely on sort by bytes.

**Comment by groob** [comment]
@monkykap would you be able to test a build of @deeso's #1700 PR and see if the changes there look good to you for windows hosts?

**Comment by deeso** [comment]
I dug up an old Macbook Pro and tested this code, and the networks were correctly listed.

**Comment by deeso** [comment]
![pseudo-working-interfaces](https://user-images.githubusercontent.com/1205295/35779474-384c74b2-0993-11e8-8637-123a3053470a.png)

Looks like the Mac OS X is working, but:

![ms-windows-strip-needed](https://user-images.githubusercontent.com/1205295/35779473-3839cb00-0993-11e8-93ae-2007adccc0aa.png)

There might be some additional spacing after the Windows NIC MAC or IP address that is not stripped.

**Comment by deeso** [comment]
Actually, upoin further inspection this issue may be the result of the OS Name.  Here, the OS name uses 3-lines.  Patch is still good.

**Comment by zwass** [comment]
I'm going to close this issue with the merge of #1700. @monkykap feel free to reopen or open a new issue if those changes don't adequately address your environment.
