### ISSUE TITLE
Two hosts with the same name get merged into a single entry

### ISSUE THREAD

**Issue by seandilda** [kolide/fleet#1689]
### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 1.0.5
  branch: 	HEAD
  revision: 	baeb80f3b58f4c8c5c92f94f935674d3926907e1
  build date: 	2017-10-18T16:22:07Z
  build user: 	marpaia
  go version: 	go1.9.1

### What operating system are you using?
CentOS 7

### What did you do?

Created a RHEL7 and an Ubuntu16 host.  On each I ran 'hostnamectl set-hostname sean-test', then rebooted it.
On the RHEL7 host, I installed osquery to connect to Kolide. 
I checked the Fleet UI and saw sean-test added as a RHEL7 host.
I then setup osquery on the Ubuntu box.
I checked the Fleet UI again, and saw no new sean-test box.
I then ran saved query (select * from os_version) against 'sean-test'.  The results showed it was in fact talking to the Ubuntu box, even though I was attempting the query against the RHEL7 box.

### What did you expect to see?

A separate host entry for each host.

**Comment by groob** [comment]
use `--host-identifier=uuid` in your osquery flags. If you specify hostname(the default), then there's nothing fleet could do.

**Comment by seandilda** [comment]
Thanks for the quick response.

Given this behaviour, using ```hostname``` seems like a really dangerous idea.  Would it be possible to document this was having a lot of issues?  I've also noticed that https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md recommends the ```hostname``` option.  Would it be possible to change the documentation to suggesting something like ```instance```?

I had assumed that fleet was using some kind of instance identifier (if not a physical identifier like serial number) to deferentiate them.

**Comment by groob** [comment]
`uuid` should be the recommended option. 
```
    --host_identifier VALUE                   Field used to identify the host running osquery (hostname, uuid, instance, ephemeral, specified)
```

IMO this is osqueryd specific documentation and belongs in https://osquery.readthedocs.io/en/stable/
We could probably update the "adding hosts to fleet" documentation to reflect that, but generally, there are lots of footguns with osquery, and running it in your environment will require expert knowledge in both the behavior of fleet as well as the behavior of osqueryd.

**Comment by zwass** [comment]
We should update the section https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md#launching-osqueryd where it has `--host_identifier=hostname` to be `uuid`.
