### ISSUE TITLE
Problem using development certs

### ISSUE THREAD

**Issue by bali007861** [kolide/fleet#1701]
I am having a small problem with Fleet binary. When the binary is launched it appears that the cert and key file is deleted. This makes stopping and starting the binary very difficult as I have recreate the cert and distribute to clients again. 
fleet config_dump returns the following:
 cert: ./tools/osquery/kolide.crt
  key: ./tools/osquery/kolide.key

But these directories are not found anywhere.
### What version of `fleet` are you using (`fleet version --full`)?
1.0.6

### What operating system are you using?
CentOS 6

### What did you do?
Stop and Start Fleet binary

### What did you expect to see?
Cert and Key file should be where they were.

### What did you see instead?
Cert and Key files are deleted and missing

**Comment by groob** [comment]
Can you provide more detail? Fleet should never delete your certificate. 
What is the startup command you ran(make sure you remove any secrets when you copy the command from your terminal history).

**Comment by zwass** [comment]
@newbeeeeeee Do you have those files in `./tools/osquery/`? It looks like Kolide is looking for your key and cert there, but I have a feeling you never put them there.

There is no code anywhere in Fleet that is intended to delete files. I strongly suspect this is just confusion.

**Comment by bali007861** [comment]
Where can I find ./tools/osquery/ directory?

**Comment by groob** [comment]
Here https://github.com/kolide/fleet/tree/master/tools/osquery

**Comment by zwass** [comment]
@newbeeeeeee Note also that those certs in `./tools/osquery` should only be used for development. You need to generate your own certs if you are deploying Fleet with any kind of public access.

I'm going to change the title of this issue as I don't think it accurately reflects the problem here.

**Comment by bali007861** [comment]
I was able to fix the my problem. It was related to a cron job. Thanks guys.
