### ISSUE TITLE
Support allowNativePasswords in DB connection

### ISSUE THREAD

**Issue by joncrain** [kolide/fleet#1703]
Currently fleet does not allow the `allowNativePasswords` DSN parameter to enable connections to Azure MySQL. Instead of passing a bunch of different params, requesting to simply expose the DSN string instead.

More information from a similar request available here: https://github.com/grafana/grafana/pull/8618

### What version of `fleet` are you using (`fleet version --full`)?
 - version 1.0.6
  branch: 	master
  revision: 	45165aa29aae52346ed1c458f19b89947d315c61
  build date: 	2017-12-04T22:50:27Z
  build user: 	marpaia
  go version: 	go1.9.2
### What operating system are you using?
Ubuntu 16.04.3 LTS
Azure MySQL
### What did you do?
fleet serve --config ./confg.yml
### What did you expect to see?
Proper connection
### What did you see instead?
"mysql":"could not connect to db: this user requires mysql native password authentication.

**Comment by audibleblink** [comment]
+1

Would love to use Azure MySQL for our Fleet deployment. We're nearing 5k machines.

**Comment by zwass** [comment]
Fixed by #1805
