### ISSUE TITLE
Allow updating other settings without enabling email

### ISSUE THREAD

**Issue by Jackbennett** [kolide/fleet#1705]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 1.0.6
  branch:       master
  revision:     45165aa29aae52346ed1c458f19b89947d315c61
  build date:   2017-12-04T22:52:42Z
  build user:   marpaia
  go version:   go1.9.2

### What did you do?
Updated Kolide App URL from localhost:8080 to <DevPCName:8080>

### What did you expect to see?
Success

### What did you see instead?
Error: Email is not currently configured in Kolide. Many features rely on email to work.

### Notes

In trying to get a test docker service running I can't get osquery to show up in the host list. Perhaps this appURL is binding the server to not listen on the right interface. Or it's replacing the osquery tls_hostname immediately on sync to localhost:8080 on the clients which of course, wouldn't work.

Anyway, I can't check this because invalid mail configs are blocking saving the page on update config.  #1663 seems to prevent me satisfying the data entry validation.

**Comment by zwass** [comment]
It would be better if we could allow other options to be modified if email is not set up.

Nevertheless, @Jackbennett I don't think this is what is preventing you from getting your hosts connected to Fleet. Can you please try turning on `--verbose` and `--tls_dump` on those hosts and seeing what the output looks like? Maybe easier for us to assist you in #kolide on [Osquery Slack](https://osquery-slack.herokuapp.com/).

**Comment by Jackbennett** [comment]
> It would be better if we could allow other options to be modified if email is not set up.

This issue is open for that.

Groob got my other issue sorted. --flagfile was being totally ignored without any message. Very helpful slack channel.

**Comment by zwass** [comment]
This is fixed by #1903

**Comment by zwass** [comment]
@slw07g It would be possible to implement that, but unlikely to be added to our roadmap.
