### ISSUE TITLE
Scheduled Queries packs not working

### ISSUE THREAD

**Issue by bali007861** [kolide/fleet#1709]
Hello All,
I am currently having an issue with scheduling query packs from fleet and I am not sure what I am doing wrong. I have created packs using some saved queries and have set the option to snapshot so I can see when the queries run and logged but it seems that these packs never run. If I setup a schedule using osquery config file, I see these queries run and log properly to the fleet server (osquery result log).

I am also able to run these queries from the fleet server but just the packs  don't run on my defined interval. 

My OSQuery config looks like this:

{
  // Configure the daemon below:
  "options": {
    // Select the osquery config plugin.
    "config_plugin": "tls",
    // Select the osquery logging plugin.
    "logger_plugin": "tls",
    // The log directory stores info, warning, and errors.
    // If the daemon uses the 'filesystem' logging retriever then the log_dir
    // will also contain the query results.
    //"logger_path": "/var/log/osquery",
    // Set 'disable_logging' to true to prevent writing any info, warning, error
    // logs. If a logging plugin is selected it will still write query results.
    //"disable_logging": "false",
    // Splay the scheduled interval for queries.
    // This is very helpful to prevent system performance impact when scheduling
    // large numbers of queries that run a smaller or similar intervals.
    //"schedule_splay_percent": "10",
    // A filesystem path for disk-based backing storage used for events and
    // query results differentials. See also 'use_in_memory_database'.
    //"database_path": "/var/osquery/osquery.db",
    // Comma-delimited list of table names to be disabled.
    // This allows osquery to be launched without certain tables.
    //"disable_tables": "foo_bar,time",
    "utc": "false",
   // "disable_events": "false",
    //Kolide Options
    "enroll_secret_path": "/var/osquery/enroll_secret",
    "tls_server_certs": "/var/osquery/server.pem",
    "tls_hostname": "x.x.x.x:8080",
    "host_identifier": "hostname",
    "enroll_tls_endpoint": "/api/v1/osquery/enroll",
    "config_tls_endpoint": "/api/v1/osquery/config",
    "config_tls_refresh": "10",
    "disable_distributed": "false",
    "distributed_plugin": "tls",
    "distributed_interval": "3",
    "distributed_tls_max_attempts": "3",
    "distributed_tls_read_endpoint": "/api/v1/osquery/distributed/read",
    "distributed_tls_write_endpoint": "/api/v1/osquery/distributed/write",
    "logger_tls_endpoint": "/api/v1/osquery/log",
    "logger_tls_period": "10"
  }

As mentioned earlier, if I add a query to schedule or packs in the osquery config file, it works as expected but I would like to use fleet for managing packs and my config.

Can someone shed some light on what I am doing wrong.

### What version of `fleet` are you using (`fleet version --full`)?
 - version 1.0.6
  branch:       master
  revision:     45165aa29aae52346ed1c458f19b89947d315c61
  build date:   2017-12-04T22:50:27Z
  build user:   marpaia
  go version:   go1.9.2

### What operating system are you using?
CentOS 6

### What did you do?
Trying to schedule queries using packs

### What did you expect to see?
Query packs should run and there should be logging

### What did you see instead?
Nothing

**Comment by zwass** [comment]
Can you run osquery with the `--tls_dump` and `--verbose` flags and show us the output? I'm particularly interested in seeing whether the scheduled queries are being passed to osquery.

Also, can you please show us what your configuration looks like in Kolide?

**Comment by bali007861** [comment]
Here is my Kolide Config, working on the osquery output, interested to see if I can use tls_dump and verbose just in the config file.

![kolide-packs1](https://user-images.githubusercontent.com/36089031/36170509-941794fc-10cd-11e8-897a-a18069a50809.JPG)

![kolide-test-pack2](https://user-images.githubusercontent.com/36089031/36170549-a99edfd8-10cd-11e8-974d-d262a1345bcf.JPG)

![kolide-test-pack](https://user-images.githubusercontent.com/36089031/36170556-ad74471a-10cd-11e8-8bf8-e8e4bc90b215.JPG)

OSquery verbose and tls_dump (Looks like queries are getting there)

I0213 15:00:00.208803 31774 init.cpp:380] osquery initialized [version=2.11.2]
I0213 15:00:00.227241 31774 system.cpp:344] Found stale process for osqueryd (31755)
I0213 15:00:00.227308 31774 system.cpp:377] Writing osqueryd pid (31774) to /var/run/osqueryd.pidfile
I0213 15:00:00.227378 31774 extensions.cpp:300] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0213 15:00:00.228188 31775 watcher.cpp:549] osqueryd watcher (31774) executing worker (31776)
I0213 15:00:00.234661 31776 init.cpp:377] osquery worker initialized [watcher=31774]
I0213 15:00:00.234917 31776 rocksdb.cpp:132] Opening RocksDB handle: /var/osquery/osquery.db
I0213 15:00:00.338655 31784 interface.cpp:338] Extension manager service starting: /var/osquery/osquery.em
I0213 15:00:00.339776 31776 tls.cpp:198] TLS/HTTPS POST request to URI
{
  "schedule": {
    "file_events": {
      "query": "SELECT * FROM file_events;",
      "interval": 300,
      "removed": false
    }
  },
  "options": {
    "disable_distributed": false,
    "disable_events": false,
    "distributed_interval": 10,
    "distributed_plugin": "tls",
    "distributed_tls_max_attempts": 3,
    "distributed_tls_read_endpoint": "/api/v1/osquery/distributed/read",
    "distributed_tls_write_endpoint": "/api/v1/osquery/distributed/write",
    "logger_plugin": "tls",
    "logger_tls_endpoint": "/api/v1/osquery/log",
    "logger_tls_period": 10,
    "pack_delimiter": "/"
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT hostname AS hostname FROM system_info;"
    ]
  },
  "packs": {
    "Check-All-FileEvents": {
      "queries": {
        "Find-0777-Permissions": {
          "query": "select file_events.*, users.username from file_events,users where file_events.uid = users.uid and file_events.mode = '0777';",
          "interval": 30,
          "platform": "linux",
          "version": "",
          "snapshot": true
        },
        "Find-All-File-Events-Map-uid": {
          "query": "select file_events.*, users.username from file_events,users where file_events.uid = users.uid;",
          "interval": 30,
          "platform": "linux",
          "version": "",
          "snapshot": true
        }
      }
    },
    "Get-OS-Version-From-All-Hosts": {
      "queries": {
        "Get-OS-Version": {
          "query": "select * from os_version;",
          "interval": 30,
          "platform": "",
          "version": "",
          "snapshot": true
        }
      }
    },
    "Test-Pack": {
      "queries": {
        "crontab": {
          "query": "select * from crontab;",
          "interval": 30,
          "platform": "",
          "version": "",
          "snapshot": true
        }
      }
}

I0213 15:00:00.656656 31776 system.cpp:257] Using host identifier: 42002987-BBEC-CED9-BFF1-52B606DC20B4
I0213 15:00:00.695672 31776 events.cpp:825] Event publisher not enabled: audit: Publisher disabled via configuration
I0213 15:00:00.695730 31776 events.cpp:825] Event publisher not enabled: syslog: Publisher disabled via configuration
I0213 15:00:00.696040 31776 events.cpp:1078] Error registering subscriber: socket_events: Subscriber disabled via configuration
I0213 15:00:00.698330 31788 events.cpp:746] Starting event publisher run loop: udev
I0213 15:00:00.698462 31789 tls.cpp:198] TLS/HTTPS POST request to URI

**Comment by zwass** [comment]
I'm not sure if this is the problem, but it looks like there is a syntax error with your `file_events` queries.

**Comment by zwass** [comment]
This is probably going to be easier to debug in the [osquery slack](https://osquery-slack.herokuapp.com/).

In this scenario you describe, are you using Fleet? If not, please ask about it in #general. If so, please ask in #kolide.

**Comment by ghost** [comment]
@newbeeeeeee pack queries result will not store in osquery node , it store on fleet server, pls see this link: https://github.com/kolide/fleet/blob/master/docs/application/working-with-osquery-logs.md
