### ISSUE TITLE
Build from Dockerfile Fails

### ISSUE THREAD

**Issue by matthewjurczyk** [kolide/fleet#1711]
Build an image from a Dockerfile
root@m7-osquery-1:~# docker build -t kolide/fleet -f fleet/Dockerfile .
Sending build context to Docker daemon  111.5MB
Step 1/5 : FROM alpine
 ---> 3fd9065eaf02
Step 2/5 : MAINTAINER Kolide Developers <engineering@kolide.co>
 ---> Using cache
 ---> c92727989042
Step 3/5 : RUN apk --update add ca-certificates
 ---> Using cache
 ---> b8626791c3e2
Step 4/5 : COPY ./build/linux/fleet /usr/bin/fleet
COPY failed: stat /var/lib/docker/tmp/docker-builder943348346/build/linux/fleet: no such file or directory

**Comment by groob** [comment]
You need to build fleet first before you can add it to the container. See the appropriate makefile target. https://github.com/kolide/fleet/blob/998e81db6da7aa1cf5f31ffcaa07868ba62036be/Makefile#L179-L182

The Dockerfile copies an existing fleet binary into the container.

**Comment by matthewjurczyk** [comment]
Alright i may be missing a step....i'm missing packages is there a command i run before make docker-build-release

root@m7-osquery-1:~/gopath/src/github.com/mygithubname/fleet# make docker-build-release 
GOOS=linux go build -i -o build/linux/fleet -ldflags " -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.appName=fleet -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.version=1.0.6-19-g998e81d -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.branch=master -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.revision=998e81db6da7aa1cf5f31ffcaa07868ba62036be -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.buildDate=2018-02-16T16:37:20Z -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.buildUser=root -X github.com/kolide/fleet/vendor/github.com/kolide/kit/version.goVersion=go1.9.4" ./cmd/fleet
cmd/fleet/config_dump.go:6:2: cannot find package "github.com/kolide/fleet/server/config" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/config (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/config (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/config (from $GOPATH)
cmd/fleet/prepare.go:12:2: cannot find package "github.com/kolide/fleet/server/datastore/mysql" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/datastore/mysql (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/datastore/mysql (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/datastore/mysql (from $GOPATH)
cmd/fleet/serve.go:21:2: cannot find package "github.com/kolide/fleet/server/health" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/health (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/health (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/health (from $GOPATH)
cmd/fleet/prepare.go:13:2: cannot find package "github.com/kolide/fleet/server/kolide" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/kolide (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/kolide (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/kolide (from $GOPATH)
cmd/fleet/serve.go:23:2: cannot find package "github.com/kolide/fleet/server/launcher" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/launcher (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/launcher (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/launcher (from $GOPATH)
cmd/fleet/serve.go:24:2: cannot find package "github.com/kolide/fleet/server/mail" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/mail (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/mail (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/mail (from $GOPATH)
cmd/fleet/prepare.go:14:2: cannot find package "github.com/kolide/fleet/server/pubsub" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/pubsub (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/pubsub (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/pubsub (from $GOPATH)
cmd/fleet/prepare.go:15:2: cannot find package "github.com/kolide/fleet/server/service" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/service (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/service (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/service (from $GOPATH)
cmd/fleet/serve.go:27:2: cannot find package "github.com/kolide/fleet/server/sso" in any of:
	/root/gopath/src/github.com/mygithubname/fleet/vendor/github.com/kolide/fleet/server/sso (vendor tree)
	/usr/local/go/src/github.com/kolide/fleet/server/sso (from $GOROOT)
	/root/gopath/src/github.com/kolide/fleet/server/sso (from $GOPATH)
Makefile:180: recipe for target 'docker-build-release' failed
make: *** [docker-build-release] Error 1

**Comment by offsecn00b** [comment]
identical issue here with #>make docker-build-release

Doesn't seem to be downloading the go dependencies into $GOPATH (or anywhere)

EDIT: pretty sure this is GOPATH or GOROOT  issue but haven't gotten further.

**Comment by zwass** [comment]
I believe this issue should be resolved if `GOPATH` is configured properly. If anyone needs help with this, please connect with us on osquery Slack.

https://github.com/kolide/fleet/pull/1896 ensures that the binary is built before running the Dockerfile.
