### ISSUE TITLE
long sql statement

### ISSUE THREAD

**Issue by kemalbayar** [kolide/fleet#1713]
### What version of `fleet` are you using (`fleet version --full`)?
1.0.6

### What operating system are you using?
Windows

### What did you do?
I saved the following sql statement as a query and I used it in a query pack

SELECT * FROM windows_events WHERE eventid in ('1100','1101','1102','1104','4608','4609','4624','4625','4634','4657','4660','4663','4670','4688','4689','4698','4699','4700','4701','4702','4719','4720','4722','4723','4723','4724','4724','4725','4726','4727','4728','4729','4730','4731','4732','4733','4734','4735','4737','4738','4739','4767','4740','4741','4742','4743','4744','4745','4746','4747','4748','4749','4750','4751','4752','4753','4754','4755','4756','4757','4758','4759','4760','4761','4762','4763','4764','4800','4801','4817','5024','5025','5140','5142','5143','5144','5145');

### What did you expect to see?
I expect the logs created by related scheduled query pack (in osquery_results on Kolide)

### What did you see instead?
no logs created.  But when I shorten the query, log formation is starting
for example SELECT * FROM windows_events WHERE eventid in ('1100','1101','1102','1104');

**Comment by kemalbayar** [comment]
![image](https://user-images.githubusercontent.com/33925821/36479569-375fe644-171a-11e8-82bf-6c2f4ccf7223.png)

in addition to above situation, (in query pack page)  the field on the right side doesnt contain exact query

**Comment by zwass** [comment]
@kemalbayar Let's try a couple of things:

1) Your screenshot shows that there is a scrollbar in the query text... Does it not include the rest of the query if you scroll down?

2) What do you get for `show create table queries` in your MySQL DB? Queries were originally stored as `varchar(255)` which might have caused this problem, but there was a migration quite a while ago that updated those columns to `text` type (https://github.com/kolide/fleet/blob/master/server/datastore/mysql/migrations/tables/20170117025759_IncreaseQueryLength.go).

**Comment by kemalbayar** [comment]
@zwass  
1-when I scroll down, the rest of the statement doesn't appear. (i tought that it's wouldn't be asked thus I didn't indicate it, but no problem, you are right for asking). This is a problem need to be fixed
2- answer is in the picture.
![image](https://user-images.githubusercontent.com/33925821/36526366-05d03b06-17bf-11e8-864a-315de1812f7d.png)

**Comment by zwass** [comment]
So I was able to partially repro this...

What I noticed is that while the UI sidebar view cuts off the query, the backend does return the entire query:

<img width="1651" alt="screen shot 2018-02-22 at 9 47 31 am" src="https://user-images.githubusercontent.com/575602/36554976-9697dc02-17b5-11e8-88e5-5bb406c38f47.png">

This is also evidenced in the "edit query" page, where we see it continue to the end:

<img width="1072" alt="screen shot 2018-02-22 at 9 49 00 am" src="https://user-images.githubusercontent.com/575602/36554995-add9e8b0-17b5-11e8-964f-4761e944c8aa.png">

I don't think it is intentional that the query is truncated in that sidebar view without any indication that there is more. We should fix that, but it's probably going to be low priority.

I'm still wondering about why the query would not _execute_ on your host when it is long like this. Can you try turning on `--tls_dump` on a host that should be receiving this query and seeing if it receives the entire query?

**Comment by kemalbayar** [comment]
I tried that your instructions but on different way and I recognized that:

firstly I changed the query as SELECT * FROM windows_events WHERE eventid in ('4776','1102') and saved, after that, I check the client logs using --tls_dump=true --verbose flags in osquery.flags file, the output is that:


I0223 12:30:40.742208  6912 scheduler.cpp:75] Executing scheduled query pack/Windows_test_events/Windows Events: SELECT * FROM windows_events WHERE eventid in ('4776','1102');

It seems the exact query is getting by the client but although the related event ids is created and continue to be creating, I observed that only 1102 eventid logs are written to osquery_results log file

Also, earlier I tried without changing the long query and I saw the exact query in output of the client

There is inconsistency related to the Kolide config or processing sql statements I think

**Comment by zwass** [comment]
If the exact query is making it to osquery, this does not sound like a Kolide issue. Can you reproduce this without a TLS server at all (by adding a config with these queries scheduled)? If so, please file an issue with the osquery repo.

**Comment by kemalbayar** [comment]
I've tried this on a osquery agent without tls server and I see the exact (long) query in the output (--verbose) but not happening any logging action in osquery_results (local file on the client)

When the query to be changed to Select * from windows_events where eventid=1102;  no logging problem



C:\Users\Administrator>\ProgramData\osquery\osqueryd\osqueryd.exe --config_path=\programdata\osquery\osquery.conf --flagfile=\programdata\osquery\osquery.flags
I0226 15:40:33.200104  3804 init.cpp:380] osquery initialized [version=2.11.2]
I0226 15:40:33.262603  3804 system.cpp:344] Found stale process for osqueryd (3864)
I0226 15:40:33.262603  3804 system.cpp:377] Writing osqueryd pid (5020) to \ProgramData\osquery\osqueryd.pidfile
I0226 15:40:33.262603  3804 extensions.cpp:300] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0226 15:40:33.778230  3360 watcher.cpp:549] osqueryd watcher (5020) executing worker (5876)
I0226 15:40:33.809479   896 init.cpp:377] osquery worker initialized [watcher=5020]
I0226 15:40:33.825103   896 rocksdb.cpp:132] Opening RocksDB handle: \ProgramData\osquery\osquery.db
I0226 15:40:33.981364  5860 interface.cpp:338] Extension manager service starting: \\.\pipe\osquery.em
I0226 15:40:36.083745  5800 events.cpp:746] Starting event publisher run loop: windows_event_log
I0226 15:40:36.083745   896 main.cpp:106] Not starting the distributed query service: Distributed query service not enabled.
I0226 15:40:39.107058  3368 scheduler.cpp:75] Executing scheduled query system_info: SELECT * FROM windows_events WHERE eventid in ('1100','1101','1102','1104','4608','4609','4624','4625','4634','4657','4660','4663','4670','4688','4689','4698','4699','4700','4701','4702','4719','4720','4722','4723','4723','4724','4724','4725','4726','4727','4728','4729','4730','4731','4732','4733','4734','4735','4737','4738','4739','4767','4740','4741','4742','4743','4744','4745','4746','4747','4748','4749','4750','4751','4752','4753','4754','4755','4756','4757','4758','4759','4760','4761','4762','4763','4764','4800','4801','4817','5024','5025','5140','5142','5143','5144','5145');

**Comment by kemalbayar** [comment]
I will open an issue. Thanks

**Comment by kemalbayar** [comment]
https://github.com/facebook/osquery/issues/4157
