### ISSUE TITLE
not existed table or config related warning

### ISSUE THREAD

**Issue by kemalbayar** [kolide/fleet#1716]
currently I have no file_events related config but I see the following error on my client 
(output of --tls_dump=true --verbose)
I may have used this table before but not currently

E0223 13:12:01.392943 92772 scheduler.cpp:80] Error executing scheduled query file_events: Error running query: no such table: file_events

### What version of `fleet` are you using (`fleet version --full`)?
1.0.6

**Comment by zwass** [comment]
When there is a FIM config applied, a `SELECT * FROM file_events` query is added. This is not expected behavior IMO, and will be fixed with the release of fleetctl.

**Comment by kemalbayar** [comment]
Also sometime i see non-existed config logs like that. for your information. Thanks

**Comment by marpaia** [comment]
#1792 merged fleetctl into master, resolving this issue for 2.0.0
