### ISSUE TITLE
FIM problem

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1721]
Hi, 
I have configured FIM to monitor changes on /etc and /usr/bin like this:
curl --insecure "https://kolide_server_ip/api/v1/kolide/fim" -H "Authorization: Bearer token"
{
  "payload": {
    "interval": 300,
    "file_paths": {
      "etc": [
        "/etc/%%"
      ],
      "usr": [
        "/usr/bin/%%"
      ]
    }
  }
}

Enabled --disable_events=false option and scheduled a query on file_events table
But i'm getting results from /var on the kolide results file:

{"name":"file_events","hostIdentifier":"xxxx","calendarTime":"Mon Mar  5 08:46:10 2018 UTC","unixTime":"1520239570","epoch":"0","counter":"0","decorations":{"address":"x.x.x.x","host_uuid":"423DD70A-685E-5E6E-D597-9A709514F0F8","hostname":"xxxx"},"columns":{"action":"UPDATED","atime":"1520239568","category":"etc","ctime":"1520239569","gid":"0","hashed":"1","inode":"1073","md5":"e3b286987af45735c68a92f8a045bdf8","mode":"0644","mtime":"1520239569","sha1":"d4c773bf0317f8f3b96183f9839fcc40b85cc31c","sha256":"dafac1508f410fb7224da015f61fd69ad8cd5a2766867e720c8dc9004d05515d","size":"1622856","target_path":"\/var\/log\/httpd\/ssl_request_log","time":"1520239569","transaction_id":"0","uid":"0"},"action":"added"}

### What version of `fleet` are you using (`fleet version --full`)?
 - version 1.0.6
  branch:       master
  revision:     45165aa29aae52346ed1c458f19b89947d315c61
  build date:   2017-12-04T22:50:27Z
  build user:   marpaia
  go version:   go1.9.2
### What operating system are you using?
CentOS Linux release 7.4.1708 (Core)

**Comment by rubenrodr-versia** [comment]
I have test if exclude_path would solve this issue, but kolide is not getting the exclude_path:

`# curl --insecure -X "PATCH" "https://kolideserver/api/v1/kolide/fim" -H "Authorization: Bearer token"  -H "Content-Type: text/plain; charset=utf-8" -d $'{ "interval": 300, "file_paths": { "System_Configuration": [ "/etc/%%" ], "Mitre_T1156_bashrc_bash_profile": [ "/home/%/.bashrc", "/home/%/.bash_profile" ], "Sudoers_change": [ "/etc/sudoers", "/etc/sudo-ldap.conf", "/etc/sudo.conf", "/etc/sudoers.d/%%" ], "Binary_changes": [ "/usr/bin/%%", "/usr/sbin/%%", "/usr/local/bin/%%", "/usr/local/sbin/%%" ] },` **"exclude_paths": { "var_log": [ "/var/log/%%" ] }**` }'
{}`

`curl --insecure "https://kolideserver/api/v1/kolide/fim" -H "Authorization: Bearer token"`
`{
  "payload": {
    "interval": 300,
    "file_paths": {
      "Binary_changes": [
        "/usr/bin/%%",
        "/usr/sbin/%%",
        "/usr/local/bin/%%",
        "/usr/local/sbin/%%"
      ],
      "Mitre_T1156_bashrc_bash_profile": [
        "/home/%/.bashrc",
        "/home/%/.bash_profile"
      ],
      "Sudoers_change": [
        "/etc/sudoers",
        "/etc/sudo-ldap.conf",
        "/etc/sudo.conf",
        "/etc/sudoers.d/%%"
      ],
      `**"System_Configuration"**`: [
        "/etc/%%"
      ]
    }
  }
}`

and events related to /var/log files keep being generated related to "System_Configuration" (etc directory):

`{"name":"file_events","hostIdentifier":"xxxx","calendarTime":"Thu Mar  8 15:52:47 2018 UTC","unixTime":"1520524367","epoch":"0","counter":
"0","decorations":{"address":"x.x.x.x","host_uuid":"uid","hostname":"xxxx"},"columns":{"action":"UPD
ATED","atime":"1520524361","category":`**"System_Configuration"**`,"ctime":"1520524362","gid":"0","hashed":"1","inode":"2237","md5":"f919859cdfe98a527a57c00a3cdd2822","mode
":"0644","mtime":"1520524362","sha1":"e3c963d32579bcfeaae889a20a70985d32072058","sha256":"54a8ef711d1788059fa2856b4a1495b7475cb1d68e90c809dd87f5fe98b663b1","size":"11
392986","target_path":"\/var\/log\/httpd\/ssl_request_log","time":"1520524362","transaction_id":"0","uid":"0"},"action":"added"}`

Thanks.

**Comment by rubenrodr-versia** [comment]
A symbolik link exists on /etc/httpd/logs pointing to /var/log/httpd wich causes the entries in the results file. I have launched osquery manually on one host with the following FIM config:

`  "file_paths": {`
`    "Cambios_Config_etc": [`
`      "/etc/%%"`
`      ],`
`    "Mitre_T1156_bashrc_bash_profile": [`
`      "/home/%/.bashrc",`
`      "/home/%/.bash_profile"`
`      ],`
`    "Sudoers_change": [`
`      "/etc/sudoers",`
`      "/etc/sudo-ldap.conf",`
`      "/etc/sudo.conf",`
`      "/etc/sudoers.d/%%"`
`      ],`
`    "Binary_changes": [`
`      "/usr/bin/%%",`
`      "/usr/sbin/%%",`
`      "/usr/local/bin/%%",`
`      "/usr/local/sbin/%%"`
`      ]`
`  },`
`  "exclude_paths": {`
`    "Cambios_Config_etc": [`
`      "/etc/httpd/logs/%%"`
`      ]`
`  },`

And works fine, no /var/log/httpd entries on osqueryd.results
I have tried to include exclude_paths on fim using kolide api, but it's not working as expected or i'm doing something wrong:

`curl --insecure -X "PATCH" "https://kolide_server/api/v1/kolide/fim" -H "Authorization: Bearer token" -d $'{ "interval": 300, "file_paths": { "Cambios_Config_etc": [ "/etc/%%" ], "Mitre_T1156_bashrc_bash_profile": [ "/home/%/.bashrc", "/home/%/.bash_profile" ], "Sudoers_change": [ "/etc/sudoers", "/etc/sudo-ldap.conf", "/etc/sudo.conf", "/etc/sudoers.d/%%" ], "Binary_changes": [ "/usr/bin/%%", "/usr/sbin/%%", "/usr/local/bin/%%", "/usr/local/sbin/%%" ] }, "exclude_paths": { "Cambios_Config_etc": [ "/etc/httpd/logs/%%" ] } }'`
`{}`

`curl --insecure "https://kolide_server/api/v1/kolide/fim" -H "Authorization: Bearer token"`
`{`
`  "payload": {`
`    "interval": 300,`
`    "file_paths": {`
`      "Binary_changes": [`
`        "/usr/bin/%%",`
`        "/usr/sbin/%%",`
`        "/usr/local/bin/%%",`
`        "/usr/local/sbin/%%"`
`      ],`
`      "Cambios_Config_etc": [`
`        "/etc/%%"`
`      ],`
`      "Mitre_T1156_bashrc_bash_profile": [`
`        "/home/%/.bashrc",`
`        "/home/%/.bash_profile"`
`      ],`
`      "Sudoers_change": [`
`        "/etc/sudoers",`
`        "/etc/sudo-ldap.conf",`
`        "/etc/sudo.conf",`
`        "/etc/sudoers.d/%%"`
`      ]`
`    }`
`  }`
`}`

Is exclude_paths directive supported by fim kolide api ?

Thanks.

**Comment by rubenrodr-versia** [comment]
Hi,

I have updated to the latest fleet:
`# fleet version`
`fleet version 1.0.7-1-g2ded63e`

and now i cannot change/delete the fim configuration (**HTTP/1.1 405 Method Not Allowed**):

`#  curl --verbose --insecure "https://kolide_host/api/v1/kolide/fim" -H "Authorization: Bearer token" -H "Content-Type: text/plain; charset=utf-8" -d $'{"interval": 500}'`
`* About to connect() to kolide_host port 443 (#0)`
`*   Trying xxx.xxx.xxx.xxx...`
`* Connected to kolide_host (xxx.xxx.xxx.xxx) port 443 (#0)`
`* Initializing NSS with certpath: sql:/etc/pki/nssdb`
`* skipping SSL peer certificate verification`
`* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`
`* Server certificate:`
`*       subject: E=XXXXXX,CN=kolide_host,OU=XXXX,O=XXXXX,L=XXXXXX,ST=XXXX,C=XX`
`*       start date: Dec 27 10:38:24 2017 GMT`
`*       expire date: Jan 04 10:38:24 2028 GMT`
`*       common name: kolide_host`
`*       issuer: E=XXXX,CN=kolide_host,OU=XXXXX,O=XXXXX,L=XXXXX,ST=XXXXX,C=XX`
`> POST /api/v1/kolide/fim HTTP/1.1`
`> User-Agent: curl/7.29.0`
`> Host: kolide_host`
`> Accept: */*`
`> Authorization: Bearer token`
`> Content-Type: text/plain; charset=utf-8`
`> Content-Length: 17`
`>`
`* upload completely sent off: 17 out of 17 bytes`
`< HTTP/1.1 405 Method Not Allowed`
`< Date: Wed, 25 Apr 2018 09:50:04 GMT`
`< Content-Length: 0`
`<`
`* Connection #0 to host kolide_host left intact`

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
Hi,

I have upgraded to fleet 1.0.8:

`#fleet version --full`
`fleet - version 1.0.8`
`  branch:       changelog_1.0.8`
`  revision:     eb85e71181c90082808107ecabf655bcea94a117`
`  build date:   2018-05-04T00:01:31Z`
`  build user:   zwass`
`  go version:   go1.9.2`

And the same "HTTP/1.1 405 Method Not Allowed" error.

**Comment by lefthand** [comment]
I'm not seeing the 405 error but I am also wanting to exclude some paths and it doesn't look like that's supported yet.

**Comment by benjamin-hering** [comment]
I'm encountering a similar issue. Is the 'exclude_paths' settings not supported through the Kolide FIM API?

I'm trying to drop in the config like so:

```
$ curl -X "PATCH" "https://<server-ip>/api/v1/kolide/fim" \
     -H "Authorization: Bearer token" \
     -H "Content-Type: text/plain; charset=utf-8" \
     -d $'{
    "interval": 300,
    "file_paths": {
      "etc-lc": [
        "/etc/lc/%%"
      ],
      "lcapp": [
        "/home/lcapp/%%"
      ],
      "tmp": [
        "/tmp/%%",
        "/var/tmp/%%"
      ]
    },
    "exclude_paths": {
    "lcapp": [
    	"/home/lcapp/%/logs/%%"
             ]
       	 }
    }'
{}
```

But checking the FIM through the API shows the excluded files section dropped:

```
$ curl "https://<server-ip>/api/v1/kolide/fim"      -H "Authorization: Bearer token"
{
  "payload": {
    "interval": 300,
    "file_paths": {
      "etc-lc": [
        "/etc/lc/%%"
      ],
      "lcapp": [
        "/home/lcapp/%%"
      ],
      "tmp": [
        "/tmp/%%",
        "/var/tmp/%%"
      ]
    }
  }
}
```

**Comment by zwass** [comment]
Those of you having these problems... Can you please try testing with the [Fleet 2.0 RC1](https://github.com/kolide/fleet/releases/tag/2.0.0-rc1)? It will help to take a look at the docs on [configuring osquery](https://github.com/kolide/fleet/blob/master/docs/cli/file-format.md#osquery-configuration-options).

**Comment by benjamin-hering** [comment]
@zwass can you confirm my assumptions about testing this FIM in Fleet 2.0. I'm gathering that in Fleet 1.0 is using the API, but Fleet 2.0 is via the fleetctl. 

My assumption gathering information is that we pull existing options using

```
fleetctl get options > options.yaml
```

Add in the exclude paths in the format from what you linked above, and then re-apply with

```
fleetctl apply -f ./options.yaml
```

That seems right?

Also, in order for this to work, does the config_refresh osquery flag then need to be set to a non-zero (non-default) value on the host?

**Comment by zwass** [comment]
@benjamin-hering that all sounds correct.

**Comment by rubenrodr-versia** [comment]
Hi,

I have upgraded to fleet 2.0.0-rc2

`# fleet version --full`
`fleet - version 2.0.0-rc2`
`  branch:       master`
`  revision:     c4f2850e38a611a44189adf80e433bf38046e387`
`  build date:   2018-06-18T19:21:18Z`
`  build user:   zwass`
`  go version:   go1.10.2`

`# fleetctl -v`
`fleetctl - version 2.0.0-rc2`
`  branch:       master`
`  revision:     c4f2850e38a611a44189adf80e433bf38046e387`
`  build date:   2018-06-18T19:21:30Z`
`  build user:   zwass`
`  go version:   go1.10.2`

 and tried to configure FIM like this:

`# fleetctl get options`
`apiVersion: v1`
`kind: options`
`spec:`
`  config:`
`    decorators:`
`      always:`
`      - SELECT user AS username FROM logged_in_users WHERE user <> '' ORDER BY time`
`        LIMIT 1`
`      interval:`
`        "3600": SELECT total_seconds AS uptime FROM uptime`
`      load:`
`      - SELECT version FROM osquery_info`
`      - SELECT uuid AS host_uuid FROM system_info`
`    options:`
`      distributed_interval: 3`
`      distributed_tls_max_attempts: 3`
`      logger_plugin: tls`
`      logger_tls_endpoint: /api/v1/osquery/log`
`      logger_tls_period: 10`
`  overrides:`
`    platforms:`
`      linux:`
`        decorators:`
`          interval:`
`            "3600": SELECT total_seconds AS uptime FROM uptime`
`          load:`
`          - SELECT * FROM cpuid`
`          - SELECT * FROM docker_info`
`        exclude_paths:`
`          etc:`
`          - /etc/redis/%%`
`        file_paths:`
`          etc:`
`          - /etc/%%`
`        options:`
`          config_refresh: 60`
`          disable_events: false`
`          distributed_interval: 10`
`          distributed_tls_max_attempts: 3`
`          docker_socket: /etc/run/docker.sock`
`          events_expiry: 3600`
`          events_max: 50000`
`          events_optimize: true`
`          logger_plugin: tls`
`          logger_tls_endpoint: /api/v1/osquery/log`
`          logger_tls_period: 60`
`          schedule_timeout: 60`
`      windows:`
`        options:`
`          disable_events: false`
`          events_expiry: 3600`
`          events_max: 50000`
`          events_optimize: true`
`          windows_event_channels: System,Application,Setup,Security`

apply the config with fleetclt:

`# fleetctl apply -f options.yaml`
`[+] applied 3 queries`
`[+] applied 3 labels`
`[+] applied 1 packs`
`[+] applied options`

but if i check the FIM config via API i get:

`# curl "https://kolide_host/api/v1/kolide/fim" -H "Authorization: Bearer token"`
`{`
`  "payload": {`
`    "interval": 300`
`  }`
`}`

**Comment by zwass** [comment]
@rubenrodr-versia The FIM configuration has now been merged into the rest of the osquery configuration, so that API endpoint is only remaining to allow exporting from Fleet 1 to Fleet 2.

Based on the output of `fleetctl get options`, it looks like you successfully configured FIM. If you want to be extra sure of this, you could run an `osqueryd` with `--tls_dump` and inspect the config it receives.

**Comment by benjamin-hering** [comment]
@zwass Things are looking better now using fleetctl.

After applying the options, here's what I see from the fleetctl options

```
$ ./fleetctl get options 
apiVersion: v1
kind: options
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    exclude_paths:
      lcapp:
      - /home/lcapp/server-%/logs
    file_paths:
      etc-lc:
      - /etc/lc/%%
      lcapp:
      - /home/lcapp/%%
      tmp:
      - /tmp/%%
      - /var/tmp/%%
    options:
      config_refresh: 300
      config_tls_endpoint: /api/v1/osquery/config
      disable_distributed: false
      disable_watchdog: false
      distributed_interval: 120
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      distributed_tls_read_endpoint: /api/v1/osquery/distributed/read
      distributed_tls_write_endpoint: /api/v1/osquery/distributed/write
      hash_delay: 20
      host_identifier: hostname
      logger_plugin: tls
      logger_tls_endpoint: /api/v1/osquery/log
      logger_tls_period: 60
      pack_delimiter: /
      schedule_splay_percent: 15
      watchdog_level: 0
  overrides: {}

```
And then to be sure, I dropped a simple flag file on a testing host
```
# cat osquery.flags
--enroll_secret_path=/var/osquery/enroll_secret
--tls_hostname=<hostname>
--tls_server_certs=/var/osquery/server.pem
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=10
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
```
And then did a config_check and config_dump
```
# osqueryi --flagfile=/etc/osquery/osquery.flags --config_check --config_dump
{
	"tls_plugin": {
		"decorators": {
			"load": ["SELECT uuid AS host_uuid FROM system_info;", "SELECT hostname AS hostname FROM system_info;"]
		},
		"exclude_paths": {
			"lcapp": ["\/home\/lcapp\/server-%\/logs"]
		},
		"file_paths": {
			"etc-lc": ["\/etc\/lc\/%%"],
			"lcapp": ["\/home\/lcapp\/%%"],
			"tmp": ["\/tmp\/%%", "\/var\/tmp\/%%"]
		},
		"options": {
			"config_refresh": "300",
			"config_tls_endpoint": "\/api\/v1\/osquery\/config",
			"disable_distributed": "false",
			"disable_watchdog": "false",
			"distributed_interval": "120",
			"distributed_plugin": "tls",
			"distributed_tls_max_attempts": "3",
			"distributed_tls_read_endpoint": "\/api\/v1\/osquery\/distributed\/read",
			"distributed_tls_write_endpoint": "\/api\/v1\/osquery\/distributed\/write",
			"hash_delay": "20",
			"host_identifier": "hostname",
			"logger_plugin": "tls",
			"logger_tls_endpoint": "\/api\/v1\/osquery\/log",
			"logger_tls_period": "60",
			"pack_delimiter": "\/",
			"schedule_splay_percent": "15",
			"watchdog_level": "0"
		},
		"packs": {
			"Find Evil": {
				"queries": ""
			}
		}
	}
}
``` 
and it looks like it shows up there just fine.
