### ISSUE TITLE
osquery agent host name changes

### ISSUE THREAD

**Issue by kemalbayar** [kolide/fleet#1726]
Osquery agent host name changes isn't reflected to Kolide fleet server. Despite the host names changed they still keep appearing as they were first added

**Comment by kemalbayar** [comment]
I didn't waited for an hour but I ran the (distributed) query "select hostname from system_info" a short time after I changed the hostname and I saw the host name changed on UI.
lastly, after I changed the hostname one more time, I ran the query again and I noticed the hostname and computer_name is different 
(query result is that: hostname: win2008-2 but computer_name: win2008-2-23)
and On the UI is still seen the hostname as win2008-2
When I check on the computer via login I see that computer name, full computer name and netbios name is same win2008-2-23

what could be the situation?

COMMENT EDIT:

I noticed the hostname and computer_name is now same win2008-2-23.
in this case, it is need a while to take effect the changes but what do you think about the difference between hostname and computer_name ?

(like the situation above, after a while both columns became same too)

![image](https://user-images.githubusercontent.com/33925821/37586022-2417c906-2b6c-11e8-91ba-41c92d0f3807.png)

**Comment by zwass** [comment]
If Fleet is showing the correct data from osquery (after up to an hour delay), then things are working fine.

The Fleet UI is using the value returned for the `hostname` column of system info. I think this is the most generally useful value we can show (note that `computer_name` is marked as "optional" in the [osquery schema](https://osquery.io/schema/2.11.2#system_info)).

It sounds like there things are working as expected with Fleet, so I'm going to close out this issue. Happy to continue discussing if there are further clarifications needed.

**Comment by kemalbayar** [comment]
The only thning I wondered is the difference between hostname and computer_name columns for a while. Thanks.

**Comment by NicolaTaylorAS** [comment]
Possibly this is worth a new issue, but I'd really like the ability to specify the query used to populate the host name in the UI, since I'm monitoring end user workstations that like to change hostname when they change networks. ie. Have the hosts identified by `system_info.local_hostname`, or even `system_info.uuid`
