### ISSUE TITLE
Labels not seen in Select Target field

### ISSUE THREAD

**Issue by kemalbayar** [kolide/fleet#1731]
Created labels aren't seen in Select Target field

![image](https://user-images.githubusercontent.com/33925821/37820696-82ba410e-2e92-11e8-932a-5319a07ef194.png)

LABELS section is empty...

![image](https://user-images.githubusercontent.com/33925821/37820728-9c51955e-2e92-11e8-8050-0cb018158781.png)

when I write the label name then it's appearing

![image](https://user-images.githubusercontent.com/33925821/37820763-b54b6256-2e92-11e8-817c-1083389938ad.png)

**Comment by zwass** [comment]
This is working as expected. Only the built in labels display until you start entering the name of another label.
