### ISSUE TITLE
Distributed query ruins distributed plugin

### ISSUE THREAD

**Issue by yuvalapidot** [kolide/fleet#1735]
### What version of `fleet` are you using (`fleet version --full`)?
- version 1.0.6
  branch: 	master
  revision: 	45165aa29aae52346ed1c458f19b89947d315c61
  build date: 	2017-12-04T22:50:27Z
  build user: 	marpaia
  go version: 	go1.9.2

### What operating system are you using?
Fleet installed on Ubuntu 16.04, issue with distributed queries on Windows

### What did you do?
1. From ui run a distributed query on a Windows machine for example SELECT * FROM users. Result should return after a short while (check for sanity)
2. From ui run a distributed query on the same Windows machine, this time query services (Windows only) table: SELECT * FROM services (web ui doesn't recognize 'services' as a table name - maybe related to problem?). Result won't return even after a long while.
3. Stop the running query.
4. Try running query from step 1 again. Result won't return even after a long while.
5. Only after few hours machine is queryable again.
(Some scheduled querieswhere running in the background - probably not relevant)

### What did you expect to see?
Expected to receive results from services table.
Expected to receive results from tables after unsuccessfully querying another table.

### What did you see instead?
Results won't return from services table.
Results won't return from any table after querying the services table unsuccessfully.
Following is what I see in the kolide status logs grepping the specific machine name:
1. After first querying for users table: one line - executing distributed query: kolide_distributed_query_207... SELECT * FROM users.
2. While waiting for results from services table: lines come every ~10 seconds, similar to before: executing distributed query: kolide_distributed_query_208... SELECT * FROM services
(number of query doesn't change - 208).
3. Stopping the running query will stop the above log messages.
4. While waiting for results from the users table again, logs are similar to services table: come every ~10 seconds: kolide_distributed_query_209... SELECT * FROM users. (209 doesn't increase).

Running osqueri on the machine - results from both 'users' table and 'services' table is received immediately.
I suspect the problem is somewhere in fleet not parsing the results well thus querying all over again, I don't know what might cause the fleet to not function further.

**Comment by groob** [comment]
Can you run `osqueryd` with a few extra flags: `--verbose` and `--tls_dump`
These flags will force osqueryd to dump all the HTTP traffic to your standard output, so we can see if you're running into some bug with osquery.

**Comment by yuvalapidot** [comment]
@groob Sorry, probably an osquery bug.
I did as you suggested and made the same experiment again.
After querying 'users' I see in the output that osqueryd call to distributed/write.
After querying 'services' it doesn't call to distributed/write, just continue with distributed/read.
After this, any table I query will not call distributed/write again.

Should this be moved to facebook/osquery?

Thanks!

**Comment by groob** [comment]
Can you post the log you're seeing?

**Comment by defensivedepth** [comment]
I am seeing the same behavior: Fleet 1.0.6, osquery 2.11.2 on Win10 Pro + Server 2012 R2 + Server 2016.

I run a basic query from the Fleet UI (select * from osquery_info), and it returns the expected data.

I run select * from services, and the Fleet UI just spins; I Stop the query after a couple min.

I run the same basic query (select * from osquery_info), and the Fleet UI just spins. The target system appears online from Fleet's perspective, and the osqueryd service is running. Once I restart the osqeryd service, I can run queries again. 
  
Here are the relevant logs:

https://gist.githubusercontent.com/defensivedepth/2ede8a11419e438f4198492102fb4fbb/raw/2bec64a515111e809fbea2319f0d380dfb6552e9/gistfile1.txt

**Comment by yuvalapidot** [comment]
@groob
Sorry for the delay - I was OOO and not near computer.
Here are my logs showing the problem: [logs](https://gist.github.com/yuvalapidot/7a42c48941c1733f8208f85dd65e8916)
Please look for kolide_distributed_query_222, kolide_distributed_query_223 and kolide_distributed_query_224.

Hope this helps.

**Comment by zwass** [comment]
Is everyone experiencing this on Windows? Looking at the logs, it seems that the queries are making it to `osqueryd`, but it is not writing the results back to the server. It looks to me like an osquery bug.

**Comment by groob** [comment]
This is possibly related https://github.com/facebook/osquery/issues/4187

**Comment by zwass** [comment]
Thanks @defensivedepth.

Closing this as it's an osquery issue.

See facebook/osquery#4187.
