### ISSUE TITLE
pack targets after disable / re-enable the query pack

### ISSUE THREAD

**Issue by Apptestingrd** [kolide/fleet#1736]
The targets which selected in 'select pack target' field disappears after the query pack disable and then re-enable, thus, no 'osquery agents' receive the queries which in those query packs.
to have the queries be delivered to the agents, the targets must be re-selected by editing the query packs which was previously disabled and then re-enabled

**Comment by Apptestingrd** [comment]
@zwass 

<img width="954" alt="1" src="https://user-images.githubusercontent.com/38127874/39299697-0a946490-4952-11e8-959f-b95a9b4692b4.png">

![2](https://user-images.githubusercontent.com/38127874/39299702-0db8c166-4952-11e8-9d4b-ee8d67ece351.png)

![3](https://user-images.githubusercontent.com/38127874/39299708-0ff5a8ae-4952-11e8-830b-2f69073ee140.png)

![4](https://user-images.githubusercontent.com/38127874/39299711-123cbc4c-4952-11e8-93d7-c0e1a2e670d7.png)

**Comment by marpaia** [comment]
#1792 merged fleetctl into master, resolving this issue for 2.0.0
