### ISSUE TITLE
Question: Updates against Collins Database

### ISSUE THREAD

**Issue by akamalov** [kolide/fleet#1739]
This is a question, not an issue raised. Is it possible to use Collins as the database to insert OS-related information? Collins is an inventory database, I am wondering if I can start feeding information to it directly from Fleet.

Thanks again.

**Comment by zwass** [comment]
Can you tell us more about what kind of data you'd like to feed through this integration?

**Comment by akamalov** [comment]
Thanks for replying Zachary. I want to feed hardware info, as well as tags
associated with the deployed node. Once populated, we are planning to use
Collins as a dynamic inventory for Ansible.


Thanks yet again,

Alex

**Comment by zwass** [comment]
You could set up scheduled queries that retrieve the data you are interested in, then run a script or some other program on the Fleet server to process the data and write it to your DB.

I'm going to close out this issue. If you have further questions, let's discuss on the [osquery Slack](https://osquery-slack.herokuapp.com/).
