### ISSUE TITLE
Missing docker image: kolide/fleet:1.0.7

### ISSUE THREAD

**Issue by MMeent** [kolide/fleet#1750]
### What version of `fleet` are you using (`fleet version --full`)?
tried 1.0.7, full n/a due to circumstances

### What operating system are you using?
Kubernetes/docker image

### What did you do?
I used "kolide/fleet:1.0.7" as my docker image in a deployment spec template, and started it.

### What did you expect to see?
The pod should spin up and start.

### What did you see instead?
There is no 1.0.7-image for kolide/fleet, so I'm getting `failed to pull image "kolide/fleet:1.0.7" : ... image kolide/fleet:1.0.7 not found Error syncing pod`

### What do I want to happen
Please provide a version-numbered image on e.g. dockerhub for this and/or other releases.

**Comment by groob** [comment]
@MMeent the 1.0.7 image is there, but it's tagged as `kolide/fleet:bb6f3af` which is the git commit for that specific release.

**Comment by MMeent** [comment]
Ah, OK. That does make it quite difficult though to see which version of kolide/fleet you're running just based on the version tag. Can it maybe be tagged with the version number as well?

**Comment by groob** [comment]
Yeah I think that's a good idea.

**Comment by MMeent** [comment]
Thanks!
