### ISSUE TITLE
RFC: PostgreSQL Support / MySQL Deprecation

### ISSUE THREAD

**Issue by marpaia** [kolide/fleet#1761]
When we started working on Fleet, we chose MySQL as the relational database technology. Since then, Kolide has shifted internally to use PostgreSQL instead and is starting to explore CockroachDB where performance and features allow.

We know that MySQL has been a pain point for many folks that use Fleet. At Kolide, we're reasoning about refactoring the data implementation of Fleet so that we can use our ever-improving PostgreSQL infrastructure.

Some questions that we have for existing users of Fleet are:

- If you use Fleet, is MySQL a pain-point for you?
  - If so, would migrating to Postgres be preferable to continuing to manage MySQL?
- If MySQL support was deprecated in favor of Postgres, would that effect your decision to continue using Fleet?
  - What if we provided tools to assist with the migration as well as a grace period?

Some questions that we have for people that are not using Fleet yet, but are consider it are:

- Would you be more likely to try Fleet if Postgres was supported, but not MySQL?
- Is MySQL-only support keeping you from adopting Fleet?

**Comment by rubenrodr-versia** [comment]
If there is an assistant to migrate from mysql to postgresql i dont care about changing the database.
Is there any estimated release date for fleet on postgresql ?

**Comment by marpaia** [comment]
@rubenrodr-versia We don't have an ETA because before we commit to doing something like this, we wanted to gauge feedback from the community. If we do decide to move forward however, we will of course provide some tooling (perhaps built in to the `fleet` binary) for migrating your data. The new `fleectl` command will help with this as well.

**Comment by benbasscom** [comment]
MySQL is not a pain point for us - we can spin up RHEL boxes and install MySQL 5.7 fairly easily.  If using another DB is an option, would MSSQL or Oracle be an option?  Pretty much anything outside of those two would have to be supported in conjunction with the fleet deployment and not handed by our internal DB team.  We do have some MySQL institutional knowledge as we are also a Jamf shop, which also uses MySQL.

**Comment by marpaia** [comment]
Note this comment with more information on the mechanics of adding a Postgres implementation: https://github.com/kolide/fleet/issues/1610#issuecomment-345464698

**Comment by arogozin** [comment]
Interested in Postgres support!

**Comment by robusto** [comment]
MySQL support isn't a problem for us if Fleet's DB support remains as stable as it is today. However, most of our teams prefer PostgreSQL wherever possible. Solid migration tools are a must-have if the PG decision is made. 

Personally I think explicit support for a CockroachDB-backed deployment is interesting. It would potentially enable multi-region deployments which would make it simpler to enable multiple Fleet deployments closer to the various end-users of an international org.

**Comment by zwass** [comment]
Closing this issue as there are no current plans to make such a migration. Thanks for the input folks.
