### ISSUE TITLE
Scheduled Query Packs not executing 

### ISSUE THREAD

**Issue by benjamin-hering** [kolide/fleet#1775]
### What version of `fleet` are you using (`fleet version --full`)?

```
$ ./bin/fleet version --full
 - version 1.0.6
  branch: 	master
  revision: 	45165aa29aae52346ed1c458f19b89947d315c61
  build date: 	2017-12-04T22:50:27Z
  build user: 	marpaia
  go version: 	go1.9.2
```

### What operating system are you using?

CentOS 7

### What did you do?

Scheduled queries in the Kolide Fleet GUI for a simple query to snapshot the hosts file against a testing box every 30 seconds. Screenshots

![screen shot 2018-05-09 at 10 41 01 am](https://user-images.githubusercontent.com/7587027/39831677-112c6f78-537a-11e8-9b09-134ea0e88810.png)

![screen shot 2018-05-09 at 10 58 39 am](https://user-images.githubusercontent.com/7587027/39831701-1f7b495a-537a-11e8-8e27-cc1240b78cd3.png)

### What did you expect to see?

I expected to see snapshot results outputted to the osquery_results.log file on the fleet server with a snapshot of the hosts file every 30 seconds.

### What did you see instead?

I don't see any results. In troubleshooting, I ran osqueryd on my testing box in verbose mode with the following command. I don't see the scheduled query pack even reaching my test box.

```
/usr/bin/osqueryd --flagfile /etc/osquery/osquery.flags --logger_min_stderr 1 --config_path /etc/osquery/osquery.conf --verbose --tls_dump
```
However, when I run an ad-hoc query against the box, I do see them in the verbose osqueryd log on my test box.

![screen shot 2018-05-09 at 10 59 03 am](https://user-images.githubusercontent.com/7587027/39831747-3dc84836-537a-11e8-8212-461c082cd759.png)

That gives the following in my local test box's verbose osqueryd log

```
{"queries":{"kolide_distributed_query_126":[{"event":"","minute":"01","hour":"*","day_of_month":"*","month":"*","day_of_week":"*","command":"root run-parts \/etc\/cron.hourly","path":"\/etc\/cron.d\/0hourly"}]},"statuses":{"kolide_distributed_query_126":"0"},"node_key":"CNPwjP7zUTQOBYdrITB4GeOQlDw5uMZy"}
```

My default assumption is there's something silly and tiny in my osqueryd config, but my sanity checks can't seem to find it. Here's my flag file:

```
# cat /etc/osquery/osquery.flags
--force=true
--disable_watchdog=false
--watchdog_dely=120
--watchdog_level=1
--schedule_splay_percent=20
--pack_refresh_interval=3600
--table_delay=20
--hash_delay=20
```
Here's my conf file:
```
# cat /etc/osquery/osquery.conf
{
  "options": {
    "enroll_secret_path": "/var/osquery/enroll_secret",
    "tls_server_certs": "/var/osquery/server.pem",
    "tls_hostname": "fleet-prod.lendingcloud.us",
    "host_identifier": "hostname",
    "enroll_tls_endpoint": "/api/v1/osquery/enroll",
    "config_plugin": "tls",
    "config_tls_endpoint": "/api/v1/osquery/config",
    "config_tls_refresh": "10",
    "disable_distributed": "false",
    "distributed_plugin": "tls",
    "distributed_interval": "3",
    "distributed_tls_max_attempts": "3",
    "distributed_tls_read_endpoint": "/api/v1/osquery/distributed/read",
    "distributed_tls_write_endpoint": "/api/v1/osquery/distributed/write",
    "logger_plugin": "tls",
    "logger_tls_endpoint": "/api/v1/osquery/log",
    "logger_tls_period": "10"
  }
}
```
Config check comes back clean:
```
# osqueryi --config_path=/etc/osquery/osquery.conf --config_check --verbose
I0509 17:52:02.147713 29419 init.cpp:380] osquery initialized [version=2.11.2]
I0509 17:52:02.147781 29419 extensions.cpp:300] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0509 17:52:02.147811 29419 init.cpp:609] Cannot start extension manager: Extensions disabled
```
We're not using any custom extensions, so that failure for the extension manager seems normal. I thought this might be related to https://github.com/kolide/fleet/issues/1709, but I didn't see the ultimate resolution there and running the verbose & tls_dump flags on osqueryd didn't even give a functional workaround like the previous issue.

I'm happy to drop into the Slack channel if that's a more efficient way to troubleshoot. Again, my hunch is that I've screwed up the config somewhere rather than a core bug in Kolide. I just can't find it and have run out of logs & config parsing tricks to peek at things.

**Comment by groob** [comment]
--config_path /etc/osquery/osquery.conf

Don't set a config path if your config is coming from fleet. There can only be one config source.

**Comment by benjamin-hering** [comment]
Ah, ah, ah! I **DID** screw up the config! 

Okay, future me and anyone else running into this issue, both I and the person in https://github.com/kolide/fleet/issues/1709 got our heads turned around with using a local osquery.conf file together with kolide. With standalone osquery there's a bunch of stuff that can either be stored as a command line flag or in the config file with similar effect, but if you're using Kolide Fleet, slam it all into the command line flags. In following @groob's advice I dropped osquery.conf out entirely, and moved everything I was setting there into my flags file. My flag file now looks like:

```
# cat /etc/osquery/osquery.flags
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--disable_distributed=false
--disable_watchdog=false
--distributed_interval=3
--distributed_plugin=tls
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--enroll_secret_path=/var/osquery/enroll_secret
--enroll_tls_endpoint=/api/v1/osquery/enroll
--force=true
--hash_delay=20
--host_identifier=hostname
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
--pack_refresh_interval=3600
--schedule_splay_percent=20
--table_delay=20
--tls_hostname=fleet-prod.lendingcloud.us
--tls_server_certs=/var/osquery/server.pem
--watchdog_delay=120
--watchdog_level=1
```

With that, my test pack shows up in my verbose osqueryd logging.

```
    "Testing Pack": {
      "queries": {
        "Hosts File": {
          "query": "SELECT * FROM etc_hosts;",
          "interval": 30,
          "platform": "",
          "version": "",
          "snapshot": true
        }
```

And the results of the query showed up in my Kolide fleet results log. 

Thanks for the quick response @groob! Closing my issue as fixed.
