### ISSUE TITLE
Question: how to query osqueryd with table loaded via extension

### ISSUE THREAD

**Issue by KennethVanMele** [kolide/fleet#1789]
More a question and probably a stupid one, but is it possible to add a custom table to fleet?
I wrote a custom table via osquery-python and it works fine in osqueryi. I tried subscribing the extension to the socket used by fleet which I found by running `select value from osquery_flags where name = 'extensions_socket';` but it justs stops after a while. Will it help to run `python ./my_table_plugin.py --socket /Users/USERNAME/.osquery/shell.em` as a service? Feel free to ask what ever more information you need as I don't realy know what to add. I also posted this question on the osquery slack.

**Comment by marpaia** [comment]
I'm going to close this, as it's not a Fleet issue. I suggest the extension docs on the osquery wiki for more info on this topic: https://osquery.readthedocs.io/en/stable/deployment/extensions/. Feel free to ping us in #kolide or #extensions on the osquery slack if you want to talk about extensions.
