### ISSUE TITLE
fleet 2.0 does not allow editing packs in the GUI

### ISSUE THREAD

**Issue by groob** [kolide/fleet#1810]
Response is always `405 Method Not Allowed` unless I use fleetctl.

**Comment by Adrellias** [comment]
I am running into the same issue this side. There is also a problem with scheduling and getting queries to run.

You can take a look at a request for adding a new pack below.

[kolide.txt](https://github.com/kolide/fleet/files/2076705/kolide.txt)

**Comment by tokac** [comment]
I looked into the code and my assumption is that there is no API endpoint for making a POST on the /api/v1/kolide/packs. Take a look here [handler.go](https://github.com/kolide/fleet/blob/master/server/service/handler.go) and here [endpoint_packs.go](https://github.com/kolide/fleet/blob/master/server/service/endpoint_packs.go).

**Comment by blacksper** [comment]
I have the similar problem. I try to create new pack and response is 405 method not allowed. I think the problem is lack of post endpoits for some api queries. I think they was losed after this commit https://github.com/kolide/fleet/commit/0122f6cb0aec526d82b1745e81e92e1892c6bf47

**Comment by gjyoung1974** [comment]
Same, create new pack from UI or API (via import.go)
Request URL: https://localhost:8024/api/v1/kolide/packs
Request Method: POST
Status Code: 405 
Remote Address: [::1]:8024
Referrer Policy: no-referrer-when-downgrade
content-length: 0
date: Mon, 11 Jun 2018 02:36:41 GMT
status: 405
:authority: localhost:8024
:method: POST
:path: /api/v1/kolide/packs
:scheme: https
accept: application/json
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8
authorization: Bearer ey...Xc
content-length: 73
content-type: application/json
origin: https://localhost:8024
referer: https://localhost:8024/packs/new
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

**Comment by blacksper** [comment]
Thanks a lot!

**Comment by Adrellias** [comment]
Awesome! Thank you for fixing this so quickly :+1:

**Comment by zwass** [comment]
We'll be cutting an RC2 quite soon, but please feel free to build from `master` and test this.

**Comment by blacksper** [comment]
But. For now I catch another problem. When I try to edit query in pack and click to "Save" I get 500 error page.
Steps to reproduce:
1) Create query
2) Create pack "test"
3) Add query to pack and configure it
4) After that click to "manage packs", select the pack "test" and click to edit pack
5) Select query which you want to change and change interval (for instance)
6) Click to Save button and get 500 error page

**Comment by zwass** [comment]
@blacksper I can't repro this on master. Are you sure you are running master?

**Comment by blacksper** [comment]
@zwass , sorry, my bad, I install the previous fix from another brunch. With master brunch all ok
