### ISSUE TITLE
Redis repo no longer supported

### ISSUE THREAD

**Issue by csanders-git** [kolide/fleet#1820]
The Go library used for redis integration is no longer supported. Currently in use is [https://github.com/garyburd/redigo/](https://github.com/kolide/fleet/blob/c273a925379043918aa116ba9c638afc23fcf330/server/pubsub/redis_query_results.go#L9.). The specified repo is archived and suggests use of https://github.com/gomodule/redigo

### What version of `fleet` are you using (`fleet version --full`)?
Fleet 2.0rc1

### What operating system are you using?
Ubuntu

**Comment by zwass** [comment]
Thanks for the report @csanders-git. Fixed in #1821.

**Comment by csanders-git** [comment]
well shoot, quick turn around, thanks.

**Comment by zwass** [comment]
Ha, you caught me at a good time and it was an easy fix 😉
