### ISSUE TITLE
make deps fail with "/home/vagrant/fleet is not within a known GOPATH/src"

### ISSUE THREAD

**Issue by nirhenn** [kolide/fleet#1822]
Hi there,

I am trying to build fleet with no success and need some newbe help.
When i run make deps it fails with an error "/home/vagrant/fleet is not within a known GOPATH/src"
Any clue?

agrant@vagrant:~/fleet$ make deps
yarn
yarn install v1.7.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.72s.
go get -u \
	github.com/kolide/go-bindata/... \
	github.com/golang/dep/cmd/dep \
	github.com/groob/mockimpl
dep ensure -vendor-only
/home/vagrant/fleet is not within a known GOPATH/src
Makefile:162: recipe for target 'deps' failed
make: *** [deps] Error 1
vagrant@vagrant:~/fleet$ 
vagrant@vagrant:~/fleet$ 
vagrant@vagrant:~/fleet$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vagrant/go"
GORACE=""
GOROOT="/usr/lib/go-1.9"
GOTOOLDIR="/usr/lib/go-1.9/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build677059068=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
vagrant@vagrant:~/fleet$

**Comment by marpaia** [comment]
The Go toolchain requires the Fleet repo to be checked out to `$GOPATH/src/github.com/kolide/fleet`. If you're new to Go and are not familiar with `$GOPATH`, check out the repo to `$HOME/go/src/github.com/kolide/fleet`.
