### ISSUE TITLE
Panic with fleetctl query

### ISSUE THREAD

**Issue by rhuddleston** [kolide/fleet#1824]
### What version of `fleet` are you using (`fleet version --full`)?

2.0.0rc1

### What operating system are you using?

ubuntu 16.04 but running in alpine 3.7 docker container using the default binary compiled by kolide

### What did you do?

./fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'

### What did you expect to see?

some results as I see in the fleet UI

### What did you see instead?

$ ./fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'
⠋ panic: interface conversion: interface {} is nil, not *service.targetTotals

goroutine 1 [running]:
github.com/kolide/fleet/server/service.(*LiveQueryResultsHandler).Totals(...)
    /Users/marpaia/go/src/github.com/kolide/fleet/server/service/client_live_query.go:46
main.queryCommand.func1(0xc420248420, 0x0, 0x0)
    /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleetctl/query.go:112 +0xcbb
github.com/kolide/fleet/vendor/github.com/urfave/cli.HandleAction(0x150a0a0, 0xc4201e1080, 0xc420248420, 0xc4201f8500, 0x0)
    /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/kolide/fleet/vendor/github.com/urfave/cli.Command.Run(0x15c117a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15c8111, 0x10, 0x15cda73, ...)
    /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/urfave/cli/command.go:210 +0xa36
github.com/kolide/fleet/vendor/github.com/urfave/cli.(*App).Run(0xc4202044e0, 0xc4200c00f0, 0x5, 0x5, 0x0, 0x0)
    /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/urfave/cli/app.go:255 +0x6a0
github.com/kolide/fleet/vendor/github.com/urfave/cli.(*App).RunAndExitOnError(0xc4202044e0)
    /Users/marpaia/go/src/github.com/kolide/fleet/vendor/github.com/urfave/cli/app.go:276 +0x53
main.main()
    /Users/marpaia/go/src/github.com/kolide/fleet/cmd/fleetctl/fleetctl.go:53 +0x8ef

Also was seeing these errors on the fleet server logs:

{"err":"sending: sockjs: session not in open state","msg":"error writing to channel","ts":"2018-06-13T03:30:29.170054645Z"}

**Comment by thorduri** [comment]
Fixed in #1802 (not a part of RC1)

**Comment by zwass** [comment]
Closing this because we've already merged the fix.
