### ISSUE TITLE
Old pack targets are dropped when new targets are added

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#1827]
### What version of `fleet` are you using (`fleet version --full`)?
This issue goes back to at least Fleet 1.0.4

### What operating system are you using?
Any

### What did you do?
Edit a pack -> Add a target -> Save pack

### What did you expect to see?
Pack has existing targets and new target

### What did you see instead?
Pack only has new target

![edit pack](https://user-images.githubusercontent.com/575602/41423528-8cb2b8bc-6fc9-11e8-85d8-6ee2d6366c61.gif)

**Comment by kyleknighted** [comment]
Hey @zwass I took 30 minutes and dug into this a little bit. The problematic line is going to be https://github.com/kolide/fleet/blob/c273a925379043918aa116ba9c638afc23fcf330/frontend/kolide/entities/packs.js#L51

We need to better assess our use of the `deepDifference` function here and potentially find a better way to clean up the data before passing it to the API.
