### ISSUE TITLE
Ad-Hoc Queries Stalling Out After 5 minutes or so.

### ISSUE THREAD

**Issue by benjamin-hering** [kolide/fleet#1836]
### What version of `fleet` are you using (`fleet version --full`)?

```
{
version: "2.0.0-rc2",
branch: "master",
revision: "c4f2850e38a611a44189adf80e433bf38046e387",
go_version: "go1.10.2",
build_date: "2018-06-18T19:21:18Z",
build_user: "zwass"
}
```

### What operating system are you using?

Docker running on CentOs 7

### What did you do?

I executed a query from the GUI against "All hosts"

### What did you expect to see?

I expected to see results coming back from the ~3800 online hosts

### What did you see instead?

Results came back from hosts for about the first 5 minutes, and even after leaving the query to run for another 30 minutes no new additional hosts reported back.

Results after 5 minutes:

![screen shot 2018-06-18 at 1 49 56 pm](https://user-images.githubusercontent.com/7587027/41565545-125be69c-730c-11e8-9f63-f23133b8641d.png)

Results after 30 minutes:

![screen shot 2018-06-18 at 2 41 30 pm](https://user-images.githubusercontent.com/7587027/41565552-1a5883be-730c-11e8-86dd-9162f6be5367.png)

Current number is 3791 online hosts Screenshot of the home page showing that number:

![screen shot 2018-06-18 at 3 27 30 pm](https://user-images.githubusercontent.com/7587027/41565577-32a2b9f8-730c-11e8-863a-07ea48756e38.png)

Note the ~350 offline hosts are expected. My org uses a 'kill and fill' method, and the majority of those hosts are in fact legitimately killed.

I executed a similar query through fleetctl command line to see if there's a similar issue through that method. This time it gave me _more_ hosts than I actually have online.

```
time ./fleetctl query --query 'SELECT name, path, pid FROM processes WHERE on_disk = 0;' --labels='CentOS Linux' | tee results.json
....
⠒  171% responded (187% online) | 7069/4124 targeted hosts (7069/3777 online) {"host":"sjcbrwrsvc208-prod.tlcinternal.com","rows":[]}
⠲  171% responded (187% online) | 7070/4124 targeted hosts (7070/3777 online) {"host":"sjcadm202-prod.tlcinternal.com","rows":[]}
{"host":"","rows":[]}
⠦  171% responded (187% online) | 7071/4124 targeted hosts (7071/3777 online) ^C
real	10m14.030s
user	0m2.642s
sys	0m1.367s
```

**Comment by benjamin-hering** [comment]
And I re-ran the same query in the GUI after getting more than my total number of hosts back from fleetctl, now it as well shows more than my total online number of hosts.

![screen shot 2018-06-18 at 3 42 43 pm](https://user-images.githubusercontent.com/7587027/41566083-ad256f66-730e-11e8-9339-696b5f2d401f.png)

**Comment by benjamin-hering** [comment]
@zwass at the time, it appeared to be 20 or so. The systems seems to have stabilized now, so no more "incoming hosts" and the ad-hoc queries seem to have stabilized now as well. I can't reproduce the issue anymore. 

Perhaps I just hit a strange edge case with these "incoming hosts" throwing off the queries?

**Comment by zwass** [comment]
When hosts are stuck in that "Incoming Host" state, it means they successfully enrolled, but somehow aren't responding properly to distributed queries. So correlation makes a lot of sense but I don't think there's any implication of causation.

I'm going to close this issue for now, but please comment again if you continue having issues.
