### ISSUE TITLE
Cascade deletion of scheduled queries

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1837]
Cannot delete labels or queries

### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc2
  branch:       master
  revision:     c4f2850e38a611a44189adf80e433bf38046e387
  build date:   2018-06-18T19:21:18Z
  build user:   zwass
  go version:   go1.10.2
### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a

**Comment by rubenrodr-versia** [comment]
![image](https://user-images.githubusercontent.com/24841626/41595071-dc22fb32-73c5-11e8-8b4c-627f2a29064e.png)

![image](https://user-images.githubusercontent.com/24841626/41595100-f1c6a09c-73c5-11e8-87c1-64fd369b6e80.png)

**Comment by zwass** [comment]
This error is occurring because you have the query scheduled in a pack. You have to delete it from any packs before you can delete the query itself.

**Comment by AndersTao** [comment]
I am unable to delete queries as well, and still a problem after removing all packs

<img width="921" alt="screenshot 2018-06-20 at 04 30 18" src="https://user-images.githubusercontent.com/1774117/41634180-d6f1299a-7442-11e8-8773-1ac02684fe75.png">

**Comment by zwass** [comment]
Ah, I know what's going on. We used to have soft deletion which we are now migrating off of. The packs are being soft deleted so the foreign key constraint still fails.

I will fix this.

**Comment by rubenrodr-versia** [comment]
Hi,

I have updated to fleet rc3
>fleet - version 2.0.0-rc3
  branch:       master
  revision:     8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date:   2018-06-22T00:37:31Z
  build user:   marpaia
  go version:   go1.10.3

Now i can delete queries, but still cannot delete labels.

Thanks.
Best regards.

**Comment by zwass** [comment]
@rubenrodr-versia I see the issue you are referring to and I'm now tracking it in https://github.com/kolide/fleet/issues/1847.
