### ISSUE TITLE
Kolide fleet; I cant make a pack

### ISSUE THREAD

**Issue by aCruzQ** [kolide/fleet#1839]
![capture005](https://user-images.githubusercontent.com/20323736/41606422-f146a040-73e3-11e8-9730-27aa8a4fd30c.PNG)
Ubuntu 16.04 has a server
Windows 10 as a client

Kolide fleet run on last version.

Try to make a pack and I cant. I made many queries without problems but pack nothing.
The queries run without problem. This show me results.
Only try to save the pack, but this isnt save. 

![capture004](https://user-images.githubusercontent.com/20323736/41595819-741ba8ce-73c8-11e8-81b5-20be1ebdb100.PNG)

Only try to save the pack, but this isnt save.

**Comment by zwass** [comment]
If you open the network inspector, do you see an error when you try this? Please provide as much information about the error as possible.

**Comment by aCruzQ** [comment]
Hi Zwass. Thanks for help me.
Network inspector, I dont understand, sorry. Is a tool?, Is a command of linux?.

Regards.

**Comment by zwass** [comment]
Please see https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#requests

**Comment by aCruzQ** [comment]
Hi, I see this menssage in Crhome-devtoools: 

{
  "message": "Authentication Failed",
  "errors": [
    {
      "name": "base",
      "reason": "username or email and password do not match"
    }
  ]
}

This info too.

![capture009](https://user-images.githubusercontent.com/20323736/41723244-d6f8945e-756a-11e8-9542-0ad5ece3d7ab.PNG)

Add to this: I can make queries and other things on Kolide. My unique problems are the packs. My user is admin and is active.

**Comment by zwass** [comment]
The first error is indicating your authentication is invalid. Perhaps you cleared your cookies or restarted the Fleet server with a different jwt key?

The second error looks like the bug that we fixed in Fleet 2.0 RC2, so please upgrade.

I'm going to close this issue because I think we've fixed it in RC2, but please comment if you have further problems and we can reopen and discuss.

**Comment by aCruzQ** [comment]
Hi, continous with problems.
I try to update fleet but has problems. 
I used: 
https://github.com/kolide/fleet/blob/master/docs/infrastructure/updating-fleet.md

Donwload, Unzip, docker without problems, but when I try to running database migration, started the problems:

xxxx:~$ fleet prepare db
Error creating db connection: Errror 1045: Access denied dor user ´kolide´@´localhost´(using password: YES)
**- Tryted with this:**
xxxx:~$ fleet prepare db --mysql_address=127.0.0.1:3306 --mysql_database=kolide --mysql_username=man --mysql_password=passman
Migration alredy completed. Nothing to do.
xxxx:~$ Fleet version
fleet version 2.0.0-rc-1
xxxx:~$ Fleet serve
ts=2018-06-26T15:46:19.528168585Z mysql=could not connected to db: Error 1045: Access denied for user ´Kolide´@´localhost´ (using password: YES), sleeping 0s"
ts=2018-06-26T15:46:19.528529391Z mysql=could not connected to db: Error 1045: Access denied for user ´Kolide´@´localhost´ (using password: YES), sleeping 1s"
......
**- Tryted with this:**
xxxx:~$ sudo fleet serve db --mysql_address=127.0.0.1:3306 --mysql_database=kolide --mysql_username=man --mysql_password=passman
#######################################################################
# ERROR
#  A Value must be supplied for --auth_jwt_key. This value is used to create
# session tokens for users.
# 
# consider using the following randomly generated key:
# UZw6jdjujj4h5iJJ58878JKJlllios9sklr
########################################################################
xxxx:~$ Fleet version
fleet version 2.0.0-rc-1

Thanks for help me.

**Comment by aCruzQ** [comment]
I used the first and thirt links. I will read the second link to try understands how works kolide.
Thanks.

**Comment by aCruzQ** [comment]
Hi, I finally update the version. But continuous the problem.

I have fleet version 2.0.0-rc3.
I restarted the mysql too, and continuous equal.

The problem would be this?

xxxx:~$ prepare db
Error creating db connection: Error 1045: Access denied for user ´Kolide´@´localhost´ (using password: YES)´
try with this:
xxxx:~$ sudo prepare db (here pass parameter of db too; same error)
Error creating db connection: Error 1045: Access denied for user ´Kolide´@´localhost´ (using password: YES)´

Thanks.

**Comment by zwass** [comment]
Your database username/password combination is invalid.
