### ISSUE TITLE
fleetctl query error

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1840]
Running
>fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'

on the fleet server host i get the error:
>upgrade live query result websocket: websocket: bad handshake

### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc2
  branch:       master
  revision:     c4f2850e38a611a44189adf80e433bf38046e387
  build date:   2018-06-18T19:21:18Z
  build user:   zwass
  go version:   go1.10.2

### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a

### What did you do?
fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'

### What did you expect to see?
query results from all hosts

### What did you see instead?
upgrade live query result websocket: websocket: bad handshake

**Comment by rubenrodr-versia** [comment]
I have just tested on Ubuntu 18.04 and got the same error message:

>$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
$ ./fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'
upgrade live query result websocket: websocket: bad handshake

**Comment by zwass** [comment]
Is Fleet behind a load balancer that doesn’t support websockets?

**Comment by rubenrodr-versia** [comment]
Hi,

We have no load balancer, but the access to fleet server is done via firewall.
I have configured fleetctl on fleet server to point to localhost instead of his fqdn, so the communication is done locally, not through the firewall, and still getting the same error:

>fleetctl config set --address https://localhost
fleetctl query --query 'select * from osquery_info;' --labels='All Hosts'
upgrade live query result websocket: websocket: bad handshake

Our network team has revised the issue and tell us there should be no problem with websocket, and confirm that all type of ssl communication to 443 port is permited and fw is not dropping any packet.

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
Hi,

We have apache as reverse proxy, maybe is apache causing the issue ?

Thanks.
Best regards.

**Comment by rubenrodr-versia** [comment]
Hi,

I have tested configuring fleectl to point to https://localhost:8080
and fleetctl query is working fine:

>  fleetctl config set --address https://localhost:8080

So it's clear that this is an apache issue.
Any experience with apache as reverse proxy for fleet ?

Thanks.
Best regards.

**Comment by zwass** [comment]
I don't have any experience with apache as a revere proxy for Fleet. It does look like there are a number of resources online for configuring websocket proxying in Apache.

**Comment by rubenrodr-versia** [comment]
Hi

Hope this helps anyone using apache in front of fleet.
We have been able to configure apache to proxypass websockets with the following config:
```
SSLProxyEngine on
SSLProxyCheckPeerCN Off

#ProxyPass / https://127.0.0.1:8080/
#ProxyPassReverse / https://127.0.0.1:8080/

  RewriteEngine On
  RewriteCond %{HTTP:Upgrade} =websocket [NC]
  RewriteRule /(.*)           wss://127.0.0.1:8080/$1 [P,L]
  RewriteCond %{HTTP:Upgrade} !=websocket [NC]
  RewriteRule /(.*)           https://127.0.0.1:8080/$1 [P,L]

  ProxyPassReverse / https://127.0.0.1:8080/
```

Now fleetctl query is working fine through apache.

Thanks.
Best regards.

**Comment by aCruzQ** [comment]
Hi rubenrodr-versia.
Thanks for your contribution to https://github.com/kolide/fleet/issues/1840#issuecomment-402385841. One question related to this. I have one public IP: x.x.x.x as kolide server using a public certificate, all host are connected to kolide by internet. But I have the problem that I cant run queries/pack from API of kolide; I have the same kinds of error of this post. In relation with your solution; could use it with my public IP too? and whats is the exactly file that you edited?.

Thanks for your answer.
Kid regards.

**Comment by zwass** [comment]
@aCruzQ are you able to run queries through the UI or `fleetctl`? These both use the standard API.

**Comment by aCruzQ** [comment]
Hi Zwass, I run queries and packs by UI without problems. But when I tried to run any query using the API fleetctl the result is this message:  
_**"upgrade live query result websocket: x509: certificate signed by unknow authority".**_ 
The Kolide server run under Centos 7.  Version 2.0.2
![image](https://user-images.githubusercontent.com/20323736/61691239-674fe900-ad2b-11e9-8c38-59fdd84cfb4c.png)

Kind regards.

**Comment by aCruzQ** [comment]
Anyone, reply, please.

Kind regards.

**Comment by rubenrodr-versia** [comment]
Hi aCruzQ,

The specified config is apache config file for the corresponding virtual host.
