### ISSUE TITLE
Updating fleet causes pack CRUD errors in the UI

### ISSUE THREAD

**Issue by find-mikeli** [kolide/fleet#1845]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc1
  branch: 	master
  revision: 	a172540b7bc6a11ca261749040c9585eba370cdd
  build date: 	2018-05-23T19:27:13Z
  build user: 	marpaia
  go version: 	go1.10.2
### What operating system are you using?
CentOS Linux release 7.5.1804 (Core) 
### What did you do?
Upgraded from fleet version 1.0.7-1-g2ded63e and ran `fleet db prepare`. Once completed i went into the Fleet UI and tried to manage my Packs. I can view them but cannot do CRUD on any of the packs (create, enable, edit, delete). 
### What did you expect to see?
I expect the ability to manage packs. 
### What did you see instead?
error messages saying something went wrong. 
{“component":"service","err":"packs 3 was not found in the datastore","method":"DeletePack","took":"627.342µs","ts":"2018-06-21T22:48:46.751689647Z”}

**Comment by marpaia** [comment]
Hey @find-mikeli, this should be fixed in the latest release candidate. Can you upgrade to 2.0.0-rc3 and try?
