### ISSUE TITLE
pkgbuild command not found when create MAC client package

### ISSUE THREAD

**Issue by gnomefish** [kolide/fleet#1859]
### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 2.0.0-rc3
  branch: 	master
  revision: 	8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date: 	2018-06-22T00:37:31Z
  build user: 	marpaia
  go version: 	go1.10.3

### What operating system are you using?

Ubuntu 16.04

### What did you do?

Trying to make a package for MACOS client, just followed instructions and added the host, enroll secret and certificate to the config.mk file

### What did you expect to see?

My package, but I keep getting the PKGBUILD error "Command not found"

### What did you see instead?

root@OSQUERY:/opt/kolide/tools/mac# make
rm -rf out/
rm -rf root/etc/osquery
mkdir -p out
mkdir -p root/etc/osquery
echo *READACTED* > root/etc/osquery/kolide_secret
echo "$KOLIDE_TLS_CERTIFICATE" > root/etc/osquery/kolide.crt
# validate the certificate
openssl x509 -in root/etc/osquery/kolide.crt -text > /dev/null
echo "$KOLIDE_FLAGS" > root/etc/osquery/kolide.flags
pkgbuild --root root --scripts scripts --identifier co.kolide.osquery.enroll --version 1.0.0 out/kolide-enroll-1.0.0.pkg
make: pkgbuild: Command not found
Makefile:17: recipe for target 'build' failed
make: *** [build] Error 127

**Comment by groob** [comment]
`pkgbuild` is a mac specific utility.

**Comment by gnomefish** [comment]
oh... duh... yes ofcourse makes sens as I'm building a MAC package, should be done on MAC... *blush* than you groob!
