### ISSUE TITLE
how to write kolide/fleet packs running output into kafka???

### ISSUE THREAD

**Issue by binups** [kolide/fleet#1861]
### What operating system are you using?
     Ubuntu 16.04 
### What did you expect to see?
                   i need kolide/fleet need to read osquery from /etc/osquery/osquery.conf  and execute and write it in kafka 
config i used 
sudo /usr/bin/osqueryd   --enroll_secret_path=/var/osquery/enroll_secret   --tls_server_certs=/home/binu/install/8080.pem   --tls_hostname=localhost:8080   --host_identifier=hostname   --enroll_tls_endpoint=/api/v1/osquery/enroll   --config_plugin=tls   --config_tls_endpoint=/api/v1/osquery/config   --config_tls_refresh=10   --disable_distributed=false   --distributed_plugin=tls   --distributed_interval=3   --distributed_tls_max_attempts=3   --distributed_tls_read_endpoint=/api/v1/osquery/distributed/read   --distributed_tls_write_endpoint=/api/v1/osquery/distributed/write   --logger_plugin=tls,kafka_producer   --logger_tls_endpoint=/api/v1/osquery/log   --logger_tls_period=10   --logger_kafka_brokers="-----------:9091"   --logger_kafka_topic="demo-osqueryd"   --logger_kafka_compression="none"   --logger_kafka_acks="all" 

but its not reading from

**Comment by zwass** [comment]
If you want the osquery nodes to write to Kafka, you need to set up Fleet to provide them the appropriate configuration.

If you want Fleet to collect the logs and then push to Kafka from the Fleet server, you'll need some forwarding agent on the Fleet server.
