### ISSUE TITLE
The best way to connect Kolide with Logrhythm

### ISSUE THREAD

**Issue by aCruzQ** [kolide/fleet#1864]
Hi, I run kolide on 5 devices (4 windows + 1 linux). I need now use the log of fleet (/tmp/; by the moment) to read it and analyze with LoghRhythm. How is the best way to make it?

### What version of `fleet` are you using (`fleet version --full`)?
Version 2.0.0.-rc3

### What operating system are you using?
Ubuntu 16.04

### What did you do?
Nothing until today

### What did you expect to see?
Work with log on LogRhythm

**Comment by zwass** [comment]
Fleet just writes logs to a standard text file on the Fleet server. You'll need to set up any additional log handling on your own. I suggest the LogRhythm docs.

**Comment by aCruzQ** [comment]
Ok. Thanks. I will read more information on LogRhythm.
