### ISSUE TITLE
Unable to save settings with no SMTP server

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#1871]
:wave: While trying to set up Fleet I was trying to configure SSO before SMTP (while I waiting for someone to get back to me on what to use for SMTP) and I was unable to save the settings page without a valid SMTP server. It's pretty annoying that I can't save the form in any partially complete setup.

### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 1.0.8
  branch: 	changelog_1.0.8
  revision: 	eb85e71181c90082808107ecabf655bcea94a117
  build date: 	2018-05-04T00:06:50Z
  build user: 	zwass
  go version: 	go1.9.2

### What operating system are you using?
Using the `kolide/fleet:1.0.8` docker image in k8s.

### What did you do?
Attempted to save settings without an SMTP server configured

### What did you expect to see?
Settings would save

### What did you see instead?
Form validation errors insisting I enter an SMTP server.

**Comment by devx** [comment]
I would also love to see this behave as an option.
