### ISSUE TITLE
 FAIL 20171219164727_UpdateScheduledQueryKey.go (adding not null: Error 1138: Invalid use of NULL value), quitting migration

### ISSUE THREAD

**Issue by bali007861** [kolide/fleet#1872]
### What version of `fleet` are you using (`fleet version --full`)?
version 1.0.6 
Trying to upgrade to fleet version 2.0.0-rc3
### What operating system are you using?
Red Hat Enterprise Linux Server release 6.7 
### What did you do?
Trying to upgrade to fleet version 2.0.0-rc3 and running fleet prepare db. 
### What did you expect to see?
DB should migrate to new version but I get an error
### What did you see instead?
FAIL 20171219164727_UpdateScheduledQueryKey.go (adding not null: Error 1138: Invalid use of NULL value), quitting migration.

**Comment by zwass** [comment]
I believe this was fixed in #1851. Are you able to build from master and try again?

**Comment by bali007861** [comment]
Any workaround to fix this issue? Also, if I don't use prepare db and just start fleet server, what would happen? Will i need reconfigure all my packs?

**Comment by zwass** [comment]
Please reach out to me directly on Slack and we’ll work through this. I’m
@zwass and will have availability during PST working hours this week.

**Comment by zwass** [comment]
We followed up on Slack and it looks like the patch did resolve the issue. Thanks!

**Comment by rubenrodr-versia** [comment]
Hi,

I have the same issue migrating from 1.0.8 to 2.0.0-rc4 running on Centos 7.5 with mysql  5.7.23
```
# ./fleet prepare db --config /etc/kolide/kolide.yml
Using config file:  /etc/kolide/kolide.yml
################################################################################
# WARNING:
#   This will perform Fleet database migrations. Please back up your data before
#   continuing.
#
#   Press Enter to continue, or Control-c to exit.
################################################################################

2018/08/17 10:06:40 FAIL 20171219164727_UpdateScheduledQueryKey.go (adding query_name column: Error 1060: Duplicate column name 'query_name'), quitting migration.
```

Thanks.

**Comment by zwass** [comment]
@rubenrodr-versia did you first see the error that is referenced in the original issue description?

```
FAIL 20171219164727_UpdateScheduledQueryKey.go (adding not null: Error 1138: Invalid use of NULL value), quitting migration.
```

I'd like to understand how you got into this state.

We've had luck with folks opening their MySQL DB and running `alter table scheduled_queries drop column query_name;` as a workaround, but I'd really like to understand the root cause better.

**Comment by rubenrodr-versia** [comment]
Hi,

I think the first error was not displayed.
This is a vm for internal use, so i can make an snapshot and try to diagnose the issue.
I can send you a database dump via slack if you need it.

Thanks.
Best regards.

**Comment by clong** [comment]
@zwass can you guys add logic to the DB migration such that it effectively runs `alter table scheduled_queries drop column query_name;` if that column exists when it shouldn't? This has happened on multiple 1.0.8 installs, so there must be some normal way that 1.0.8 installs get into this state
