### ISSUE TITLE
Create a k8s helm chart

### ISSUE THREAD

**Issue by gjyoung1974** [kolide/fleet#1873]
### What version of `fleet` are you using (`fleet version --full`)?
2.0.0-rc2

### What operating system are you using?
Linux Ubuntu

### What did you do?
Created a k8s helm chart to deploy the stack
https://github.com/gjyoung1974/kolide-fleet-chart

### What did you expect to see?
This is a request to include a k8s helm chart

### What did you see instead?
Please consider distributing a k8s helm chart like the following:
https://github.com/gjyoung1974/kolide-fleet-chart

**Comment by zwass** [comment]
@gjyoung1974 Maybe you'd like to add your repo to https://github.com/kolide/fleet#community-projects? I'd be happy to merge a PR for that.

I'm reluctant to add it into the repo as we would then become responsible for supporting it (and we don't use helm).

**Comment by gjyoung1974** [comment]
Perfect! I'll add it there thanks @zwass !
~G
