### ISSUE TITLE
Add k8s Helm chart to Community projects listing

### ISSUE THREAD

**Issue by gjyoung1974** [kolide/fleet#1874]
### What version of `fleet` are you using (`fleet version --full`)?
latest

### What operating system are you using?
Linux

### What did you do?
create a Kubernetes helm chart
https://github.com/gjyoung1974/kolide-fleet-chart

### What did you expect to see?
Would like to request to add it to the community projects listing 
https://github.com/kolide/fleet#community-projects

### What did you see instead?
N/A project is designed for Docker. Would be cool to see a helm chart for those using k8s or GKE.

Thanks in advance!
~Gordon

**Comment by gjyoung1974** [comment]
@zwass Thank you for your suggestion to list my Repo under community projects!  Would love to see it there and potentially have any interested folks collaborate with me. 
Best!
~G

**Comment by zwass** [comment]
@gjyoung1974 Did you delete the repo or make it private? The link 404s for me now.

Happy to add it to the Community Projects listing once that is resolved.

**Comment by gjyoung1974** [comment]
@zwass my mistake I made it private. I will update it today,
Thank you for offering to add it to community projects for me!

**Comment by gjyoung1974** [comment]
@zwass Done!
https://github.com/gjyoung1974/kolide-fleet-chart
Thank you again!
