### ISSUE TITLE
Import query packs via gui

### ISSUE THREAD

**Issue by gnomefish** [kolide/fleet#1880]
Hi there,
Sorry for the noon question but is it possible to import query packs into the gui of fleet? Couldn’t find any option to import existing packs.
May thanks and keep up the good work.
L.

**Comment by zwass** [comment]
The best way to import packs currently is to use the `fleetctl convert` command. This will output yaml which you can then `fleetctl apply` to get into your Fleet instance.

There are no plans to build a GUI import tool.

**Comment by gnomefish** [comment]
Hi Z.
Ok thanks for the quick response :) 
L.
