### ISSUE TITLE
Got unexpected content-type \"text/html; charset=utf-8\" while enrolling

### ISSUE THREAD

**Issue by johnkeates** [kolide/fleet#1881]
### What version of `fleet` are you using (`fleet version --full`)?
1.0.8
### What operating system are you using?
macOS 10.13.6
### What did you do?
Install fleet containers on AWS ECS behind an ALB behind CloudFlare
### What did you expect to see?
Launcher connect to fleet and enrolling nodes
### What did you see instead?
```
{"caller":"main.go:358","component":"launcher","enrolling host: transport error in enrollment: rpc error: code = Internal desc = transport: received the unexpected content-type \"text/html; charset=utf-8\"":"(MISSING)","level":"info","ts":"2018-07-27T23:04:17.490513987Z"}
```

It seems to do rpc over the same port and not expect text/html. The UI works fine.

**Comment by zwass** [comment]
Launcher communicates with Fleet via gRPC which uses HTTP2 and is not supported by ALB. You'll have to use a TCP load balancer to for compatibility.

**Comment by johnkeates** [comment]
Excellent to know, I'll use an NLB instead and have CloudFlare's HTTP2 do SSL and offloading.

**Comment by zwass** [comment]
That should work! We're also happy to talk about this stuff in #kolide in osquery Slack.

**Comment by johnkeates** [comment]
I did ask there before opening a ticket here ;-) https://osquery.slack.com/archives/C1XCLA5DZ/p1532735495000107

**Comment by johnkeates** [comment]
An update: CloudFlare doesn't run HTTP/2 towards the origin, only between the browser/client and CloudFlare ingress.

**Comment by Oneiroi** [comment]
For future users reference, if you are fronting fleet with nginx you'll encounter the same issue see https://www.nginx.com/blog/http2-module-nginx/ -> `At the moment, we only support HTTP/2 on the client side. You can’t configure HTTP/2 with proxy_pass. `

**Comment by johnkeates** [comment]
Seems to be a broader issue indeed, most proxies, balancers and relays have trouble with upstream H2.

**Comment by tkennym** [comment]
> For future users reference, if you are fronting fleet with nginx you'll encounter the same issue see https://www.nginx.com/blog/http2-module-nginx/ -> `At the moment, we only support HTTP/2 on the client side. You can’t configure HTTP/2 with proxy_pass. `

Hi @Oneiroi , so i'm having the same issue even with launcher version 5 : unexpected content-type. Howver, enrolling directly with `osqueryd --enroll_secret_path=<path> --tls_server_certs=<path to certs> --tls_hostname=<hostname> --host_identifier=hostname` etc, works fine. Both via `launcher` and via `osqueryd` directly connect to the same host and one works while the other doesn't. It's running Nginx. Is there a solution to this?

**Comment by zwass** [comment]
@minamonk This is likely because Launcher uses the gRPC transport, while osqueryd is using plain HTTPS.
