### ISSUE TITLE
window_events query not working

### ISSUE THREAD

**Issue by gnomefish** [kolide/fleet#1882]
### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 2.0.0-rc3
  branch: 	master
  revision: 	8b7edf759db2911030a660aa85cf82615f0f5f4b
  build date: 	2018-06-22T00:37:31Z
  build user: 	marpaia
  go version: 	go1.10.3

### What operating system are you using?

Ubuntu 16.04

### What did you do?

trying to write a query that checks windows event logs

### What did you expect to see?

SELECT * FROM windows_events where eventid = 4672;

### What did you see instead?

windows_events does not appear in the autocomplete menu, and when saving and running the query nothing happens

**Comment by gnomefish** [comment]
Some extra info : my osquery.flags file has these:

--disable_logging=false
--windows_event_channels=System,Application,Setup,Security
--disable_events=false
--events_max=50000

and when I do osqueryi —verbose--nodisable_events --windows_event_channels="System,Application,Setup,Security” --logger_plugin=filesystem --events_max=50000

SELECT * FROM windows_events where eventid = 4672 limit 3;

it does work:

osquery> select time, eventid, source, data from windows_events where eventid = 4658 limit 1;
   time = 1532874114
eventid = 4658
 source = Security
   data = {"EventData":{"HandleId":"0x287c","ObjectServer":"Security","ProcessId":"0x1550","ProcessName":"C:\\SysinternalsSuite\\procexp64.exe","SubjectDomainName":"ACME","SubjectLogonId":"0x60e09","SubjectUserName":"John","SubjectUserSid":"S-1-5-21-1143857549-1447411070-2460191317-1108"}}

**Comment by gnomefish** [comment]
so after some troubleshooting, this is what was missing on the osquery side : --logger_event_type=true

It's not really documented very well, but having this flag on the osqueryd made things work. In fleet the autofill still doesn't recognize windows_events - but you cqn just type the query and it does run

**Comment by zwass** [comment]
Glad you got this sorted. I am tracking the need to update autocompletion values in #1883.

**Comment by gnomefish** [comment]
cool stuff 👍
