### ISSUE TITLE
SAML - IdP certificate fails to read correctly

### ISSUE THREAD

**Issue by chelming** [kolide/fleet#1892]
### Background info
Our IdP's metadata is formatted like so:
```XML
<ds:X509Certificate>
MIIDVDCCAjygAwIBAgIVAMPFek+px9vIGJ0/+QhwyptEXQqaMA0GCSqGSIb3DQEB 
BQUAMCUxIzAhBgNVBAMTGnNoaWJib2xldGgubWFpbi5hZC5yaXQuZWR1MB4XDTA4 
MTEyNTE4MzU0N1oXDTI4MTEyNTE4MzU0N1owJTEjMCEGA1UEAxMac2hpYmJvbGV0 
aC5tYWluLmFkLnJpdC5lZHUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB 
AQC3LLiBrUjXO+LFsfrk4u5lQ62FfXJEPJnmL6/4WVsOtpLWMQZesuiOlyhFTsTN 
dlmFp37UTcZ9MJsTeG/1M87BxUnPB22Qn7TPNLh7Oi3QDinVyukPXRl6B/bHdtMh 
lq5V+E8rNyITaOc7YB6GkNLBOVBRemBcttmlwz5whHWwU/MNdQlBf4/KIu7mV5dp 
WQrnPvaTk3nle4vOtbPThipD5jiD2r/a4/l5gROJRuLvxQaiNfBfACwowp9R9DHK 
lpqD4EPSEv2v0RXJyFx4pMi/hnfmSjvIQi9s+J5sKzyNN3JtCzrVO5GSiddO46bR 
tvp5H/rz0cNpp5rnjz+NRkarAgMBAAGjezB5MFgGA1UdEQRRME+CGnNoaWJib2xl 
dGgubWFpbi5hZC5yaXQuZWR1hjFodHRwczovL3NoaWJib2xldGgubWFpbi5hZC5y 
aXQuZWR1L2lkcC9zaGliYm9sZXRoMB0GA1UdDgQWBBRJRQ19Vjpa3qktIoVtEqdL 
onWQFTANBgkqhkiG9w0BAQUFAAOCAQEAmXDiVgm0fmvvhtzYO2GFBIpZNNzd+8ou 
jnUNTKNAliKToarQvLDTQUENh2L558u3OvwFXlC7hcnGNKin4VjQ/GWps+J7dQ67 
gCiYMquyf5i9UE/j5ilriNXmSwzwvB/YPJzEMIFd2XBI550ODeIMf5B0gGx1EMB1 
jyWpy4iOZbMCBbGn0Vo2/AeGyiUmT6/qcDnrMTg4fvAqG26kujwPBb42UpkwSo2E 
OZDp3OGGicpNhWVWca74r8KHYJGNBwXYmZ5ntP5Yfd9cElJKFLS21igLGkhr/o4N 
Im4Q86WvRXW4cHfy8OB9fEIURxSmGeZMYsd0YLh8ouPlWuLl3hWsyQ==
</ds:X509Certificate>
```
which, when viewed in a browser looks something like this:
![image](https://user-images.githubusercontent.com/7746625/43801492-410a0b82-9a61-11e8-9440-b2d4f6091fc2.png)

full link to metadata: https://shibboleth.main.ad.rit.edu/rit-metadata.xml

### What version of `fleet` are you using (`fleet version --full`)?
```
fleet - version 2.0.0-rc3-10-g6bdddfa
  branch: 	master
  revision: 	6bdddfacf0c68314ec242a22205ad1982802a583
  build date: 	2018-07-23T13:04:03Z
  build user: 	root
  go version: 	go1.9.4
```

### What operating system are you using?
RHEL 7

### What did you do?
Point fleet to the IdP's metadata using the URL or by copy/pasting the metadata from the XML

### What did you expect to see?
Error-free logs

### What did you see instead?
```
{"component":"service","err":"creating validator from metadata: decoding idp x509 cert: illegal base64 data at input byte 1164","method":"CallbackSSO","took":"652.814µs","ts":"2018-08-07T20:23:45.861159546Z"}
```

### But...
If I copy/paste the metadata into fleet and then delete all the line breaks _only_ within the `X509Certificate` tag, it starts working

**Comment by zwass** [comment]
If I understand correctly, you were able to find a workaround for this by manually editing the metadata?

I think the problem is not actually the newlines (which are ignored by Go's base64 decoder), but the spaces at the end of each line. If you can show me that this is valid according to the SAML spec we will mark it as a bug. Otherwise I'm not inclined to special case any parsing unless this becomes a common issue for folks.

**Comment by chelming** [comment]
>If I understand correctly, you were able to find a workaround for this by manually editing the metadata?

Correct.

>I think the problem is not actually the newlines (which are ignored by Go's base64 decoder), but the spaces at the end of each line.

If I `curl -O https://shibboleth.main.ad.rit.edu/rit-metadata.xml` and view it there aren't actually any spaces at the end of the lines. Just line breaks. I think it was just my github formatting.

![image](https://user-images.githubusercontent.com/7746625/43806858-c01fe754-9a73-11e8-9ee6-3928c7e8ff2c.png)

**Comment by chelming** [comment]
Any idea how I can check what character it's failing on? Specifically `illegal base64 data at input byte 1164` I guess?

**Comment by chelming** [comment]
oh, any idea if Go's base64 decoder ignores tabs? It looks like char 1164 might be the tabs before the X509Certificate tag closes.

**Comment by zwass** [comment]
@cwhits That sounds like a very likely culprit. The base64 decoder definitely ignores newlines (https://golang.org/src/encoding/base64/base64.go?s=11527:11590#L303) but I don't think it has any special handling for tabs.
