### ISSUE TITLE
fleet returning results one by one instead of fetching all available results at the same time

### ISSUE THREAD

**Issue by cantorek** [kolide/fleet#1895]
Following discussion on slack with @zwass 

After executing a query (UI and fleetctl) I'm seeing results returned one by one instead of all at the same time.
While examining redis instance I can see that all my osquery clients already responded to the query, but fleet is fetching them gradually instead of fetching all available results from redis.
Also, this is clearly visible when looking at current results number, I'm getting 1-3 results per second.
I would expect to get all available results from redis.
Since picture is worth a thousand words I've attached screenshot showing redis memory usage after running the query via fleetctl.
Clearly visible spike represents a moment when results are returned from osquery agents, next we can observe that fleet is slowly fetching results - one by one.
Unfortunately with the number of hosts we're planning to use fleet with - this will not scale.

![redis](https://user-images.githubusercontent.com/5817943/43843045-ef1c497c-9b26-11e8-8762-ea22715e42bc.png)

When looking at MySQL's `distributed_query_executions` table I can confirm the same - results from osquery daemons are available almost instantly, while fleet UI and fleetctl is returning them one by one.

This is regardless of using websockets or not.

### What version of `fleet` are you using (`fleet version --full`)?
`2.0.0-rc3`

### What operating system are you using?
linux

### What did you do?
ran a query

### What did you expect to see?
All available results returned at the same time

### What did you see instead?
Results are returned one by one

**Comment by cantorek** [comment]
Hey @zwass ,

If you need me to run more tests or gather some data let me know. I'm happy to do all it takes to get this solved! :-)

**Comment by zwass** [comment]
Am I reading this graph correctly that it took something like 20 minutes to retrieve all of the results? What is the `distributed_interval` you are using on these hosts? And how many hosts are we looking at here?

We should expect to see the results from each host come in at the same time (therefore "1 by 1"), but when the host reports their results to Fleet there should be very minimal delay before those results make it to the UI or `fleetctl` client.

**Comment by cantorek** [comment]
Hello and thanks for the reply.

Yes, you are reading the graph correctly. We are talking about 5k online
hosts. Around 8k in total.

We use default value for Distributed_interval which is 10 I believe.


śr., 15 sie 2018, 20:58 użytkownik Zachary Wasserman <
notifications@github.com> napisał:

**Comment by cantorek** [comment]
Hey guys, @zwass

Any traction on this?

Can you let me know if fixing this is somehow on your roadmap?
Is there anything I can do more to help?

**Comment by latundetoks** [comment]
@cantorek im curious to know the visualization you're using for redis.

**Comment by fireydagostino** [comment]
Hi there,

Has there been further in-house discussion regarding this?

I would also like to know if receiving results from a query-pack into Fleet on a per-server basis is the desired outcome versus receiving the results all at once (or as they are returned) is something that will be looked into in the future.

Thanks

**Comment by zwass** [comment]
I have discovered the cause for this and will be pushing up a fix shortly. @cantorek I apologize for the delay as I haven't had the time to prioritize it, but I'd love to work with you to resolve the issue.

**Comment by cantorek** [comment]
Wow. Amazing. This is a game changer for us! Please keep me posted and let
me know what I can do to help! :-)

pt., 7 gru 2018, 22:44: Zachary Wasserman <notifications@github.com>
napisał(a):

**Comment by zwass** [comment]
@cantorek are you able to build from my branch? The fix is pushed up to https://github.com/kolide/fleet/pull/1965. Will be very curious if this fixes your issue.

**Comment by zwass** [comment]
@cantorek have you had a chance to test out the fix? I will likely merge it anyway, but I would really like to know if it fixes your problem.

**Comment by cantorek** [comment]
Apologies @zwass ,

It might take a while since I'm no longer working with fleet in my projects, but I've asked my colleague to look into it. I'll keep you posted! :-)

We normally use provided docker image, so building from source and deploying to our env will take some time.
