### ISSUE TITLE
Problem with migrations from 1.0.8 to 2.0.0-rc4

### ISSUE THREAD

**Issue by m6a-UdS** [kolide/fleet#1910]
### What version of `fleet` are you using (`fleet version --full`)?
1.0.8, pulled from Dockerhub

### What operating system are you using?
Fleet's base image (Alpine)

### What did you do?
Upgraded to 2.0.0-rc4 (pulled from dockerhub)

### What did you expect to see?
The `Migrations completed` message

### What did you see instead?
```
FAIL 20171116163618_CreateTableOsqueryOptions.go (Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'JSON NOT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8' at line 1), quitting migration.
```

### More details
Database: AWS RDS MySQL 5.6.27

**Comment by zwass** [comment]
Can you please try with MySQL 5.7? We always recommend folks use 5.7, but I now realize this is not explicit in the docs. I'll update them to make it more clear.

**Comment by zwass** [comment]
Updated in #1919. Please comment and we can reopen this issue if you have trouble with MySQL 5.7.

**Comment by m6a-UdS** [comment]
Thanks, I will!
