### ISSUE TITLE
deleting a user from fleet causing NULL errors on db queries. 

### ISSUE THREAD

**Issue by groob** [kolide/fleet#1911]
Followup from https://osquery.slack.com/archives/C1XCLA5DZ/p1535398700000100

It appears that after a user is deleted, `author_id` on list queries returns as NULL, causing this error message:

```
listing queries: sql: Scan error on column index 9: converting driver.Value type <nil> ("<nil>") to a uint: invalid syntax
```
From slack:
> …. The only nulls I see are in `deleted_at`,`author_id`, `author_name` - every row in these columns are null

**Comment by zwass** [comment]
Is there any more background for how a user was deleted? The UI only allows disabling a user (am I missing something?), and foreign key constraints should prevent a user from being deleted even directly via MySQL if they have created any queries.

We can add a fallback on this query that will return an empty string, but I'd really like to understand how we got here.

**Comment by defensivedepth** [comment]
@zwass I can't replicate this. I can confirm that a number of my queries in the database had `null` for author_id. Once I replaced these `nulls`  with the correct author_id, the UI stopped throwing the error.

I don't know how the data got into that state to begin with.

**Comment by zwass** [comment]
I'm not sure that this can be reproduced without manually deleting users in the database... Nevertheless, I put up a fix for it.
