### ISSUE TITLE
Logging json disabled not working

### ISSUE THREAD

**Issue by g3l0l4** [kolide/fleet#1913]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc4
  branch:       master
  revision:     71e8e3917eb77058721c9f7ad6e4d3e3704717a2
  build date:   2018-08-14T23:56:00Z
  build user:   zwass
  go version:   go1.10.2
### What operating system are you using?
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a
### What did you do?
I disabled json logging.
```
logging:
  json: false
  disable_banner: true
```
### What did you expect to see?
I expected log files not in json, I expected plain text.
### What did you see instead?
I see json logs.

**Comment by zwass** [comment]
The `--logging_json` flag effects the server log output, not the osquery log output (which is written by Fleet exactly as it is received.

```
$ ./build/fleet serve --auth_jwt_key=foobar --logging_json=true
{"component":"service","err":null,"method":"ListUsers","took":"3.227676ms","ts":"2018-09-07T17:47:56.669339589Z","user":"none"}
{"address":"0.0.0.0:8080","msg":"listening","transport":"https","ts":"2018-09-07T17:47:56.669883311Z"}
^C{"terminated":null,"ts":"2018-09-07T17:47:58.069178343Z"}
$ ./build/fleet serve --auth_jwt_key=foobar --logging_json=false
ts=2018-09-07T17:48:00.073079952Z component=service method=ListUsers user=none err=null took=4.220553ms
ts=2018-09-07T17:48:00.074418514Z transport=https address=0.0.0.0:8080 msg=listening
^Cts=2018-09-07T17:48:01.164868862Z terminated=null
```
