### ISSUE TITLE
logger_mode not being observed in 2.0.0-rc4

### ISSUE THREAD

**Issue by benbasscom** [kolide/fleet#1920]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc4
  branch: 	master
  revision: 	71e8e3917eb77058721c9f7ad6e4d3e3704717a2
  build date: 	2018-08-14T23:56:00Z
  build user: 	zwass
  go version: 	go1.10.2
### What operating system are you using?
RHEL Linux 7.5

### What did you do?
create an options.yaml and set the "logger_mode" to 420.

### What did you expect to see?
-rw-r--r-- permissions on the /var/log/osquery/osqueryd.results.log

### What did you see instead?
-rw-r-----  permissions on /var/log/osquery/osqueryd.results.log

If I chmod 644 the file, I get -rw-r--r--, and restarting osquery will reset the permissions to 
-rw-r-----, indicating that the permissions are being set by the osquery process.

If I enroll in a fleet server running 1.0.8, with the logger_mode set to 420, the correct permissions are set.

**Comment by benbasscom** [comment]
Here is the options.yaml.  Converted to text to attach.

[options.yaml.txt](https://github.com/kolide/fleet/files/2368470/options.yaml.txt)

**Comment by zwass** [comment]
@benbasscom did you find this differing behavior between 1.0.8 and RC4 when you used osqueryd on the same system? I'd like to try to ensure we aren't being thrown off by umask differences.

**Comment by zwass** [comment]
Can you run `osqueryd` with `--verbose --tls_dump` and see what the difference is in the config file it retrieves from the different server versions?

**Comment by benbasscom** [comment]
Will do.  I’ll have access to the box in the morning.

**Comment by benbasscom** [comment]
It seems that there are a bunch of things that aren't making it to the end point with 2.0.0-rc4.

I have trimmed out the packs& queries and obfuscated the urls, but it looks like the configs being sent to the end points is misconfigured/truncated.  

Both samples are running on the same mac endpoint with osquery 3.3.0.

[1.0.8.txt](https://github.com/kolide/fleet/files/2371092/1.0.8.txt)
[2.0.0-rc4.txt](https://github.com/kolide/fleet/files/2371093/2.0.0-rc4.txt)

**Comment by zwass** [comment]
Ah @benbasscom I realize now that you have misunderstood the override semantics of the fleetctl file format. When you create an override you need to include the entire config you'd like to send to hosts of that platform. There is no "inheritance" from the default config. See the example in https://github.com/kolide/fleet/blob/master/docs/cli/file-format.md#osquery-configuration-options.

**Comment by benbasscom** [comment]
Gotcha - didn't realize there wasn't any inheritance.  So if I want to add just specific file_paths, I need to dupe the entire "config" in the darwin override, correct?

**Comment by zwass** [comment]
Correct. We decided not to implement inheritance because it wasn't clear how config sections (like `file_paths`) should be merged when they appeared in both.

**Comment by benbasscom** [comment]
Closing this out - now I know how to configure overrides!  Thank you @zwass!
