### ISSUE TITLE
Missing hosts expected to appear in Fleet

### ISSUE THREAD

**Issue by bubaiwantong** [kolide/fleet#1929]
What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc4

What operating system are you using?
Red Hat Enterprise Linux Server release 6.10 (Santiago)

What did you do?
We added a total of 2000 hosts.But display only 1086 hosts.

What did you expect to see?
How many hosts are the biggest support?

How should I configure and display all hosts?

**Comment by zwass** [comment]
2000 hosts should be supported. We've see folks with 5000 hosts start to get some slowness in the UI, but there is no explicit limit on the number of hosts. Can you run osqueryd manually with `--verbose --tls_dump` on one of the machines that isn't showing up and see if there's anything helpful in the logs?

**Comment by zwass** [comment]
We will close this unless further details are provided.
