### ISSUE TITLE
Pre-select host by IP for ad-hoc queries

### ISSUE THREAD

**Issue by defensivedepth** [kolide/fleet#1934]
I am looking for a way to pre-select a host by IP for an ad-hoc query. I see that I can pre-select using the host ID `https://FleetInstall/queries/new?host_ids=20` But I am not seeing a way to use IP. 

This is to facilitate easier pivoting to Fleet from another tool.

**Comment by defensivedepth** [comment]
As I have worked through this more, I believe a better approach would be to pre-select the host by `uuid`. It is likely that the IP of the system will change at some point and the analyst will want to pivot to the correct host, whether it is the same IP or not.

Also, I would love to see this pre-selected on a page like what you see when using a label ([example](https://www.screencast.com/t/Sq7oGD3oZ6)). This would allow the analyst to see some key info about the host + confirm that it is online before attempting to run the query.

As you can see from the screencap, I have already implemented this but with labels. I don't see labels being a good fit for this once you start trying to scale to 100s or 1,000s of endpoints.

**Comment by zwass** [comment]
In the context you are using this, I assume that you have access to the UUID, but not the Fleet host ID? I seem to remember something about this coming from Kibana... Do you have the UUID there from adding a decorator to the query?

**Comment by defensivedepth** [comment]
Yes, that is correct. Using Kibana and the `uuid` is coming from a decorator query. The Fleet host ID is not accessible.

**Comment by defensivedepth** [comment]
@zwass I am not sure I understand. 

For example -

`select host_name,id,uuid from hosts where uuid = '4C4C4544-0047-3610-8042-B5C04F514832';` 

This endpoint matches the endpoint that is returned from the following osquery queries:

`select * from osquery_info where uuid = '4C4C4544-0047-3610-8042-B5C04F514832';`
`select * from system_info where uuid = '4C4C4544-0047-3610-8042-B5C04F514832';`

Are you perhaps thinking of the `instance_id` column of `osquery_info`?

**Comment by zwass** [comment]
Ah, looks like I was confusing `getHostIdentifier` (https://github.com/facebook/osquery/blob/f9620a9f8be2e458086431ea9ee3d6a6e56c2d2a/osquery/core/system.cpp#L268-L295) with `getHostUUID`(https://github.com/facebook/osquery/blob/f9620a9f8be2e458086431ea9ee3d6a6e56c2d2a/osquery/core/system.cpp#L249-L258). 

It looks like both `system_info` (https://github.com/facebook/osquery/blob/f9620a9f8be2e458086431ea9ee3d6a6e56c2d2a/osquery/tables/system/linux/system_info.cpp#L37) and `osquery_info`(https://github.com/facebook/osquery/blob/f9620a9f8be2e458086431ea9ee3d6a6e56c2d2a/osquery/tables/utility/osquery.cpp#L222) use that same UUID.
