### ISSUE TITLE
Add support for INSERT/CREATE queries

### ISSUE THREAD

**Issue by mari0d** [kolide/fleet#1937]
Hello,

Per https://github.com/kolide/fleet/issues/334 Fleet is blocking queries that use the INSERT or CREATE statements. We are currently trying to roll out an osquery extension in our environment that relies on INSERT statements to update deployed rules on clients and would prefer to use Kolide to push these queries. We have tried pushing INSERT queries via the API & also via bypassing the client-side validation with no luck - there appears to be a server side block as well.

**Comment by zwass** [comment]
@mari0d I added support for this in #1938.

There is no server-side validation of queries, so I would expect the system to allow you to push any query you like directly via the API. Can you show me what error you encountered when trying this?
