### ISSUE TITLE
500 at front ( hosts/manage ) page but all other pages working fine

### ISSUE THREAD

**Issue by keithshum** [kolide/fleet#1939]
### What version of `fleet` are you using (`fleet version --full`)?
/ # fleet version --full
fleet - version 2.0.0-rc5
  branch: 	modify-user-auth
  revision: 	dab8f21d973f81ea455625b975fc8fd99778c5ec
  build date: 	2018-09-18T18:57:45Z
  build user: 	zwass
  go version: 	go1.10.2

### What operating system are you using?
We are on OEL 7.5. 

### What did you do?
We have first experienced the issue on 1.0.8 (in docker) and we performed docker image upgrade to 2.0.0 and ran "fleet prepare db". But still seeing the same behavior.

### What did you expect to see?
Working and healthy host page.

### What did you see instead?
500 on hosts/manage but all other pages are working fine and ok to even run the queries.

Additional info, not sure if it's related, but we got this error while running api against hosts:

$ curl -X GET https://kolide.iad.ssvcs.ocp.oraclecloud.com/api/v1/kolide/hosts -H “Authorization: Bearer ${API_TOKEN}”
{
 “message”: “Unknown Error”,
 “errors”: [
  {
   “name”: “base”,
   “reason”: “select nics for hosts, rebound query: Error 1390: Prepared statement contains too many placeholders”
  }
 ]
}

**Comment by zwass** [comment]
Thanks for reporting this. It looks like the root cause of this is the lack of pagination in the browser UI. This causes the backend to run a query with too many hosts explicitly specified.

There is support for server-side pagination, but we don't currently have the resources to get this implemented in the frontend.

I do have a couple of ideas that I will look into for how we might be able to fix it in the backend.

**Comment by zwass** [comment]
If you want to hit the hosts API, you can add the paging parameters yourself like

`curl -X GET https://kolide.iad.ssvcs.ocp.oraclecloud.com/api/v1/kolide/hosts?per_page=100&page=2 -H “Authorization: Bearer ${API_TOKEN}”`

**Comment by keithshum** [comment]
Nice, Zachary, thanks for the quick fix.
When will the new build come out to the docker image?

**Comment by keithshum** [comment]
Hi Zach,

Here is the summary:

Pulled down e6f4dd54 at https://hub.docker.com/r/kolide/fleet/tags/ and tested again. Pagenation works with API, but without using it, it runs for some time and then giving 502 bad gateway.

$ curl -X GET https://kolide.iad.ssvcs.ocp.oraclecloud.com/api/v1/kolide/hosts -H “Authorization: Bearer ${API_TOKEN}”
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor=“white”>
<center><h1>502 Bad Gateway</h1></center>
<hr><center></center>
</body>
</html>

Also, at UI, it doesn't show 500 at hosts/manage, it is still trying very hard to render all hosts. 

As a user, I suggest the followings...
1. Not to pull all hosts on the landing page. I am really not quite care to see all the hosts at first anyway.  =)
2. However, showing number of hosts in different status is very important to me.
3. If I want to get the list of hosts in certain status, I will click on that and it will bring me to the query page with actual query, "all hosts" pre-occupied values and leads me to hit the RUN button. 
4. Since I am familiar on running queries will take time, I will be patient and wait for it to finish.

We love osquery and kolide fleet! Our host counts are in really large-scale, I think we can partner together and test out your new features. 

Hope this help you guys, thanks!

Keith
