### ISSUE TITLE
Request to add CORS Support

### ISSUE THREAD

**Issue by theharshguy** [kolide/fleet#1946]
### What did you see instead? Preflight cors issue. Method 405 not allowed

Hey guys, 
I was wondering if there's a way around to make fleet cross origin request compatible? I tried various methods but it didn't help. I am trying to create an Android app. Thanks.

**Comment by zwass** [comment]
Can you provide some more details about this? We call the API directly in the `fleetctl` client. For example, https://github.com/kolide/fleet/blob/master/server/service/client_queries.go#L14:18.

**Comment by zwass** [comment]
I'm closing this due to lack of response. Please get in touch via osquery Slack if you'd like to discuss further.
