### ISSUE TITLE
Request to add feature to render timezone differently

### ISSUE THREAD

**Issue by offensivedev** [kolide/fleet#1949]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0-rc5-17-g431ee37-dirty
  branch:       master
  revision:     431ee373c67afc92238a0054d72885aec6eceabc
  build date:   2018-11-01T19:52:03Z
  go version:   go1.11

### What operating system are you using?
Debian (stretch)

**Comment by zwass** [comment]
Can you tell us more about what you are looking for here?

**Comment by offensivedev** [comment]
Hey,

All the logging is in UTC timezone. Is there a possibility to add get logs
from osquery in user specific timezone (say GMT)? Or else there can be an
option to convert timestamps to GMT or other local timezones according to
admin preferences.

**Comment by amitcyberange** [comment]
Can you please guide on doing this on logging pipeline?

**Comment by offensivedev** [comment]
Can you guide on modifying the logging pipeline?

On 16-Nov-2018 5:50 PM, "Amit Kumar" <notifications@github.com> wrote:

Can you please guide on doing this on logging pipeline?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kolide/fleet/issues/1949#issuecomment-439376939>, or mute
the thread

**Comment by zwass** [comment]
You can perform any sort of operations you like on the osquery logs after they are collected by Fleet. You may be able to achieve this with your log forwarding agent, you could write a custom script, etc.
