### ISSUE TITLE
fleetctl convert error

### ISSUE THREAD

**Issue by rubenrodr-versia** [kolide/fleet#1950]
### What version of `fleet` are you using (`fleet version --full`)?
```
fleet - version 2.0.0
  branch:       master
  revision:     3a07a4c07e5c216c5680a0b0dd5300f6019bf7d6
  build date:   2018-10-16T22:32:17Z
  build user:   zwass
  go version:   go1.11
```
### What operating system are you using?
```
LSB Version:    n/a
Distributor ID: SUSE
Description:    SUSE Linux Enterprise Server 12 SP2
Release:        12.2
Codename:       n/a
```
### What did you do?
I'm trying to convert the config files from
https://github.com/teoseller/osquery-attck
and some of them works fine, but with others i get the following errors:
```
fleetctl convert -f network_connection_listening.conf
json: cannot unmarshal string into Go value of type kolide.PermissiveQueryContent
```

**Comment by zwass** [comment]
That pack is valid JSON, but it has an inconsistent/incorrect schema (see https://github.com/teoseller/osquery-attck/blob/master/network_connection_listening.conf#L32). I don't anticipate us making changes to the convert command to support invalid packs. Does osquery accept this as a valid pack? If so, it's likely silently ignoring the error. I'd love to improve the error message, but Go's JSON parser doesn't really give us anything helpful in this case.

**Comment by zwass** [comment]
I'm closing this as I corresponded directly with @teoseller who is fixing the problem in the pack JSON.

**Comment by teoseller** [comment]
fixed in all the query packs sorry for the issue @rubenrodr-versia

**Comment by rubenrodr-versia** [comment]
Thank you for your work and sharing @teoseller !!!

**Comment by teoseller** [comment]
@rubenrodr-versia  could you please confirm that the change solve the issue? thanks

**Comment by rubenrodr-versia** [comment]
Now is working fine, thank you !!!
