### ISSUE TITLE
OWASP top 10 questions

### ISSUE THREAD

**Issue by benbasscom** [kolide/fleet#1951]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.0
  branch: 	master
  revision: 	3a07a4c07e5c216c5680a0b0dd5300f6019bf7d6
  build date: 	2018-10-16T22:32:17Z
  build user: 	zwass
  go version: 	go1.11

### What operating system are you using?
RHEL 7

### Questions for documentation regarding the OWASP top 10.

- Describe your secure coding practices, including code reviews, use of static/dynamic security testing tools, 3rd party scans/reviews.
- How do they test for and prevent the following vulnerabilities in their code:
- SQL Injection
- Broken authentication – authentication, session management flaws that compromise passwords, keys, session tokens etc.
- Sensitive data exposure – encryption in transit, at rest, improperly implemented APIs
- Broken access controls – how restrictions on what authorized users are allowed to do/access are enforced
- Cross-site scripting – ensure an attacker can’t execute scripts in the user’s browser
- Components with known vulnerabilities – prevent the use of libraries, frameworks, other software with existing vulnerabilities

**Comment by benbasscom** [comment]
@zwass That works for me.  I will gladly write up the documentation and do a PR to get it into markdown and into the project.  What would be the best way to get me the answers?  I can do email, DM on slack, I'm open to options.

**Comment by zwass** [comment]
Please go ahead and write up what you can. You can pepper me with questions via Slack.
