### ISSUE TITLE
Add ability to set custom TLS protocols and supported cipher suites

### ISSUE THREAD

**Issue by znb** [kolide/fleet#1952]
### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 2.0.0
  branch: 	master
  revision: 	3a07a4c07e5c216c5680a0b0dd5300f6019bf7d6
  build date: 	2018-10-16T22:32:17Z
  build user: 	zwass
  go version: 	go1.11

### What operating system are you using?

Ubuntu 16.04

**Comment by groob** [comment]
Fleet has the following flag:
```
--server_tls_compatibility string             Env: KOLIDE_SERVER_TLS_COMPATIBILITY
        TLS security profile choose one of modern, intermediate or old (default "modern")
```

The values for "modern", "intermediate" etc correspond to the mozilla wiki here https://wiki.mozilla.org/Security/Server_Side_TLS#Modern_compatibility and are maintained in this bit of code: https://github.com/kolide/fleet/blob/510ec10769ae03375bedd9bdfbf0215825229db6/cmd/fleet/serve.go#L293-L368
If the profiles are out of date, please open a PR to update them. 

IMO if you need customization beyond the three modes fleets offers, the obvious place to do that is to terminate tls with a proxy like nginx or haproxy and set your own rules there.

**Comment by znb** [comment]
Makes perfect sense.
I should have dug a little deeper.

Thank you @groob
