### ISSUE TITLE
Add fleetctl support for Admin Tab.

### ISSUE THREAD

**Issue by stefanmaerz** [kolide/fleet#1953]
Creating an Issue per my conversation with @zwass on osquery's Slack channel

It would be awesome if I could manage the "Admin" tab (specifically App Settings) via fleetctl/yaml files. This  would help Fleet admins keep the configuration under revision control and help make deploying fleet even more reproducible.

Best Regards,
-Stefan

**Comment by zwass** [comment]
This was addressed by #2143.
