### ISSUE TITLE
Fleetctl Returning Inaccurate Pack YAML

### ISSUE THREAD

**Issue by clong** [kolide/fleet#1956]
### What version of `fleet` are you using (`fleet version --full`)?
```
{
  "version": "2.0.0",
  "branch": "HEAD",
  "revision": "3a07a4c07e5c216c5680a0b0dd5300f6019bf7d6",
  "go_version": "go1.11",
  "build_date": "2018-10-25T20:00:12Z",
  "build_user": "marpaia"
}
```
Probably worth noting that this console has been updated quite a bit over time, so there may be some legacy DB artifacts from older builds hanging around.

### What operating system are you using?
Linux/Docker to host Fleet

### What did you do?
`fleetctl get pack macpack`

### What did you expect to see?
A 1:1 representation of what I see in the Fleet UI in the YAML

### What did you see instead?
Queries that are no longer present in the pack (and some which have been deleted from the console entirely) are being included in the pack YAML.

I've been able to semi-work around this problem by re-creating deleted queries, adding them, and then immediately removing them from the pack. It seems whatever datasource Fleetctl pulls from gets updated when I do that. 

Here's the most straight forward example I can provide:
Our console shows 53 queries present for the "macpack" query pack:
![image](https://user-images.githubusercontent.com/5092699/48641114-94265200-e98d-11e8-9192-efe30646bd04.png)

However, using fleetctl returns 61 queries:
```
$ fleetctl get pack macpack | grep name: | grep -v 'name: macpack' | wc -l
61
```

**Comment by zwass** [comment]
This looks to be the same issue with soft deletion as reported in https://github.com/kolide/fleet/issues/1923. I expect the equivalent solution to work for scheduled queries. While we are at it, I will also fully delete soft deleted queries and labels.

**Comment by clong** [comment]
@zwass are there instructions anywhere for running the data migration mentioned in #1923 ?

**Comment by zwass** [comment]
@clong that migration should have run when you did `fleet prepare db`. I'm adding a migration to delete the other entities discussed.

If you want to do it now directly via MySQL it would be:
```
DELETE FROM scheduled_queries WHERE deleted = 1;
DELETE FROM queries WHERE deleted = 1;
DELETE FROM labels WHERE deleted = 1;
```
