### ISSUE TITLE
Pass and ENV var to allow Fleet to initialize database if it isn't initialized

### ISSUE THREAD

**Issue by TOoSmOotH** [kolide/fleet#1963]
### What operating system are you using?
CentOS 7 and Docker
### What did you do?
Added the docker container. Started the docker using salt and passing ENV variables. Trying to make the deployment automated for end users.

### What did you expect to see?
The docker start up. 
### What did you see instead?
```
################################################################################
# ERROR:
#   Your Fleet database is not initialized. Fleet cannot start up.
#
#   Run `fleet prepare db` to initialize the database.
################################################################################
```

**Comment by robusto** [comment]
Could you do this with Docker? Fleet's default Docker image only runs the simple `fleet serve` command by default, but you could override the default docker command "fleet prepare db" of the Kolide image.

e.g.
```
# one-off container run
docker run kolide/fleet fleetctl prepare db [mysql_args]
# fleet serve
docker run -d kolide/fleet 
```

**Comment by TOoSmOotH** [comment]
I ended up creating my own Dockerfile and entrypoint script that will do the above. It calls prepare db and then fleet serve each time it starts. https://github.com/Security-Onion-Solutions/securityonion-docker-hh/tree/master/so-fleet

**Comment by groob** [comment]
What is `sleep infinity`? The `fleet serve` command will already run continuously (unless you kill the process or the server crashes). 

As noted in our Slack conversations, we prefer fleet’s migrations to be an explicit step for the operator to invoke/automate as best fits their workflow. Unfortunately migrations can be somewhat complex(even if they often are not), and making this step implicit would be problematic. 

For an environment running the docker container, an entrypoint seems fine.

**Comment by TOoSmOotH** [comment]
I had that in there as a catch all so I could get into the container if something crashed to troubleshoot.
