### ISSUE TITLE
[feature request] Host grouping feature based on custom value, instead of labels

### ISSUE THREAD

**Issue by uf0o** [kolide/fleet#1967]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.1
  branch: 	master
  revision: 	d01727dff26683ba29424fbdb7e58e403ab6210d
  build date: 	2018-11-26T19:21:48Z
  build user: 	zwass
  go version: 	go1.11.2

### What operating system are you using?
$ uname -a
Linux matteo-virtual-machine 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Hi!

As far as I know, labels need at least a query that returns the same value for the same host-group.
In my case, where there is no naming convention, we would like to have a static, local way to group the different fleets, without involving any queries.
Else, a query that returns and save a custom value we can insert in the query in advance.
Would be possibile to implement this kind of feature? I do believe it'd require a local database to manage different hosts belonging to different groups.

**Comment by blaedj** [comment]
I _think_ what you're describing could be a label where the membership is determined by a human, rather than by logic defined in a query?

**Comment by uf0o** [comment]
> I _think_ what you're describing could be a label where the membership is determined by a human, rather than by logic defined in a query?

@blaedj indeed. 
That's what I am trying to achieve: assign a label based on human categories instead of i.e. a query based on hostname convention.
Is it something already available on the codebase? thank you

**Comment by blaedj** [comment]
Unfortunately this isn't currently available in fleet, no.
