### ISSUE TITLE
Fleet unable to return query results for large number of hosts

### ISSUE THREAD

**Issue by nyanshak** [kolide/fleet#1980]
### What version of `fleet` are you using (`fleet version --full`)?
Tested both 2.0.0 and commit hash be85377

### What did you do?
I was doing load tests before rolling out fleet to manage a large number of hosts.

Relevant infra config:
* 2 to 20 c4.4xlarge instances in an ASG behind an ALB running fleet
* RDS db.m5.12xlarge running MySQL 5.7.23, with 10K PIOPS (~3.4K PIOPS needed at steady-state under load).

Load generators:
* I set up m5.4xlarge instances in an ASG to run osquery docker containers. I didn't spend a lot of time optimizing this section, so I could get ~400 reliable osquery clients per m5.4xlarge instance before encountering some issues. I would scale this up to add additional osquery clients to register in kolide.
** I found that 2 c5.4xlarge fleet instances could handle ~25k clients at steady-state (just checking for config) with about ~20-40% CPU. The db.m5.12xlarge DB would hover around 20% CPU at steady-state.

After connecting a large number of clients, I would attempt to run a query against all clients.
Example query that I would run: `SELECT uuid FROM osquery_info`

### What did you expect to see?

I expected to see all clients reporting results in the UI after a few minutes.

### What did you see instead?

Rather than getting all hosts reporting in, I'd see only 200-1200 hosts reporting in (out of 8000), then the query would continue to run for a long time (10+ minutes) before timing out without all the results.

Whereas normally CPU on both the fleet servers and the DB would normally be at ~20-30%, upon initiating any query, CPU would be maxed out attempting to run any query against all hosts.

[ cc @zwass @groob ]

**Comment by nyanshak** [comment]
Slack user (in osquery slack) @daniel319b reported the same issue with not being able to get results from a large number of hosts, and reportedly resolved by modifying redis settings:

```
The problem was with Redis.
I noticed in the logs that Redis was dropping the client's subscription a few minutes after I launched a live query and that's what caused it to stuck.
I had to increase the "output buffer limit" in the Redis configuration and that fixed the problem.
```

I attempted this fix by upgrading node type in ElastiCache but this did not improve my situation. It seems that redis is hardly being used at all (based on CPU and network I/O) so I'm not surprised this did not resolve the issue.

---

Additional details:

I also see these errors in logs while the problem is happening:

• failed to ingest result: recording execution: insert distributed campaign target: Error 1062: Duplicate entry '139863-20' for key 'idx_dqe_unique_host_dqc_id'
• failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction
• write tcp X.X.X.X:XXXX->Y.Y.Y.Y:YYYY i/o timeout

**Comment by zwass** [comment]
@nyanshak:

1) What intervals do you have your osqueryd hosts set at? `distributed_interval`, `config_refresh`, `logging_interval`

2) How many of each of those errors are you seeing?

3) Are you saying that CPU on the fleet servers _and_ on the DB server goes to 100% when you run the query?

4) Can you provide any information from the [MySQL slow query log](https://dev.mysql.com/doc/refman/8.0/en/slow-query-log.html)?

5) Are you certain that your osquery docker containers are able to handle 400 all trying to execute the query?

**Comment by nyanshak** [comment]
1) `logging_interval` is at 60 seconds, `config_refresh` was originally at 10 seconds (I've since increased that to 300 seconds, `distributed_interval` was originally set to 30 seconds (I've since Increased it to 300 seconds).
2) The majority of errors were the 'failed to ingest result' error, and it was in the order of X,000.
4) Slow-query log only contained logs like this:
```
# Time: 2019-01-07T19:42:20.015419Z
# User@Host: username[username] @  [10.107.80.16]  Id:   853
# Query_time: 10.075199  Lock_time: 0.000088 Rows_sent: 1  Rows_examined: 65444
SET timestamp=1546890140;
SELECT DISTINCT dqc.id, q.query
		FROM distributed_query_campaigns dqc
		JOIN distributed_query_campaign_targets dqct
		    ON (dqc.id = dqct.distributed_query_campaign_id)
		LEFT JOIN label_query_executions lqe
		    ON (dqct.type = 0 AND dqct.target_id = lqe.label_id AND lqe.matches)
		LEFT JOIN hosts h
		    ON ((dqct.type = 0 AND lqe.host_id = h.id) OR (dqct.type = 1 AND dqct.target_id = h.id))
		LEFT JOIN distributed_query_executions dqe
		    ON (h.id = dqe.host_id AND dqc.id = dqe.distributed_query_campaign_id)
		JOIN queries q
		    ON (dqc.query_id = q.id)
		WHERE dqe.status IS NULL AND dqc.status = 1 AND h.id = 148229
			AND NOT q.deleted
			AND NOT dqc.deleted;
```
5) I think so, but will have to do more testing to confirm.

Right now, I'm trying to increase ALB timeout settings, increase intervals, and hopefully that will help with these problems.

**Comment by zwass** [comment]
Please answer question 3 from above.

Can you please copy/paste that query into the mysql shell prefixed with explain: `explain ...` and provide the results?

**Comment by zwass** [comment]
Was this closed intentionally? Did you find a fix?

**Comment by nyanshak** [comment]
I'm still seeing poor behavior in that it seems to time out after some # of clients report in (much less than the full amount), but currently unable to reproduce the pattern I was seeing earlier with very high CPU use on the DB. I've gotten ~2K results and it seems my browser tab becomes responsive.

I think there could likely be multiple ways to approach a "fix":

* Have fleet stagger client's responding by limiting to roughly N concurrent clients with outstanding queries, such that X,000 clients aren't trying to report results at once.
* Don't provide all results in one page, but make an async job that's linked after the query is started. Have said results page paginate results.

Unfortunately I don't have time to dig into this further, but I believe it's a combination of large # of concurrent requests / DB queries / browser resources being exhausted preventing full results set to be viewed.

**Comment by zwass** [comment]
I recently worked with another user who got acceptable performance for their fleet of 30k machines by tuning the `distributed_interval`, `config_refresh`, and `logger_tls_period` flags. FWIW the suggestion to stagger query results would be easily achieved by modifying the `distributed_interval` flag.

Given that there remain unanswered questions from above and you don't have time to dig into this further, I'm going to close the issue. If you or other users have similar issues in the future, please comment or create a new issue so we can look into it.
