### ISSUE TITLE
How enable control flag: "--windows_event=false" in global environment 

### ISSUE THREAD

**Issue by aCruzQ** [kolide/fleet#1981]
### What version of `fleet` are you using (`fleet version --full`)?
version 2.0.0

### What operating system are you using?
CentOS 7 x64 

### What did you do?
Tried to disable the "--disable_events=false" on global settings (Kolide Fleet server)

### What did you expect to see?
Enable this flag to run queries related to windows events.

### What did you see instead?
Many issues posted, but nothing in a global environment.

**Comment by zwass** [comment]
You would set this in the same way you set any other osquery options. You could either do it through the flagfile you use to start up the osqueryd clients, or the configuration the Fleet server pushes (see https://github.com/kolide/fleet/blob/master/examples/config-many-files/config.yml).

**Comment by aCruzQ** [comment]
Hi Zwass.
I added this line; but dont work.

[Unit]
Description=Kolide Fleet
After=network.target

[Service]
LimitNOFILE=8192
ExecStart=/usr/local/bin/fleet serve \
  --mysql_address=127.0.0.1:3306 \
  --mysql_database=kolide \
  --mysql_username=root \
  --mysql_password=toor \
  --redis_address=127.0.0.1:6379 \
  --server_cert=/tmp/server.cert \
  --server_key=/tmp/server.key \
  --auth_jwt_key=this_string_is_not_secure_replace_it \
  ### --disable_events=false \
  --logging_json

[Install]
WantedBy=multi-user.target

I tried to: "---osquery_disable_events=false \", but dont work neither.

Thanks.
