### ISSUE TITLE
API endpoint to expose log file information

### ISSUE THREAD

**Issue by rpr5x** [kolide/fleet#2000]
Is there an API endpoint that exposes the data written to the `osquery_result` log file? I'm using a Docker container to run Fleet and my goal is to share the contents of this file with a second Docker container so that the second Docker container can parse the data in this file.

**Comment by zwass** [comment]
@rpr5x My recommendation would be to have the Docker containers share a volume for the log files. Check out https://www.digitalocean.com/community/tutorials/how-to-share-data-between-docker-containers.
