### ISSUE TITLE
Fleet UI replaces `+` with ` ` in user email address

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#2001]
### What version of `fleet` are you using (`fleet version --full`)?
I'm using the docker image `kolide/fleet:2.0.0`

### What operating system are you using?
I'm using the docker image `kolide/fleet:2.0.0`

### What did you do?
Added a user with an email of `foo+bar@example.org`

### What did you expect to see?
The user's email to be `foo+bar@example.org`

### What did you see instead?
The user's email to be `foo bar@example.org`

Using the `+` feature of gmail is very useful for any automation users.

**Comment by zwass** [comment]
Are you using the web UI? Does this reproduce in 2.0.2? I was able to add users with `+` in the email.

<img width="841" alt="screen shot 2019-03-07 at 11 58 30 am" src="https://user-images.githubusercontent.com/575602/53985418-5f6f0f80-40d0-11e9-848c-6ce13f6a5644.png">

**Comment by crimsonknave** [comment]
I haven't tried with `2.0.2` yet. But, I was able to determine that the issue came from the parameters that were populated in the url on sign up. My staging environment is stuck with a space, but for my production environment, I replaced the `+` in the url with a url encoded plus and everything worked.

For some reason, I was not able to change the email address when it had a space in it. Every time I tried to update it, it appeared to work until I reloaded the page. But, I also haven't spent much time on this.

**Comment by zwass** [comment]
I tried to reproduce in the initial signup flow as well and found that I could create a user with + in the email. I'm going to close this issue, but can reopen if you find it still reproduces for you in 2.0.2.

If upgrading to 2.0.2 doesn't allow you to fix the stuck user through the UI, please consider doing an update to the `users` table in MySQL.
