### ISSUE TITLE
Please provide an ability to configure an initial admin user and other settings automatically

### ISSUE THREAD

**Issue by alexclear** [kolide/fleet#2003]
I'm trying to build a fully automated Fleet setup using Vagrant, Docker, and Ansible. My goal is to have all the configuration described as code.
I still have to configure an initial admin, a Kollide URL, and organization settings manually in a browser.

**Comment by clong** [comment]
You can do it using Fleetctl. Check out these lines of code from this Vagrant project: https://github.com/clong/DetectionLab/blob/master/Vagrant/bootstrap.sh#L139-L146

**Comment by alexclear** [comment]
Works for me, thank you!
