### ISSUE TITLE
Set how frequently Fleet updates each host's database entry

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#2007]
Yesterday I enrolled ~1500 hosts into our Fleet server. This caused some database issues due to a how frequently the hosts table was updated. (I'm no database expert, I'm just parroting what our database folks told me.)

It appears that every second each host's entry in the database is updated. This meant that every hour there were 5 million updates. 

We use ROW based replication, where each update to a row writes the complete row image into the binary log. Even if you just update a timestamp - the entire row data is written down.

These two things combined to run one of our database servers out of disk. I'm currently working with out database team to figure out updated specs for the database cluster given this type of load. I'm confident that we can get everything to work for our given set of hosts, but this seems like it might be unnecessary load.

Is there a way to change how often Fleet updates each host's database entry? Does Fleet need to be updating each host every second or could it update every minute or 15 second?

### What version of `fleet` are you using (`fleet version --full`)?
Using the docker image `kolide/fleet:2.0.0`

### What operating system are you using?
Using the docker image `kolide/fleet:2.0.0`

**Comment by zwass** [comment]
Fleet only updates each host when that host checks in. What do you have the intervals set at? We would be interested in `config_refresh`, `distributed_interval`, and `logger_tls_period`.

There's little reason to have these set to anything under 30 seconds when working with thousands of hosts.

**Comment by crimsonknave** [comment]
I believe that I copied the settings from https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md#launching-osqueryd, but my settings are:

* `config_tls_refresh` = 10
* `distributed_interval` = 10
* `logger_tls_period` = 10

In the osqueryd logs, there are 4 lines every 10 seconds
* POST `/api/v1/osquery/log`
* POST `/api/v1/osquery/distributed/read`
* `Refreshing configuration state`
* POST `/api/v1/osquery/config`

I also had multiple browser windows open to the hosts page as I was monitoring the rollout. Would that have had any impact?

**Comment by zwass** [comment]
This configuration would result in each host row being updated 3 times every 10 seconds. The host entry is updated with a "last seen" time so that we can calculate the online status. You may be better off with a `distributed_interval` around 30s and `config_refresh`/`logger_tls_period` around 5min. This would make an order of magnitude reduction in writes to those rows.
