### ISSUE TITLE
Cant receive results from fleet api

### ISSUE THREAD

**Issue by kp625544** [kolide/fleet#2013]
I m trying to interact with the fleet server api. As I see its not documented at all still I was able to get most endpoints via inspecting elements in chrome. One thing I m still not able to get is how do I get the query results with the api. There seems to be some sort of web sockets connection going on.
Can someone help me with it?

**Comment by rubenrodr-versia** [comment]
I had issues with apache as reverse proxy to get fleetctl working.
Take a look at this:
https://github.com/kolide/fleet/issues/1840
Hope it helps.

**Comment by kp625544** [comment]
I dont want to use fleetctl! thats cli right? I want to make api requests with python to results endpoint. @rubenrodr-versia

**Comment by rubenrodr-versia** [comment]
I think fleetctl uses the API.

**Comment by kp625544** [comment]
It does but how can I extract the api call from it?

**Comment by rubenrodr-versia** [comment]
Maybe using burp
https://portswigger.net/burp/documentation/desktop/tools/proxy/intercept

**Comment by kp625544** [comment]
trying through burp :p burp seems the only solution unless some author responds with a better way.

**Comment by kp625544** [comment]
didn't even get through burp. can any author help with it?

**Comment by zwass** [comment]
You can check out the Golang implementation of the live query client here: https://github.com/kolide/fleet/blob/master/server/service/client_live_query.go. Some of the JS code is here: https://github.com/kolide/fleet/blob/master/frontend/kolide/websockets.js It might also be helpful to run a live query through the web UI and take a look at the network inspector. Both `fleetctl` and the web UI use the same API endpoints.

If you have any more questions, please feel free to follow up in #kolide the osquery Slack.

**Comment by seren** [comment]
For anyone running across this in a search for the `upgrade live query result websocket: x509: certificate signed by unknown authority` error, you may also want to check that your `~/.fleet/config` contains `tls-skip-verify: true` if you're using a self-signed certificate.
