### ISSUE TITLE
error while marshaling: proto: field \"kolide.agent.LogCollection.Log.Data\" contains invalid UTF-8

### ISSUE THREAD

**Issue by cyberonstian** [kolide/fleet#2014]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.0.2
  branch:       master
  revision:     8ca0358bf28173685815b79d8683a4239d629a14
  build date:   2019-01-18T00:39:40Z
  build user:   zwass
  go version:   go1.11.3¨
### What operating system are you using?
Windows 10 Pro 1893
### What did you do?
1. Install Kolide Fleet agent on the client
2. Start in debug mode
3. Wait a couple of minutes, we see that the server is recieving data from the client
4. The error appears in the logs and no data is recieved on the server.
### What did you expect to see?
Data sent from launcher.exe
### What did you see instead?
{"caller":"publish_logs.go:157","err":"rpc error: code = Internal desc = grpc: error while marshaling: proto: field \"kolide.agent.LogCollection.Log.Data\" contains invalid UTF-8","errcode":"","logType":"string","log_count":3,"message":"","method":"PublishLogs","reauth":false,"severity":"info","took":"0s","ts":"2019-03-12T12:34:15.8004054Z","uuid":"bde64b33-697d-4782-b8a2-866e0a44e71a"}

{"caller":"extension.go:494","err":"sending string logs: writing logs: transport error sending logs: rpc error: code = Internal desc = grpc: error while marshaling: proto: field \"kolide.agent.LogCollection.Log.Data\" contains invalid UTF-8","severity":"info","ts":"2019-03-12T12:34:15.8014026Z"}

Any tips on what we can do to troubleshoot this?

**Comment by cyberonstian** [comment]
Here is what has happened:
After installing the agent the agent runs normally for a while, then suddenly it gives this error in the log and launcher stops sending log data to the fleet server.

If we delete the osquery.d database and restart launcher it works for a while. Then it stops working again. When this is happening we can still see the endpoint is online in fleet.

These are the log entries just before the error starts when running launcher in debug:
{"caller":"scheduler.cpp:100","component":"osquery","msg":"I0312 13:34:11.782730 37124 scheduler.cpp:100] Executing scheduled query pack/centry_os/uptime: SELECT * FROM uptime","severity":"debug","ts":"2019-03-12T12:34:11.7827319Z"}

{"caller":"request_config.go:111","config_size":5502,"err":null,"method":"RequestConfig","reauth":false,"severity":"debug","took":"26.9565ms","ts":"2019-03-12T12:34:12.5188314Z","uuid":"d70d07e6-a2f5-4504-ba6e-aeca2dea702d"}

{"caller":"query_target.go:71","msg":"server does not implement GetTargets","severity":"debug","ts":"2019-03-12T12:34:14.2945246Z"}

{"caller":"publish_logs.go:157","err":null,"errcode":"","logType":"status","log_count":3,"message":"","method":"PublishLogs","reauth":false,"severity":"debug","took":"9.9748ms","ts":"2019-03-12T12:34:15.7905716Z","uuid":"1e251ab8-5e32-4f75-87d5-b9e35f0a093f"}

**Comment by zwass** [comment]
Can you please reopen this issue in the https://github.com/kolide/launcher repo? I'm going to close the one here as this appears to be a Launcher issue and not Fleet. When you do that, please include which queries you are scheduling.

**Comment by groob** [comment]
https://github.com/facebook/osquery/issues/5288
