### ISSUE TITLE
Can not find any hosts with dash symbol in hostname

### ISSUE THREAD

**Issue by ksverdlov** [kolide/fleet#2017]
### What version of `fleet` are you using (`fleet version --full`)?

```
fleet - version 2.0.2
  branch:       changelog
  revision:     96008f11bb51605cbf22b7bb6f883d262ce13a28
  build date:   2019-01-18T00:27:22Z
  build user:   zwass
  go version:   go1.11.3
```

### What operating system are you using?

Server: CentOS Linux release 7.6.1810 (Core)
Client: Windows 10 1809 64-bit Professional

### What did you do?

Try to find any host with hostname contains dash character.

### What did you expect to see?

Find it.

### What did you see instead?

When I type a dash to **Select Targets** field I see the errors in Chrome console:

```POST https://kolidefleet.domain.com:8412/api/v1/kolide/targets 500
bundle-f92fb5f….js:1
Uncaught (in promise) Error: [object Object]
    at Function.value (bundle-f92fb5f….js:1)
    at bundle-f92fb5f….js:1```

**Comment by defensivedepth** [comment]
Further context: https://osquery.slack.com/archives/C1XCLA5DZ/p1545418439002300

From woogs on the thread:

_Figured it out, looks to have been an artifact of how mysql configures tokens for FULLTEXT search. By default `innodb_ft_min_token_size` is set to 3 and `ft_min_word_len` is set to 4. In addition, the `-` can not be used as a token, so when I have systems named something like `fo-ba-1`, there aren't any tokens available that can be searched on and so searches fail. (Side note, typing `-` into the select hosts dropdown, results in a 500 error and a SQL error returned)_

_This was also effecting the ability to search with some IP addresses, especially if your hosts use only 2 digits or less in each octet._

_End result, I modified `innodb_ft_min_token_size` to 1 and rebuilt the FULLTEXT index on the hosts table. This results in getting the appropriate results back for all of my hosts._
