### ISSUE TITLE
UI showing incorrect MAC and IP for a Windows machine with two NICs

### ISSUE THREAD

**Issue by recvfrom** [kolide/fleet#2020]
Reposting from https://github.com/kolide/fleet/issues/1728#issuecomment-470257550:

It looks like the MAC Address and IP that get reported aren't always for the correct interface:

![image](https://user-images.githubusercontent.com/36489577/53910132-1f9d1f00-4021-11e9-91ed-92bdcd15ca8b.png)

![image](https://user-images.githubusercontent.com/36489577/53910161-317ec200-4021-11e9-965e-99eaa0cf0bd0.png)

This is using:
```
./build/fleet version --full
fleet - version 2.0.2-2-g4135ad7d
  branch: 	master
  revision: 	4135ad7d3fa654ec52375cfa1f0201b702569778
  build date: 	2019-03-05T19:18:37Z
  build user: 	mrt
  go version: 	go1.10.4
```

The logs show that it's talking to the correct IP:
```
ts=2019-03-06T20:07:09.589047498Z component=service method=GetClientConfig ip_addr=192.168.1.206:49798 err=null took=1.671134ms
```

Would it be possible to pull the IP from the connection information and then use that to select the appropriate interface and know which MAC address to display?

**Comment by zwass** [comment]
Fleet chooses the network interface with the most activity (queried via osquery) to decide what is "primary". It is not clear to me that we would want to choose a different definition. I think the reality is that this may not be the right choice for some environments, but it seems to work for many.

**Comment by recvfrom** [comment]
Maybe an easy fix would be to ignore interfaces configured with a 169.254.0.0/16 IP address?  I'm assuming the code probably already ignores interfaces with address 127.0.0.1?

**Comment by zwass** [comment]
Ah, that is a good idea. I don't think we are doing either currently.

I'm going to go ahead and implement this unless anyone has concerns about it.

**Comment by YehonathanRa** [comment]
Hi @zwass, 

I couldn't find the code which selects the network interface with the most activity.
