### ISSUE TITLE
Fleet 🚫🍌in 🖥 hostname

### ISSUE THREAD

**Issue by chelming** [kolide/fleet#2041]
### What version of `fleet` are you using (`fleet version --full`)?
"version": "2.1.1",
"branch": "master",
"revision": "918b9facd140a2bb80cdf589b6d87e58c8cf90ff",
"go_version": "go1.11.5",
"build_date": "2019-05-04T01:00:59Z"

### What operating system are you using?
RHEL 7.something

### What did you do?
One of my 🐴coworkers named his computer 🍌. It's actually bound to ActiveDirectory with that name and it's windows computer name matches. It's legit.

### What did you expect to see?
🍌

### What did you see instead?
`??`

**Comment by directionless** [comment]
May relate to  https://github.com/kolide/launcher/pull/481
Or may be a dup of https://github.com/kolide/fleet/issues/1268

@cwhits Can you check your mysql encoding?

**Comment by directionless** [comment]
Some discussion from slack with the OP and their coworker:

1. Mysql is using `utf8mb4`
2. livequery `SELECT hostname AS hostname FROM system_info;` returns `??.ad.rit.edu`
3. livequery `select '🤕';` gets a lot of emoji from a lot of hosts
4. osquery -i returns `??` too

```
osquery> SELECT hostname AS hostname FROM system_info;
+---------------+
| hostname      |
+---------------+
| ??.ad.rit.edu |
+---------------+
```

powershell also returns `??`
```
PS C:\WINDOWS\system32> [System.Net.Dns]::GetHostName()
??
PS C:\WINDOWS\system32>
```


This is looking more like how windows returns that data

**Comment by zwass** [comment]
I am closing this as an osquery issue. Fleet does support emoji hostnames if they are returned from osquery.
