### ISSUE TITLE
Adding create react app to makefile?

### ISSUE THREAD

**Issue by DevTGhosh** [kolide/fleet#2042]
How do I go about using create react app in Makefile? 
Currently in Makefile `make generate` is generating the webpack bundle and then creating the bindata source file how do I go about adding CRA to this and add relevant `react-scripts`?

**Comment by devg02** [comment]
Yeah that is where I am stuck I am not sure how to replace the `frontend/template` assets  with create react app in bindata. 

What do I need to change in this part so that it bundles `react-scripts start` npm script when I run `make generate`

```
go-bindata -pkg=service \
		-o=server/service/bindata.go \
		frontend/templates/ assets/...
	go-bindata -pkg=kolide -o=server/kolide/bindata.go server/mail/templates
```

**Comment by DevTGhosh** [comment]
This is where I am stuck I am unsure how to integrate the go back end to the new CRA front end. I think that is what is happening in the `make generate` command though I could be wrong. 

What do I need to change in this so that bindata points to the appropriate files? 

```
go-bindata -debug -pkg=service \
		-o=server/service/bindata.go \
		frontend/templates/ assets/...
	go-bindata -pkg=kolide -o=server/kolide/bindata.go server/mail/templates
```

**Comment by devg02** [comment]
This is where I am stuck I am unsure how to integrate the go back end to the new CRA front end. I think that is what is happening in the `make generate` command though I could be wrong. 

What do I need to change in this so that bindata points to the appropriate files? 

```
go-bindata -debug -pkg=service \
		-o=server/service/bindata.go \
		frontend/templates/ assets/...
	go-bindata -pkg=kolide -o=server/kolide/bindata.go server/mail/templates
```

**Comment by groob** [comment]
`go-bindata` just takes what is available in the `assets/...` tree and serves those files via the file server at `/assets/`  on the server. 

https://github.com/kolide/fleet/blob/master/server/service/frontend.go#L51

**Comment by groob** [comment]
How bindata works is also documented here https://github.com/kolide/go-bindata#usage

**Comment by zwass** [comment]
I'm going to close this issue. If you'd like to further discuss Fleet development let's do so in the #kolide channel in [osquery Slack](https://osquery-slack.herokuapp.com/).
