### ISSUE TITLE
SAML ID makes Azure IDP barf

### ISSUE THREAD

**Issue by dgags** [kolide/fleet#2044]
### What version of `fleet` are you using (`fleet version --full`)?

```[fleet@fleet ~]$ fleet version --full
fleet - version 2.1.0
  branch: 	master
  revision: 	ab948beb718230483c12b84995f79034eb3f0777
  build date: 	2019-04-09T18:31:16Z
  build user: 	zwass
  go version: 	go1.11.5
[fleet@fleet ~]$
```

### What operating system are you using?

```
[fleet@fleet ~]$ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[fleet@fleet ~]$
```

### What did you do?
When configuring SAML we noticed that every now and the SAML exchange with our IDP (Azure) was failing.
### What did you expect to see?
Logins without errors
### What did you see instead?
An error returned from Azure
### Additional info
The Azure documentation [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol) specifies that the ID cannot begin with a number.

I think if the recommendation is followed there and something as simple as a 2 letter string is prepended to the SAML ID, this problem should go away:
https://github.com/kolide/fleet/blob/918b9facd140a2bb80cdf589b6d87e58c8cf90ff/server/sso/validate.go#L179-L189

**Comment by zwass** [comment]
Happy to follow the recommendation there. PR incoming.

**Comment by dgags** [comment]
Thanks @zwass, much appreciated.
