### ISSUE TITLE
Running Queries not working while deploying fleet over docker

### ISSUE THREAD

**Issue by anishvarghese** [kolide/fleet#2047]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.1.1
  branch:       master
  revision:     918b9facd140a2bb80cdf589b6d87e58c8cf90ff
  build date:   2019-04-25T21:05:09Z
  build user:   zwass
  go version:   go1.11.5

### What operating system are you using?
Docker 
### What did you do?
I run  some simple queries in the fleet deployed over docker
### What did you expect to see?
I need to get the result of the query
### What did you see instead?
Query executing but didn't get the result over dashboard..

{"err":"submit launcher results: failed to ingest result: writing results: PUBLISH failed to channel results_1: dial tcp: lookup redis on 127.0.0.11:53: server misbehaving","errcode":"","message":"","method":"PublishResults","reauth":false,"results"

**Comment by zwass** [comment]
Have you investigated your Redis configuration? I'm not sure what `server misbehaving` means, but it seems likely you have something misconfigured here.

**Comment by zwass** [comment]
Closing this issue as it does not look like a Fleet bug and there have been no further updates.
