### ISSUE TITLE
AIL 20161118212436_CreateTableDistributedQueryCampaigns.go (Error 1293: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause), quitting migration

### ISSUE THREAD

**Issue by asterisk800** [kolide/fleet#2050]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.1.0
  branch: 	master
  revision: 	ab948beb718230483c12b84995f79034eb3f0777
  build date: 	2019-04-09T18:31:16Z
  build user: 	zwass
  go version: 	go1.11.5

### What operating system are you using?
Red Hat Enterprise Linux Server release 7.3 (Maipo)

### What did you do?

/usr/bin/fleet prepare db \
>     --mysql_address=127.0.0.1:3306 \
>     --mysql_database=kolide \
>     --mysql_username=kolide \
>     --mysql_password=kolide
2019/05/23 17:00:21 FAIL 20161118212436_CreateTableDistributedQueryCampaigns.go (Error 1293: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause), quitting migration.

### What did you expect to see?
Successfully completion of the prepare db step

### What did you see instead?

2019/05/23 17:00:21 FAIL 20161118212436_CreateTableDistributedQueryCampaigns.go (Error 1293: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause), quitting migration.

### Database info
mysql -V
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by zwass** [comment]
Folks have reported various issues with MariaDB, though I do think it is possible to get it working.

Fleet is definitely compatible with MySQL 5.7.

**Comment by asterisk800** [comment]
@zwass thanks for your feedback! Moved to MySQL 5.7 and It works as expected.
