### ISSUE TITLE
New Query: Selecting hosts resets the query that is run, but the query in the UI does not reflect this

### ISSUE THREAD

**Issue by jalseth** [kolide/fleet#2072]
### Description
Whenever you select targets on the New Query page, the query resets to `select * from osquery_info` even though the UI does not reflect this. This means if you type your query, then select which hosts to run it on, it runs the incorrect query.

### What version of `fleet` are you using (`fleet version --full`)?
2.1.2

### What operating system are you using?
Ubuntu 18.04

### What did you do?
1. Enter the query `select * from processes`
2. Select a target host
3. Click Run

### What did you expect to see?
All of the process info from the running processes on the machine

### What did you see instead?
The results from the default query of `select * from osquery_info` EG:

```
hostname | build_distro | build_platform | config_hash | config_valid | extensions | instance_id | pid | start_time | uuid | version | watcher
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
ubuntu-bionic | xenial | ubuntu | 61708579349720730bf82cfe000ae9b9ad548a94 | 1 | active | c755078e-8929-453e-ba61-7817a7e5848f | 1825 | 1562016672 | B2435C0D-2FA9-4745-BB95-554A1CD00714 | 3.3.2 | 1823
```

### Other details
Changing the query at all, even just adding a semicolon to the end and running it again will make the correct query execute.

**Comment by zwass** [comment]
Apologies for this bug. It was documented in #2054 and fixed in #2060. We will be getting out a new release with the fix shortly.
