### ISSUE TITLE
Indicate in the UI when Redis is not running

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#2073]
### What version of `fleet` are you using (`fleet version --full`)?
Any

### What operating system are you using?
Any

### What did you do?
Try to run a live query (with Redis not running or unable to connect).

### What did you expect to see?
Query results

### What did you see instead?
Spinning box animation.

Users are often confused when no results appear. The UI should make clear that no results will be coming because there is no Redis connection.

**Comment by icebawkz** [comment]
Took me a while to figure this out. This would be wonderful for those new to Fleet
