### ISSUE TITLE
I can't run queries/pack from the Kolide API

### ISSUE THREAD

**Issue by aCruzQ** [kolide/fleet#2085]
Hi, 
when trying to run any query under Kolide API; this shows me, as a result, this message:
_### "**Upgrade live query result WebSocket: x509: certificate signed by unknown authority**"_

When running any query/pack from Kolide web; I haven't any problem.
I'm using a public certificate.
I have enrolled 10 hosts with W10 OS and 1 with Linux.
Some other commands show me successful results; as these commands:

$ fleetctl get labels
$ fleetctl get query
$ fleetctl get options
$ fleetctl get host

I don't understand whats is the error....

### What version of `fleet` are you using (`fleet version --full`)?
2.0.2
### What operating system are you using?
Centos 7 x64
### What did you do?
Try to run a pack or queries.
### What did you expect to see?
See running the queries on the screen.

### What did you see instead?
Run the fleetctl as root. Other sentences, ext. Finally, I have the same message as a result (_### **"Upgrade live query result WebSocket: x509: certificate signed by unknown authority"**_).

![image](https://user-images.githubusercontent.com/20323736/62208159-57bd4980-b396-11e9-93b4-477843aa5e7d.png)

Thanks for help me with this issue.

Kind regards.

**Comment by zwass** [comment]
Do you have a load balancer or something between fleetctl and fleet that may be handling websockets differently?

**Comment by aCruzQ** [comment]
Hi Zwass, 
No, nothing between Fleet and fleet. The console picture is from the same server (Centos 7).

**Comment by ghigliottyc** [comment]
FWIW I also get that error too. We're specifying a custom root CA in the fleetctl config:

```
default:
    address: https://fleet.server.com
    email: email@email.com
    rootca: /path/to/cert/
    tls-skip-verify: false
    token: redacted
```

**Comment by aCruzQ** [comment]
Hi ghigliottyc,
Thanks for your help, I will try to add your configuration.
I will tell you what happens.

Kind regards.

**Comment by aCruzQ** [comment]
Hi to everybody,
I changed the configuration suggested by @ghigliottyc and the queries run; I can run live queries. Thank you so much..!

Another interesting thing is that when I run one query this show results and only run in percent that online host (in this case 5/8); the percent continuous in 62% and waiting for something; see the picture, please.

![image](https://user-images.githubusercontent.com/20323736/62457099-4ef3bb80-b77a-11e9-8b47-3cdc6a968db6.png)

Why happened this?, I need to press CTRL+ Z to stop the query (I waited for more than 10 minutes for someone and nothing).

![image](https://user-images.githubusercontent.com/20323736/62460323-ffb18900-b781-11e9-998d-e3817359c288.png)

**Comment by aCruzQ** [comment]
Hi, I found the solution.
I didn't delete the post if someone has a similar problem

Only add **--exit** to the command to finish the query when it runs with only online hosts.

$ fleetctl query --query 'select * from system_info;' --labels='All hosts' --debug --exit

Kind regards.
