### ISSUE TITLE
Some errors when the Fleet service run

### ISSUE THREAD

**Issue by aCruzQ** [kolide/fleet#2096]
Hi, from these last day I can see these logs when I see the status of Fleet service.
Are normal or what I can solve this problem.

When I run the command:

$ sudo systemctl status fleet -l

The IPs shows in the next images aren't host of fleet.

![image](https://user-images.githubusercontent.com/20323736/63019772-9ece3300-be9c-11e9-80b9-ce4f1b2c2f7d.png)

![image](https://user-images.githubusercontent.com/20323736/63019584-1485cf00-be9c-11e9-959b-3694585fd64c.png)

### What version of `fleet` are you using (`fleet version --full`)?
2.0.2
### What operating system are you using?
Centos 7 x64
### What did you do?
See that some logs no are updated

### What did you expect to see?
No errors.

### What did you see instead?
I dont know what to do.

**Comment by zwass** [comment]
These are the HTTP logs indicating that you have hosts connecting to Fleet. They do not look like they indicate any issue with Fleet.
