### ISSUE TITLE
Not able to "Fetch Fleet Certificate"

### ISSUE THREAD

**Issue by dmarcsift** [kolide/fleet#2100]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.3.0
  branch: 	master
  revision: 	bc9782e9b0c431ce8c24552861f5527fb0f4c390
  build date: 	2019-08-14T18:55:06Z
  build user: 	zwass
  go version: 	go1.12.8
### What operating system are you using?
Ubuntu 18.04.3 LTS
### What did you do?
Clicked on Fetch Fleet Certificate.
### What did you expect to see?
The certificate to be downloaded from the server.
### What did you see instead?
Nothing happened.

I am trying to set up launcher and need to get the certificate from Fleet. For context I've set up Fleet successfully using certbot. Everything is working as intended, I just can't download the certificate.

If there's a workaround where I could copy one of the pems from certbot, that would suffice. Just following the instructions on your help page and other pages I've come across the web that say to do the same thing.

**Comment by polak785** [comment]
Hello @dmarcsift 

I have the exact same issue with the same configuration. Do you know what to do to fix please ?

**Comment by zwass** [comment]
Usually this happens because the "Fleet server URL" is not specified correctly in the App Settings. This button is purely for convenience as you can download the certificate chain using your browser, or just provide osquery with the cert used to start the Fleet server.
