### ISSUE TITLE
Missing Config tab for OSQuery configuration management

### ISSUE THREAD

**Issue by stevenswager** [kolide/fleet#2101]
### What version of `fleet` are you using (`fleet version --full`)?
2.3.0

### What operating system are you using?
ubuntu 16.04

### What did you do?
https://github.com/kolide/fleet/blob/master/docs/infrastructure/fleet-on-ubuntu.md

### What did you expect to see?
Config tab in the UI to manage OSQuery configuration.

### What did you see instead?
Do not see a tab for config (see all the other tabs, but not config).

**Comment by cybersadmin** [comment]
I have the same issue, what was the solution?
