### ISSUE TITLE
Installing windows service 

### ISSUE THREAD

**Issue by iknowjason** [kolide/fleet#2107]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.2.0

### What operating system are you using?
osquery client is Windows 10 pro; Fleet server is Ubuntu 18.04

### What did you do?
Trying to install Windows service for osquery client on Windows 10 Pro.
I did:  
PS C:\Program Files\osquery> .\manage-osqueryd.ps1 -install -startupArgs C:\Program Files\osquery\osquery.flags

Then I ran:  .\manage-osqueryd.ps1 start

### What did you expect to see?
I expected to see the agent registered to Kolide server (it has already enrolled and registered).

Now when I run osqueryd.exe manually with the flags file, it does register:
PS C:\Program Files\osquery\osqueryd> .\osqueryd.exe --flagfile 'C:\Program Files\osquery\osquery.flags' --tls_dump --verbose

### What did you see instead?
So the issue doesn't appear to be with the flags file because I parsed and debugged it line by line until I can run 'osqueryd.exe' with the flags file.  Could I get a tip on why the powershell script is not installing the service so that it works when trying to point "startupargs" to the flags file?

**Comment by iknowjason** [comment]
Here is contents from osquery.flags:
--tls_hostname=host.domain.net:8080
--enroll_secret_path=C:\Program Files\osquery\enrollment-secret.txt
--tls_server_certs=C:\Program Files\osquery\certs\host.domain.net_8080.pem
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=3
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=tls
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10

**Comment by zwass** [comment]
This does not sound like an issue with Fleet. Please ask on [osquery Slack](https://osquery-slack.herokuapp.com/) for help debugging on the agent side.

**Comment by iknowjason** [comment]
Makes perfect sense.  After further research, this is a Windows service installation issue so I'm researching that further.  Thanks.

**Comment by johnsaker97** [comment]
> ### What version of `fleet` are you using (`fleet version --full`)?
> fleet - version 2.2.0
> 
> ### What operating system are you using?
> osquery client is Windows 10 pro; Fleet server is Ubuntu 18.04
> 
> ### What did you do?
> Trying to install Windows service for osquery client on Windows 10 Pro.
> I did:
> PS C:\Program Files\osquery> .\manage-osqueryd.ps1 -install -startupArgs C:\Program Files\osquery\osquery.flags
> 
> Then I ran: .\manage-osqueryd.ps1 start
> 
> ### What did you expect to see?
> I expected to see the agent registered to Kolide server (it has already enrolled and registered).
> 
> Now when I run osqueryd.exe manually with the flags file, it does register:
> PS C:\Program Files\osquery\osqueryd> .\osqueryd.exe --flagfile 'C:\Program Files\osquery\osquery.flags' --tls_dump --verbose
> 
> ### What did you see instead?
> So the issue doesn't appear to be with the flags file because I parsed and debugged it line by line until I can run 'osqueryd.exe' with the flags file. Could I get a tip on why the powershell script is not installing the service so that it works when trying to point "startupargs" to the flags file?

Hi bro,
I'm setting osquery on Window 10 for Kolide on Ubuntu. I have build Kolide on Ubuntu, it's OKE. But I have problem in setting Launcher on Window 10 add host to Kolide. Can you give me tutorial about setting Launcher on Window 10. Please help me!!
