### ISSUE TITLE
Labels does not get accurate hosts

### ISSUE THREAD

**Issue by anelshaer** [kolide/fleet#2109]
### What version of `fleet` are you using (`fleet version --full`)?

>   fleet - version 2.3.0
>   branch: 	master
>   revision: 	bc9782e9b0c431ce8c24552861f5527fb0f4c390
>   build date: 	2019-08-14T18:55:06Z
>   build user: 	zwass
>   go version: 	go1.12.8

### What operating system are you using?

> CentOS Linux release 7.6.1810 (Core)

### What did you do?
Creating a Label
`select * from system_info where hostname like 'webserver%';`
`select * from system_info where hostname not like 'webserver%';`
### What did you expect to see?
i'm expecting to see more hosts, which i'm able to see in the All Hosts.
### What did you see instead?
i'm able to see partial results.

**Comment by zwass** [comment]
Is this still an issue for you? Hosts will only "join" labels when they have executed that label query and returned results. This means it takes some time for all hosts to show up in a label as hosts will not appear until they are online, receive the label query, and return their results.
