### ISSUE TITLE
Querying or Label Online/Offline Machines (Agents)

### ISSUE THREAD

**Issue by anelshaer** [kolide/fleet#2111]
### What version of `fleet` are you using (`fleet version --full`)?
> fleet - version 2.3.0
> branch: master
> revision: bc9782e
> build date: 2019-08-14T18:55:06Z
> build user: zwass
> go version: go1.12.8

### What operating system are you using?
> CentOS Linux release 7.6.1810 (Core)

### What did you do?
Query only Against Online Machines. and Export list of offline Machines. Create Labels for Both Online or Offline. 
### What did you expect to see?
Get list of all Offline Machines(Agents). Query only online Machines and not all clients.
### What did you see instead?
only able to query all machines, and not able to get list of offline agents.

**Comment by anelshaer** [comment]
Is there any way to get a list of the offline machines so we can go further investigate that? 
i have noticed that most of the offline machines are online but have this warning
`http_client.cpp:38 SSL SHORT_READ_ERROR: http_client closing socket`

**Comment by zwass** [comment]
Queries: Live queries only hit online hosts. When you leave the page the query stops being sent to any new hosts, so never makes it to hosts that were offline while the query was running.

Offline Hosts: You could use `fleetctl get hosts` to get a list of offline hosts.
