### ISSUE TITLE
Request error: certificate verify failed

### ISSUE THREAD

**Issue by hackdefendr** [kolide/fleet#2130]
### What version of `fleet` are you using (`fleet version --full`)?

  fleet - version 2.3.0                                   
  branch:       master                                  
  revision:     bc9782e9b0c431ce8c24552861f5527fb0f4c390
  build date:   2019-08-14T18:55:06Z                    
  build user:   zwass                                   
  go version:   go1.12.8                                

### What operating system are you using?

  Ubuntu 18.04.3

### What did you do?

1. Followed the installation instructions for installing / configuring Fleet.  This part went as expected.
2. Tried both self-signed and full-signed certificates, neither are verified during OSQuery Enrollment.
3.  Error does not detail (even with verbose set) why the certificate is not verified.

### What did you expect to see?

I expected the Fleet host to enroll properly.

### What did you see instead?

ERROR:
W1104 10:44:55.307343 27248 tls_enroll.cpp:74] Failed enrollment request to https://localhost:8080/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...

Would like to see better documentation around the certificate creation steps.  Provided steps do not work.

**Comment by archanchoudhury** [comment]
You can view this- https://youtu.be/nxOdzM9QRAg
Given the demo how to resolve the cert verification error problem and to fix it. The problem lies the way we create the cert.
