### ISSUE TITLE
Use filesystem and pubsub logger plugin with Kolide?

### ISSUE THREAD

**Issue by ghigliottyc** [kolide/fleet#2131]
### What version of `fleet` are you using (`fleet version --full`)?

fleetctl - version 2.3.0
  branch: 	master
  revision: 	bc9782e9b0c431ce8c24552861f5527fb0f4c390
  build date: 	2019-08-14T18:55:21Z
  build user: 	zwass
  go version: 	go1.12.8

### What did you do?

This isn't an issue but just a general question around shipping client logs

Currently we're using the filesystem plugin + log forwarder to ship all osquery client logs. We'd like to enable the tls logger plugin to ship a subset of our client logs to Kolide using the GCP pubsub integration while keeping our current logging pipeline using the filesystem plugin as is. 

In order to achieve this we'd need [configure the fleet binary](https://github.com/kolide/fleet/blob/master/docs/infrastructure/configuring-the-fleet-binary.md#osquery_result_log_plugin) with the values `tls` and `filesystem`, set all the requisite pusub values [here](https://github.com/kolide/fleet/blob/master/docs/infrastructure/configuring-the-fleet-binary.md#pubsub) and add logger_plugin: tls,filesystem to the flags file on the subset of hosts we wants to ship logs from?

 If this is not accurate, what's the best path forward?

**Comment by zwass** [comment]
I hope you worked this out by now, but you generally have the right idea. Fleet doesn't really care where your logs go. You can have Fleet provide the appropriate configuration for logging and this can include logging to Fleet (via TLS) or any of the other logger plugins built into osquery (or shipped by you as an extension).

If you have further questions about this, please reach out on osquery Slack.
