### ISSUE TITLE
log x-forwarded-for IP

### ISSUE THREAD

**Issue by groob** [kolide/fleet#2133]
If fleet is behind a loadbalancer, the logs for `ip_addr` will display the ip of the proxy, not the remote ip of the client. 

Fleet should also log the remote IP from the x-forwarded-for field.

To accomplish this, all the log entries will need an additional line that reads `ContextKeyRequestXForwardedFor`

Example: 

https://github.com/kolide/fleet/blob/d453ca3f8f2db7c2b73fcf04f4ac85c05084be64/server/service/logging_osquery.go#L32-L49

Becomes 

	defer func(begin time.Time) {
		_ = mw.logger.Log(
			"method", "AuthenticateHost",
			"ip_addr", ctx.Value(kithttp.ContextKeyRequestRemoteAddr).(string),
			"x_for_ip_addr", ctx.Value(kithttp.ContextKeyRequestXForwardedFor).(string),
			"err", err,
			"took", time.Since(begin),
		)
	}(time.Now())

**Comment by zwass** [comment]
Closed by #2193.
