### ISSUE TITLE
fleetctl: return label result in yaml format

### ISSUE THREAD

**Issue by nyanshak** [kolide/fleet#2135]
Feature request: have `fleetctl get labels` return yaml output.

### What version of `fleet` are you using (`fleet version --full`)?

2.3.0

```fleetctl --version
fleetctl - version 2.3.0-11-ged9f890b
  branch: 	master
  revision: 	ed9f890ba02bf8946284572baae351b7b908d99d
  build date: 	2019-11-07T20:34:47Z
  build user: 	user
  go version: 	go1.13.4
```

### What operating system are you using?

Linux

### What did you do?

`fleetctl get labels`

### What did you expect to see?

Output in yaml format, similar to the documented format here: https://github.com/kolide/fleet/blob/master/docs/cli/file-format.md

```apiVersion: v1
kind: label
spec:
  name: slack_not_running
  query: >
    SELECT * from system_info
    WHERE NOT EXISTS (
      SELECT *
      FROM processes
      WHERE name LIKE "%Slack%"
    );```

### What did you see instead?

```
+--------------+----------+--------------------------------+--------------------------------+
|     NAME     | PLATFORM |          DESCRIPTION           |             QUERY              |
+--------------+----------+--------------------------------+--------------------------------+
| All Hosts    |          | All hosts which have enrolled  | select 1;                      |
|              |          | in Kolide                      |                                |
...
```

**Comment by zwass** [comment]
This is now supported via `fleetctl get label foobar` and `fleetctl get labels --yaml`.
