### ISSUE TITLE
Allow disabling ad-hoc querying panel

### ISSUE THREAD

**Issue by nyanshak** [kolide/fleet#2140]
Feature request: support disabling distributed queries through API / query panel page.

Fleet internally uses distributed querying to get info such as network interfaces. I'd like to be able to leave this enabled, but disable the distributed querying features of fleet, such that users are not able to go to the query page and run queries (or use the API).

It's possible to set `disable_distributed` to true, but then hosts won't send info that fleet uses to enrich the UI.

Also, when `disable_distributed` is set to true, the UI still lets you go to the query page, select `All Hosts` and queue up an ad-hoc query that won't ever return results. It would be better for users to remove the link from the sidebar or maybe show a warning that the feature is disabled when that is set to disabled.

**Comment by anelshaer** [comment]
I was thinking also disabling ad-hoc queries only admins can write queries, and normal users only use already created/saved queries made by admin to reduce the risk of running something that causes production issues.

**Comment by nyanshak** [comment]
I think that would be great, as well as limiting those users to being able to query certain numbers of hosts. However, I think it's a bit off-topic for this ticket, and probably belongs instead in https://github.com/kolide/fleet/issues/2077

**Comment by zwass** [comment]
This has been implemented by #2167.

**Comment by mbigras** [comment]
Does disabling live queries remove the dependency on redis?

**Comment by zwass** [comment]
Redis is also used for SSO login. You could remove Redis and you would find that most things work but `healthz` returns 500 errors and SSO login does not work.
