### ISSUE TITLE
Missing Config tab for OSQuery configuration management

### ISSUE THREAD

**Issue by cybersadmin** [kolide/fleet#2162]
Exact same issue has here: https://github.com/kolide/fleet/issues/2101

I've only got one agent enrolled in fleet, and it is NOT using the --config_path parameter, so I'm stumped.

There was no resolution in that ticket, and I've scoured the docs for anything that might suggest the cause of this.

What is the solution?

**Comment by directionless** [comment]
I don't think fleet exposes the underlying osquery configuration. Fleet itself manages that based on how fleet and the device are configured.

**Comment by cybersadmin** [comment]
@directionless not sure I follow, see screenshots here with config tab on the left navigation panel: https://github.com/kolide/fleet/blob/master/docs/dashboard/running-queries.md

My understanding is that these flags:

--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_refresh=10

Instruct osquery to get it's config from a server?

**Comment by zwass** [comment]
The osquery configuration is managed only through the `fleetctl` CLI. You can find docs about that here: https://github.com/kolide/fleet/blob/master/docs/cli/file-format.md#osquery-configuration-options.

**Comment by cybersadmin** [comment]
Has the "Config" page been deprecated?

**Comment by zwass** [comment]
Ah, yes, looks like we need to update those screenshots.

**Comment by cybersadmin** [comment]
@zwass thanks for clarifying. 

So what about scheduled queries part of the UI, does that work?

**Comment by zwass** [comment]
Yes
