### ISSUE TITLE
Duplicated hosts everytime Launcher runs

### ISSUE THREAD

**Issue by Serrvosky** [kolide/fleet#2165]
### What version of `fleet` are you using (`fleet version --full`)?
kolide/fleet:2.4.0 

### What operating system are you using?
Kubernetes v1.14

### What version of `launcher` are you using?
v0.11.5

### What did you do?
Setup up my Kolide fleet server. Then start to add hosts using Launcher.

### What did you expect to see?
1 host entry per machine

### What did you see instead?
Every time I run launcher, it makes a new entrance in hosts view, leaving the old one as offline.
As you can see in this example I have two entries for machine GL-IT-0002. And I tested with GL-ITDEV-0011 as well, that have a different OS and a different OSQuery version.

This is how I'm starting launcher for now (later it will be in a service):
`./launcher --hostname=159.65.214.148:443 --root_directory=$(mktemp -d) --enroll_secret=gR6Ymc1GZvvmPwRjPyFTGqWU1mzFgYkA --insecure`
 
![image](https://user-images.githubusercontent.com/50745107/70732842-186a1680-1d01-11ea-8f2f-5b9e3940db4b.png)

Can anyone tell me what could be happening?

Thanks

**Comment by zwass** [comment]
You need to specify `--root_directory` when running launcher. If you don't do that, a new local database will be created on each run and cause this issue.

**Comment by Serrvosky** [comment]
@zwass Thanks a lot for your help. That works
