### ISSUE TITLE
Use proxy certificate

### ISSUE THREAD

**Issue by Serrvosky** [kolide/fleet#2166]
### What version of `fleet` are you using (`fleet version --full`)?
fleet 2.4.0
### What operating system are you using?
kubernetes 1.14

Hello guys,

I want to set a Kolide scenario on kubernetes, but to use only one Load Balancer in my cloud provider, I'm using Traefik as a reverse proxy, to handle different domains.

I'm also using let's encrypt in Traefik configs to generate and manage certificates to all my sub domains, and I want to do the same to kolide, but I'm not finding the solution because every time I deploy Kolide fleet with no certificate and key mounted it don't start, and if I mount a self signed certificate, it gives an error `2019/12/19 16:41:31 http: TLS handshake error from 10.244.1.37:59248: remote error: tls: bad certificate`, 

If I expose Kolide directly using a load balancer service, it works fine (with a warning about a self signed certificate of course) but I that not the solution that I want.

I think that the problem is between Traefik and Kolide, because Traefik is providing my URL with a Let's Encrypt certificate, and Kolide pod is using another.

Can anyone help me with that?

Thanks

**Comment by zwass** [comment]
My guess is your proxy cannot validate the self-signed certificate used by Fleet. You'll need to find a way to get the proxy to trust the cert.

Alternatively -- If it's acceptable in your environment -- You could terminate TLS with the proxy and serve Fleet over HTTP on the local private network.

**Comment by kavehmz** [comment]
One way might be to mount your tls in your deployment and use them (key,crt) as fleet certs. I am doing that (fleet behind nginx-ingress) and it works fine.

**Comment by servo1x** [comment]
Hi @kavehmz, could you share your nginx-ingress config? Do you separate the https and grpc endpoints?

**Comment by Serrvosky** [comment]
Hello guys,

Thanks for your replies. 
I fixed my problem by using TCP Routers on Traefik Reverse Proxy.

Thanks a lot
