### ISSUE TITLE
Error creating new admin user

### ISSUE THREAD

**Issue by servo1x** [kolide/fleet#2169]
### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 2.4.0
  branch: 	master
  revision: 	70c6f5bd7d8a337a97f7702ee17088e74722896f
  build date: 	2019-11-12T23:19:38Z
  build user: 	zwass
  go version: 	go1.12.8

### What operating system are you using?

Linux.

### What did you do?

Setting up a new fleet instance, through the setup wizard and when clicking "finish", the request returns a 500.

```json
{"component":"service","created_by":"unauthenticated","err":"create new user: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin,\n      \tenabled,\n      \tadmin_forced_password_reset,\n      \tgravatar_url,\n' at line 7","method":"NewAdminCreatedUser","took":"251.5728ms","ts":"2019-12-30T18:28:09.586634762Z","user":"none"}
```

### What did you expect to see?

Setup wizard and user to be created successfully.

### What did you see instead?

Nothing happens because the request returns a 500.

Is Fleet not compatible with MySQL 8?

**Comment by ideologysec** [comment]
I believe it requires 5.7.x series (based on remembered conversations around MariaDB support, etc).

**Comment by servo1x** [comment]
Looks like that is the case, we switched to a MySQL 5.7 db instead.
