### ISSUE TITLE
Disable host_expiry_enabled on setup and provide cli command to run the cleanup

### ISSUE THREAD

**Issue by servo1x** [kolide/fleet#2174]
### What version of `fleet` are you using (`fleet version --full`)?
2.4.0

### What operating system are you using?
Alpine

### What did you do?
Upon setting up a new kolide instance, when connected to a database that does not provide `EVENT` access, kolide fails to initialize.

`/api/v1/setup` returns a 500 and we are unable to proceed with the setup because the host_expiry event cannot be dropped because we don't have access to it.

```json
{
  "message": "Unknown Error",
  "errors": [
    {
      "name": "base",
      "reason": "new app config: drop existing host_expiry event: Error 1044: Access denied for user 'kolide'@'%' to database 'kolide_fleet'"
    }
  ]
}
```

### What did you expect to see?

Setup to proceed and notify the user event has been disabled due to lack of permissions.

### What did you see instead?

Stuck on setup page until going into the database and editing the `app_configs` table and setting `host_expiry_enabled` to `1` (false).

For those of us who are using a managed database that does not provide access to `EVENT` or has the event scheduler disabled, it would be nice if we could instead run a fleet command to do the host cleanup and then we can schedule it with whatever mechanism we want.

**Comment by zwass** [comment]
@servo1x I put up a PR to fix the error on setup. If you are interested in a `fleetctl` command to run the cleanup, please open a new issue with a request for that feature.
