### ISSUE TITLE
remote error: tls: unknown certificate authority

### ISSUE THREAD

**Issue by hackdefendr** [kolide/fleet#2191]
### What version of `fleet` are you using (`fleet version --full`)?
  fleet - version 2.4.0
  branch:       master
  revision:     70c6f5bd7d8a337a97f7702ee17088e74722896f
  build date:   2019-11-12T23:10:49Z
  build user:   zwass
  go version:   go1.12.8
### What operating system are you using?
Redhat 7
### What did you do?
I configured fleet and my osquery agents per documentation. I have troubleshot this to death, and I cannot figure it out. Why do some agents connect and all new ones do not?
### What did you expect to see?
I expect, since all agents are using the same certificate and root authority.
### What did you see instead?
30 agents are connecting fine, All the remaining do not connect and instead my /var/log/messages is filled with TLS handshake errors.

**Comment by zwass** [comment]
Did you go through the steps in https://github.com/kolide/fleet/blob/master/docs/infrastructure/faq.md#how-do-i-fix-certificate-verify-failed-errors-from-osqueryd?

If none of that helps, you'll need to provide more information about your configuration: How is it configured, which agents are connecting, which are not, what error messages you are seeing, etc.

This may be easier to do on #kolide in osquery Slack.

**Comment by hackdefendr** [comment]
Yep I did go through that document and nothing helped.

The error message I am seeing:
```
2020/02/06 11:33:07 http: TLS handshake error from IP_ADDRESS:58914: remote error: tls: unknown certificate authority
```
I know it says unknown certificate authority, but its not.  All of my clients are using the same configuration, the same server cert, and the same root CA.  

The clients that are connecting are a mix of Redhat 7 and Ubuntu 18.04.

I don't know how to give more information than that.

**Comment by hackdefendr** [comment]
Ugh! I think we figured it out and boy is this going to be funny (to me).  My linux admin deployed the last 40 or so servers/containers using an old root CA cert. That curl command in the FAQ is what clued me in by showing me where it was reading the CAfile from.  Once I compared root certs it was clear he was using an old cert.

**Comment by zwass** [comment]
Glad you worked it out!
