### ISSUE TITLE
Problem With looking for targets option

### ISSUE THREAD

**Issue by ItsQuestionsTime** [kolide/fleet#2192]
### What version of `fleet` are you using (`fleet version --full`)?
The latest version of both the docker and the fleet

### What did you do?
I updated the fleet and now when I try to add a new query and add new targets the target bar doesn't let me search for names or ips it just lets me see the first options.
But when I reverse it to the old fleet binary it works just fine and let me search for targets.

### What did you expect to see?
To be able to search for targets by ip or hostname

### What did you see instead?
Nothing really, can't search cause the search bar ain't working.

**Comment by zwass** [comment]
Have you run `fleet prepare db`?

What do you see in the network inspector in your browser when you type into the targets box?

What do you see in the Fleet server logs?

**Comment by zwass** [comment]
Absent further details, this issue cannot be investigated. Closing.
