### ISSUE TITLE
Fleet unable to return query results for somewhat large number of hosts

### ISSUE THREAD

**Issue by h3rm1tkr4b** [kolide/fleet#2195]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.5.0
  branch: 	master
  revision: 	8e77f4369a3d49005beebe08f6a7ac453810c586
  build date: 	2020-01-26T22:02:00Z
  build user: 	zwass
  go version: 	go1.13.4

### What operating system are you using?
CentOS Linux release 7.7.1908 

### What did you do?
Ran a query on ~500 of my ~4k hosts.
Query: SELECT * FROM osquery_info
Targets: 463 CentOS systems

### What did you expect to see?
Results returned.

### What did you see instead?
About 10 results after around 5 minutes of waiting. CPU spike to ~100% on the DB, front end web UI failure. 

SETUP:
Network load balancer with two m5a.4xlarge servers behind it. 16 CPUs each. As for the DB I'm using a separate cluster with a primary and a secondary. Engine version :5.7.mysql_aurora.2.04.6, db.r5.12xlarge, vCPU: 48, RAM:384 GB. For Redis I'm using 3 cache.r5.large that each have CPUs: 2, Memory: 13.07, Network Performance: Up to 10 Gigabit

DB settings set in config yml on each server:
max_open_conns: 250
max_idle_conns: 250

Info from osquery.flags file: 
--enroll_secret_path=REDACTED
--tls_server_certs=REDACTED
--tls_hostname=REDACTED
--host_identifier=hostname
--enroll_tls_endpoint=/api/v1/osquery/enroll
--config_plugin=tls
--config_tls_endpoint=/api/v1/osquery/config
--config_tls_refresh=10
--disable_distributed=false
--distributed_plugin=tls
--distributed_interval=60
--distributed_tls_max_attempts=3
--distributed_tls_read_endpoint=/api/v1/osquery/distributed/read
--distributed_tls_write_endpoint=/api/v1/osquery/distributed/write
--logger_plugin=filesystem
--logger_tls_endpoint=/api/v1/osquery/log
--logger_tls_period=10
--logger_min_status=1

From Servers during query: 
SERVER1: sudo lsof | grep fleet | sort -u | wc -l
1310814

SERVER2: sudo lsof | grep fleet | sort -u | wc -l
1310810

![DB](https://user-images.githubusercontent.com/40723590/74255710-8013f200-4caf-11ea-8ff4-215eb4c0e004.png)
![kolide](https://user-images.githubusercontent.com/40723590/74255718-82764c00-4caf-11ea-8964-21282334e6eb.png)
![REDIS](https://user-images.githubusercontent.com/40723590/74255726-84400f80-4caf-11ea-8ae0-581b84f3d91c.png)
![servers](https://user-images.githubusercontent.com/40723590/74255762-8efaa480-4caf-11ea-89c6-e2290a397a81.png)

**Comment by h3rm1tkr4b** [comment]
I thought the image names would appear but since they haven't, the first images is obviously my DB states when the query started. The second is the kolide UI during the query. The 3rd is my REDIS states and the last is the stats from my 2 servers running kolide.

**Comment by zwass** [comment]
Are these systems being targeted by a label? This is a scale that Fleet would typically handle so I'd be interested in understanding better what might be going on.

**Comment by h3rm1tkr4b** [comment]
They are being targeted by one of the default labels (CentOS Linux).

**Comment by h3rm1tkr4b** [comment]
Anyone have time to look into this? Seems to be a bug.
