### ISSUE TITLE
kolide fleet can not query file_events

### ISSUE THREAD

**Issue by topsekadmin** [kolide/fleet#2198]
Dear all:
    i use fleet manager osquey client, when i query file_events table, no display,show below:
<img width="538" alt="WX20200219-101504@2x" src="https://user-images.githubusercontent.com/59950798/74795369-b8937b80-5300-11ea-8c45-6a1d3d4bbfd8.png">
   but i run osqueryi command , use select * from file_events;  show below:
![image](https://user-images.githubusercontent.com/59950798/74795244-63f00080-5300-11ea-8ce9-89b1273b8d81.png)
   please help me,thank you

**Comment by zwass** [comment]
This is a configuration issue.

`osqueryi` and `osqueryd` are likely running with different configurations. The local database where events are stored is not shared between them, so seeing the events in `osqueryi` does not tell you that `osqueryd` is configured appropriately.
