### ISSUE TITLE
Fleet unable to return all query results for ad hoc queries

### ISSUE THREAD

**Issue by alejandroortuno** [kolide/fleet#2199]
Following on this issue as it was closed without a final resolution: 

#1980 

Kolide server is managing around 700 hosts.

### What version of `fleet` are you using (`fleet version --full`)?

2.5.0

### What operating system are you using?

Fleet is running on containers on top of AWS ECS Fargate. Also using AWS RDS and AWS Cache Redis. Utilization of RDS / Redis seems normal and there are no specific spikes associated with the ad hoc query.

### What did you do?

Running an ad-hoc query results in a high number of error logs as follows:

`{
    "component": "service",
    "err": "failed to ingest result: recording execution: insert distributed campaign target: Error 1062: Duplicate entry 'XXXXXXX-XXX' for key 'idx_dqe_unique_host_dqc_id'",
    "ip_addr": "X.X.X.X:X",
    "method": "SubmitDistributedQueryResults",
    "took": "4.671645ms",
    "ts": "2020-02-27T15:34:33.922783808Z"
}`

**Comment by zwass** [comment]
Do you happen to have a low value set for the `distributed_interval`? You are at a scale that has not typically caused problems with the distributed query system, and it is not typical to see this duplicate entry error.

**Comment by alejandroortuno** [comment]
@zwass we have setup to a value of 3:

`distributed_interval=3`

Do you think this could be causing the errors?

**Comment by zwass** [comment]
That is quite a low interval. Can you try 10? This usually feels pretty real time without causing any issues.

**Comment by alejandroortuno** [comment]
@zwass, so that `distributed_interval=3` is the flag we use when deploying osquery daemon on our EC2 instances across the org.

Now exporting the options configuration in yaml, using fleetctl, I get the following value:

`distributed_interval: 10`

Is this flag controlled also by the fleet server on the osquery daemons? Thanks for your help.

**Comment by zwass** [comment]
If you use `--config_plugin=tls` (so that you can manage configs and packs from Fleet) then the `distributed_interval` value set in Fleet will be used by the hosts.

**Comment by alejandroortuno** [comment]
thanks @zwass that makes sense and that is included in our osquery daemons across the fleet which means then we have distributed_interval = 10 as stated by Kolide.

Is there any other potential changer we could do to improve on this situation?
