### ISSUE TITLE
Unable to connect to fleet

### ISSUE THREAD

**Issue by noale1** [kolide/fleet#2205]
### Fleet version 
2.4.0

### What did you do?

I am trying to reconfigure the check-in time for my Osquery clients. So I tried using fleetctl and fleet serve

### What did you expect to see?

I expected to login to fleetctl using my login credentials.

### What did you see instead?

When I tried to login to fleetctl I get a connection timed out error.
So I tried to login through fleet serve, the default database, username and password is “kolide”. Obviously my database has a different name, so when I try to change the database name and login credentials I can’t login in the first place to change the credentials. 
So I’m kind of in a paradox situation. Or maybe I’m missing something... either way I would really appreciate it if someone could try to help me!

**Comment by zwass** [comment]
I'm having trouble understanding what you are trying to do and the steps you have tried. Can you please join #kolide in osquery Slack and ask for help there?
