### ISSUE TITLE
Proposal: Remove network_interfaces from host details

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#2207]
### Motivation

Fleet currently stores all the network interfaces for each host. This has two major performance impacts:

1. MySQL transactions are used to store and update the network interfaces, causing high load on the MySQL server and the deadlock errors observed in #845.
2. The Fleet server sends a large JSON blob containing all of the network interfaces for each host to API clients (like the frontend). This causes issues for the server and client as the responses are so large (https://github.com/kolide/fleet/issues/2204).

### Proposal

I propose to cease storing the full network interface information, and instead store only the primary IP and MAC address (which is the only information displayed in the UI). This should provide very good performance improvements on both the backend and frontend.

**If you use the network_interfaces information provided by the API, please comment below with more information about your use-case so that we can understand the impact this change may have.**

**Comment by avcarrillo** [comment]
I support this request. I have 15k systems in my fleet, and the network interfaces table is causing major performance issues

**Comment by zwass** [comment]
An informal poll in #kolide revealed 4 users that do not use this data, with one user who does. I've asked that user to comment here with further details.

**Comment by 1ihor1** [comment]
Actually, "network_interfaces" information is quite helpful for us when kolide is used by a SIEM/SOAR system as a source for enrichment. Let's say there is something suspicious happened on a host and we would like a SIEM/SOAR system automatically runs a distributed query via kolide API on the host. The SIEM/SOAR system can know an ip or a hostname where the query has to be executed, but it doesn't know its internal host id in kolide, which is required to run the query using kolide API. That where "network_interfaces" information comes in handy - it is used to find the host id in kolide based on its hostname or ip address. At the moment we don't know any other way how it can be done.

**Comment by avcarrillo** [comment]
1ihor1, is the network information needed in the UI/API? Can't you run a DB query to get this information?

The UI/API only returns 1 interface, but the DB contains ALL interfaces for each client and is causing performance degradation

**Comment by zwass** [comment]
@1ihor1 I'm not sure that the proposed change would actually cause problems for your use case.

First, the `hostname` field will be unaffected. Hostname is not associated with network interfaces.

Second, Fleet would continue to return the information about the "primary" IP and MAC address. These are the network details displayed on the host dashboard. The IP provided there is the most active (in terms of network traffic) interface that is bound to a non-loopback, non-link-local, address. In most cases this seems to be the IP that folks are interested in.

@avcarrillo You are correct that the UI only shows one interface, but the API does return the full list of network interfaces. As you know, this is part of the problem with large API responses.

**Comment by defensivedepth** [comment]
@zwass The problem comes into play when you have a client connected to multiple networks (WiFi + hardwired etc ) - The primary IP may not be the actual IP you are wanting in this use case.

**Comment by 1ihor1** [comment]
@avcarrillo  If I understand the proposal correctly, the full network interface information will not be available in the DB as well. 
I agree that for the most cases full "network_interfaces" information may be redundant and the optimization proposal is reasonable. But it would be good to keep a possibility to find a host based on its IP address, and unfortunately the primary IP address is not always that helpful (e.g. our remote users who connect via VPN not always can be found based on the primary IP). Also it probably would be good not to use a direct access to the DB for communication with kolide. 

@zwass Yes, you're right about "hostname", I've checked our code for integration, we use "network_interfaces" information for searches based on IP address. As I mentioned before, unfortunately the primary IP is not enough in some cases.

**Comment by 1ihor1** [comment]
Would it be possible to separate full "network_interfaces" information from host details, but still keep it? Let's say with another collection / update frequency

**Comment by billcobbler** [comment]
> Second, Fleet would continue to return the information about the "primary" IP and MAC address. These are the network details displayed on the host dashboard. The IP provided there is the most active (in terms of network traffic) interface that is bound to a non-loopback, non-link-local, address. In most cases this seems to be the IP that folks are interested in.

One compromise might be to filter the loopback/link-local interfaces.

**Comment by rfizzle** [comment]
Any update here? As of now, Kolide UI is completely unusable for my 20k hosts.

**Comment by zwass** [comment]
Update: If you rely on full network interface details from the Fleet API, please prepare to migrate to the "additional" query capability introduced in https://github.com/kolide/fleet/pull/2236.

I worked with a client to shore up Fleet perf to well over 100k hosts and we are working on getting those changes released to the public. That transition will drop the current network_interfaces implementation.

**Comment by defensivedepth** [comment]
@zwass would be really helpful to have a blog post / something that lays out what checkin times are, hardware for mysql + web UI etc for that implementation

**Comment by yunzheng** [comment]
Would also love to hear what has been changed and tweaked to make Fleet to be usable with 100k hosts. A small recap here would already help out people with a large fleet.
 
I'm currently having a fleet of around 20k hosts (and growing) and MySQL seems to be the bottle neck in regards of queries waiting for each other or not finishing.

**Comment by johnkeates** [comment]
I'm using this data (for host identity machine with other data sources that only supply a MAC address), but as already commented and mentioned this can be done using a separate query just fine.
