### ISSUE TITLE
Enroll agents using client based TLS certificates

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#2208]
Hello, I'm interested in enrolling hosts using TLS client certificates. https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md directed me to file an issue. I also noticed that #1120 is still open. Is it in fact possible to enroll osquery agents via client based TLS certificates? What would I need to do for that?

**Comment by zwass** [comment]
As of now, there's no support for TLS client auth in Fleet itself. I'm happy to review a PR, or work with an organization on a consulting basis to implement this feature.

I think you should be able to front Fleet with a proxy that does the client auth.

**Comment by directionless** [comment]
This is a dupe of #1120, isn't it?

**Comment by zwass** [comment]
Yes, closing this in favor of #1120. TLS client auth is still something that we would like to implement someday.
