### ISSUE TITLE
Enrolling local server into Fleet

### ISSUE THREAD

**Issue by Asarewin** [kolide/fleet#2209]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.5.0
  branch: 	master
  revision: 	8e77f4369a3d49005beebe08f6a7ac453810c586
  build date: 	2020-01-26T22:02:00Z
  build user: 	zwass
  go version: 	go1.13.4

### What operating system are you using?

Ubuntu 16.04 LTS

### What did you do?
Hello and thanks in advance for any help concerning my issue,

I followed the setup instructions provided to setup a osquery/Fleet server, everything went smoothly until i ran into an issue when enrolling my Fleet/Osquery server as a Fleet host (hope this part is clear) in order to do that i followed the Kolide OsQuery launcher part of this link : https://github.com/kolide/fleet/blob/master/docs/infrastructure/adding-hosts-to-fleet.md

so i typed this command : 

./build/launcher \
  --hostname=localhost:443 \
  --root_directory=$(mktemp -d) \
  --enroll_secret=MY_ENROLL_SECRET

This successfully enrolled my server as a Fleet host and i was able to run querys on it locally (Great !)

### What did you expect to see?

When i rebooted my server i expected to see the local server "coming back up" after a while and being able to query it again but to no avail

### What did you see instead?

The host stays in "offline" mode and when i tried to enroll it again, instead of the host coming back up again i get a duplicate with the same informations but this one i'm able to query.

### My question : 

Regarding this issue, would using the package-builder help or should i run the command as a service (which i guess would make a duplicate each time I reboot the server)
I read the instructions multiple times but i still don't grasp the way im supposed to make it "persistant" as in working automatically each time i reboot this server or LAN hosts i would add later on in my tests.

**Comment by zwass** [comment]
In order to prevent duplicates, you need to set a consistent directory for `--root_directory`. Right now your command is creating a new temp directory each time it runs.

In order to get the machine to come back online when it restarts, you need to run osqueryd/Launcher as a service. package-builder can help get it installed as a service.

If you have further questions, please join #kolide on osquery Slack.
