### ISSUE TITLE
fleet as a service doesn't want to start

### ISSUE THREAD

**Issue by dgrosse-eyeo** [kolide/fleet#2218]
Hey,

I wanted to create a fleet service on systemd on an Ubuntu 19.10 system.
However I am able to start the process manually, but when I start the service unit, it always gives me following error:

_mysql="could not connect to db: Error 1045: Access denied for user 'kolide'@'localhost' (using password: YES), sleeping 0s"_

My unit file looks like:

[Unit]
Description=Kolide Fleet
After=network.target

[Service]
LimitNOFILE=8192
ExecStart=/usr/bin/fleet serve
        --mysql_address=127.0.0.1:3306
        --mysql_database=kolide
        --mysql_username=kolide
        --mysql_password=mypassword
        --redis_address=127.0.0.1:6379
        --server_cert=/tmp/server.cert
        --server_key=/tmp/server.key
        --auth_jwt_key=randomauthkey

[Install]
WantedBy=multi-user.target

Any ideas?
Thanks in advance.

**Comment by directionless** [comment]
> mysql="could not connect to db: Error 1045: Access denied for user 'kolide'@'localhost' (using password: YES), sleeping 0s"

seems pretty clear. mysql is rejecting the connection. Check your mysql permissions. It's been years since I used mysql, but if I remember correctly `localhost` is sometimes treated as magic and only grants permissions to unix socket connections, and you need to grant to 127.0.0.1 explicitly

**Comment by zwass** [comment]
This looks like a configuration issue.
