### ISSUE TITLE
Not able to add host in fleet UI

### ISSUE THREAD

**Issue by archanchoudhury** [kolide/fleet#2220]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.6.0
  branch: 	master
  revision: 	d3849d8fe1ea841d34a19e5cc06bfe62fc8dfd2d
  build date: 	2020-03-24T17:27:31Z
  build user: 	zwass
  go version: 	go1.13.4
### What operating system are you using? 
Ubuntu16.04 in AWS

### What did you do? 
Installed Fleet and ran it as backgound and it is working properly. I am able to see UI for Fleet, but I am not able to add host. 

### What did you expect to see? 
After running the commands, it should start the osqueryd and should add the host in the fleet UI

### What did you see instead? 
It is throwing an errror- "osqueryd initialize failed: osqueryd (5616) is already runninng" I have stopped the service and tried again, but the issue is same. I have downloaded the secret from UI and using it plus, I have downloaded the TLS certificate from the UI browser and using it as specified in the process. Kindly help me. I am ready for a remote session/live discussion to resolve this issue.
![Sanp1](https://user-images.githubusercontent.com/51078911/78776608-bfac4100-79b5-11ea-9a48-fe4543a9ec73.JPG)

**Comment by archanchoudhury** [comment]
Ok, So I have identified the process was running at backend. And due to that it was throwing me the above error.
But The actual problem is, osqueryd is not able to communicate with fleet server and throwing the below error... 
![image](https://user-images.githubusercontent.com/51078911/78797954-07db5b80-79d6-11ea-8fff-5ddfebe9a48c.png)
Can you please help me to identify what is causing this? I also had issues with downloading the Server Certificate since FETCH FLEET CERTIFICATE is not doing anything.

**Comment by archanchoudhury** [comment]
After a lot of efforts, I was able to download the certificate, but now receiving a certificate error. 
![image](https://user-images.githubusercontent.com/51078911/78802617-a9b17700-79db-11ea-9c59-b10d0c9a90fe.png)

**Comment by moosa-aslam** [comment]
I am also facing same issue any leads will be helpful

**Comment by archanchoudhury** [comment]
Didn't receive any recommendations till now. Tried all option specified in the help section and in other tickets.

**Comment by archanchoudhury** [comment]
The problem has been solved with a workaround. We can see the installation demo here-
https://www.youtube.com/watch?v=XC7zfQ-SmqQ

Pretty interesting..
I followed the steps, and it worked for me. :)

**Comment by archanchoudhury** [comment]
Another one which replicates the process without using launcher as mentioned in the process.- https://youtu.be/nxOdzM9QRAg
This demo shows how to resolve the certificate error problem
