### ISSUE TITLE
Impact of redis clustering (and potential consistency issues)

### ISSUE THREAD

**Issue by bored-engineer** [kolide/fleet#2221]
I didn't see any commentary in the docs about the impact of [inconsistency](https://redis.io/topics/cluster-tutorial) in the underlying redis cache:
> Redis Cluster is not able to guarantee strong consistency. In practical terms this means that under certain conditions it is possible that Redis Cluster will lose writes that were acknowledged by the system to the client.

What would the impact be to fleet of consistency issues (assuming they are short-lived)?

**Comment by zwass** [comment]
Interesting question.

Have you seen your Redis server be overwhelmed by traffic from Fleet?

Currently, there are two features in which this could manifest:

1) SSO login: Fleet stores SSO request metadata in Redis while the user is being redirected through the SSO flow. I think the worst result here would be that the user would have to retry login.

2) Live queries: All live query results are pushed through the Redis pubsub system. Any publish write that is dropped by Redis will not make it to the client as a result. If the result eventually makes it through Redis, it should make it to the client.

**Comment by zwass** [comment]
I'm going to close this issue as I don't think there is anything else actionable here.
