### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by moosa-aslam** [kolide/fleet#2234]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.6.0

### What operating system are you using?
Ubuntu 16.04
### What did you do?
Connecting osqeuryd with fleet, both fleet and osquery are on same machine followed this guide
https://github.com/kolide/fleet/blob/master/docs/infrastructure/README.md

sudo /usr/bin/osqueryd \
  --enroll_secret_path=/var/osquery/enroll_secret \
  --tls_server_certs=/var/osquery/server.pem   **(this file is downloaded from web page of fleet)**
  --tls_hostname=192.168.1.195:8080 \
  --host_identifier=hostname \
  --enroll_tls_endpoint=/api/v1/osquery/enroll \
  --config_plugin=tls \
  --config_tls_endpoint=/api/v1/osquery/config \
  --config_refresh=10 \
  --disable_distributed=false \
  --distributed_plugin=tls \
  --distributed_interval=3 \
  --distributed_tls_max_attempts=3 \
  --distributed_tls_read_endpoint=/api/v1/osquery/distributed/read \
  --distributed_tls_write_endpoint=/api/v1/osquery/distributed/write \
  --logger_plugin=tls \
  --logger_tls_endpoint=/api/v1/osquery/log \
  --logger_tls_period=10
### What did you expect to see?
N/A
### What did you see instead?
My Client Window
![1](https://user-images.githubusercontent.com/39161743/80802199-20e7be80-8bc8-11ea-8317-fc5852f18c3b.PNG)
My Server Window
![2](https://user-images.githubusercontent.com/39161743/80802202-247b4580-8bc8-11ea-9758-03b7216967d5.PNG)

**Comment by moosa-aslam** [comment]
Results from 
curl -v -X POST https://kolideserver:port/api/v1/osquery/enroll

![Capture](https://user-images.githubusercontent.com/39161743/80801993-72dc1480-8bc7-11ea-82e1-597abf1d79dd.PNG)

Resutls From
osqueryd --verbose --tls_dump
![3](https://user-images.githubusercontent.com/39161743/80802416-ac614f80-8bc8-11ea-9cdd-404248de92d1.PNG)

**Comment by zwass** [comment]
Please see https://github.com/kolide/fleet/blob/master/docs/infrastructure/faq.md#why-arent-my-osquery-agents-connecting-to-fleet and use #kolide in the osquery Slack for troubleshooting.
