### ISSUE TITLE
local error: tls: bad record MAC

### ISSUE THREAD

**Issue by arimb00r** [kolide/fleet#2235]
I have osquery 4.3.0 on Windows 2012 server and kolide 2.6.0

The osquery  agent from linux is working fine with kolide however when trying to integrate with Windows osquery with kolide then getting the following err

http: TLS handshake error from 10.10.10.1:66566 local error: tls: bad record MAC

Osquery Client on Windows
==================
Windows 2012 server 

Kolide Fleet server 
================
Centos 7.7

**Comment by zwass** [comment]
Please see https://github.com/kolide/fleet/blob/master/docs/infrastructure/faq.md#why-arent-my-osquery-agents-connecting-to-fleet and use #kolide in the osquery Slack for troubleshooting.

**Comment by catscrdl** [comment]
@zwass I've seen this issue pop up a few times in the #kolide Slack channel without an answer. I figured out that it's likely due to people accepting the defaults when generating fleets certificates using openssl. I'd recommend adding the following to Common problems in the infrastructure FAQ.

```- `bad record MAC`: When generating your certificate for your Fleet server, ensure you set the hostname to the FQDN or the IP of the server. This error is common when setting up Fleet servers and accepting defaults when generating certificates using `openssl`.```
