### ISSUE TITLE
Kolide Fleet to Redis SSL/TLS connection option

### ISSUE THREAD

**Issue by asterisk800** [kolide/fleet#2247]
Is there an SSL/TLS option for connecting Kolide Fleet to a Redis instance? 
I am trying to configure Kolide Fleet to use an Azure Cache for Redis instance that has only an SSL connection option only. 

### What version of `fleet` are you using (`fleet version --full`)?

fleet - version 2.6.0
  branch: 	master
  revision: 	d3849d8fe1ea841d34a19e5cc06bfe62fc8dfd2d
  build date: 	2020-03-24T17:27:31Z
  build user: 	zwass
  go version: 	go1.13.4

### What operating system are you using?

Red Hat Enterprise Linux 7

### What did you do?

Configure fleet to use an Azure Cache for Redis instance that has only an SSL connection option only. 

### What did you expect to see?
Live query result

### What did you see instead?

Live Queue does not work, seeing the below error instead.

Jun 23 14:15:44 xxxx.xxx.xxx fleet[109099]: {"component":"service","err":"reading from redis: read tcp xx.xx.xxx.xxx:36706-\u003exx.xx.xxx.xxx:6380: read: connection reset by peer","method":"NewDistributedQueryCampaign","numHosts":0,"sql":"SELECT * FROM osquery_info","took":"1m45.777923261s","ts":"2020-06-23T21:15:44.110580311Z","user":"xxxxxxx"}

**Comment by asterisk800** [comment]
Based on [Configuring The Fleet Binary](https://github.com/kolide/fleet/blob/master/docs/infrastructure/configuring-the-fleet-binary.md#redis), only the redis_address and redis_password option exist.

**Comment by zwass** [comment]
There is no support for this currently. I don't think it would be hard to implement. The Redis library we use seems to [support it](https://github.com/gomodule/redigo/pull/186).

I'll be happy to review a PR.

**Comment by asterisk800** [comment]
@zwass When I try to build rpm and Debian packages using `make package` after making an update to `server/pubsub/redis_query_results.go`, I am getting `make: *** No rule to make target 'package'.  Stop.`
What is the recommended step for building fleet?

**Comment by zwass** [comment]
@asterisk800 there is no `make package`. Please check out https://github.com/kolide/fleet/blob/master/docs/development/building-the-code.md for build documentation.

**Comment by asterisk800** [comment]
Thank you! For now, I end up using [stunnel](https://www.stunnel.org) to encrypt the connection between fleet and the Redis cache instance.
