### ISSUE TITLE
Execute query by api. 

### ISSUE THREAD

**Issue by pzafar1974** [kolide/fleet#2248]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 2.5.0
  branch: 	master
  revision: 	8e77f4369a3d49005beebe08f6a7ac453810c586
  build date: 	2020-01-26T22:02:00Z
  build user: 	zwass
  go version: 	go1.13.4

### What operating system are you using?
RHEL 7
### What did you do?
n/a
### What did you expect to see?
I want to see the result of an executed query

### What did you see instead?
n/a

**Comment by zpravaiz** [comment]
fleet - version 2.5.0
  branch: 	master
  revision: 	8e77f4369a3d49005beebe08f6a7ac453810c586
  build date: 	2020-01-26T22:02:00Z
  build user: 	zwass
  go version: 	go1.13.4

RHEL 7

I want to see the result of an executed query

**Comment by zwass** [comment]
The best way to understand how to do this is to look at how the web and `fleetctl` UIs handle it. Use your network inspector in the browser to see the web UI and check out the code used by fleetctl here: https://github.com/kolide/fleet/blob/master/server/service/client_live_query.go#L62
