### ISSUE TITLE
Scheduled queries from my packs are not set for new servers. Need to manually update packs.

### ISSUE THREAD

**Issue by macEar** [kolide/fleet#2260]
### What version of `fleet` are you using (`fleet version --full`)? 

Docker image: kolide/fleet:2.6.0

### What did you do?

osqueryd is being installed on new servers. After installation I can see those servers in Kolide Fleet, I can issue ad-hoc queries agaist them, it works. I have several packs targeted to `All Hosts`. When I run query agaist `osquery_schedule` table on those new servers, empty results are returned. To make it work, I need to manaully update packs.

### What did you expect to see?

Scheduled queiries from packs are set on new servers where osquery was installed. Not to manually update packs.

### What did you see instead?

No scheduled queiries on new servers for long time (week and more). Pack refresh interval in my settings is 3600.

There is related issue: https://github.com/osquery/osquery/issues/6466

**Comment by macEar** [comment]
I add some additional information on this problem below. Why that happened, is there any ideas?

We have several enabled  packs targeted to `All Hosts`, but nevetheless on some hosts there aren't any scheduled queries. 

------------

```sql
select * from os_version
```

|host_hostname|build                     |codename|major|minor|name|patch                                  |platform|platform_like|version                             |
|-------------|--------------------------|--------|-----|-----|----|---------------------------------------|--------|-------------|------------------------------------|
|test.local   |                          |        |7    |8    |CentOS Linux|2003                                   |rhel    |rhel         |CentOS Linux release 7.8.2003 (Core)|

-----------------------

```sql
select * from osquery_info
```

|host_hostname|build_distro              |build_platform|config_hash|config_valid|extensions|instance_id|pid|platform_mask|start_time|uuid            |version            |watcher|
|-------------|--------------------------|--------------|-----------|------------|----------|-----------|---|-------------|----------|----------------|-------------------|-------|
|test.local   |centos7                   |1             |aa0a230515eb44660678145fc628da30a2fb75d9|1           |active    |d184900f-534f-4e25-9279-3503bd5f60cd|22221|9            |1595446207|d79b2242-23d1-9722-e726-eda626340677|4.2.0              |22215  |

----------------------

```
[root@kolide-server prod]# docker exec -it kolide-fleet fleetctl query --hosts "test.local" --query "select * from osquery_schedule" --timeout 120s
{"host":"test.local","rows":[]}
 100% responded (100% online) | 1/1 targeted hosts (1/1 online)
```

------------------

```sql
select * from uptime
```

|host_hostname|days                      |hours|minutes|seconds|total_seconds|
|-------------|--------------------------|-----|-------|-------|-------------|
|test.local   |7                         |23   |28     |14     |689294       |

--------------------

```sql
select * from osquery_flags
```

Returned result I wanted to attached to this comment as it is large but I got `we can't process that file` error. So I did leave it here below:

|host_hostname|default_value             |description|name|shell_only|type|value                                  |
|-------------|--------------------------|-----------|----|----------|----|---------------------------------------|
|test.local   |4                         |Seconds to wait for a graceful shutdown|alarm_timeout|0         |uint64|4                                      |
|test.local   |false                     |Allow unsafe executable permissions|allow_unsafe|0         |bool|false                                  |
|test.local   |false                     |Allow the audit publisher to change auditing configuration|audit_allow_config|0         |bool|true                                   |
|test.local   |false                     |Allow the audit publisher to install file event monitoring rules|audit_allow_fim_events|0         |bool|false                                  |
|test.local   |false                     |Allow the audit publisher to install process event monitoring rules to capture fork/vfork/clone system calls|audit_allow_fork_process_events|0         |bool|false                                  |
|test.local   |true                      |Allow the audit publisher to install process event monitoring rules|audit_allow_process_events|0         |bool|true                                   |
|test.local   |false                     |Allow the audit publisher to process audit events|audit_allow_selinux_events|0         |bool|false                                  |
|test.local   |false                     |Allow the audit publisher to install socket-related rules|audit_allow_sockets|0         |bool|false                                  |
|test.local   |false                     |Allow socket events to collect domain sockets|audit_allow_unix|0         |bool|false                                  |
|test.local   |true                      |Allow the audit publisher to install user events-related rules|audit_allow_user_events|0         |bool|false                                  |
|test.local   |4096                      |The audit backlog limit|audit_backlog_limit|0         |int32|4096                                   |
|test.local   |0                         |The audit backlog wait time|audit_backlog_wait_time|0         |int32|0                                      |
|test.local   |false                     |Debug Linux audit messages|audit_debug|0         |bool|false                                  |
|test.local   |false                     |Show debug messages for the FIM table|audit_fim_debug|0         |bool|false                                  |
|test.local   |false                     |Also show file accesses (not just writes)|audit_fim_show_accesses|0         |bool|false                                  |
|test.local   |false                     |Configure the audit subsystem from scratch|audit_force_reconfigure|0         |bool|false                                  |
|test.local   |false                     |Always uninstall all rules, regardless of whether they were already installed or not|audit_force_unconfigure|0         |bool|false                                  |
|test.local   |true                      |Attempt to retain control of audit|audit_persist|0         |bool|true                                   |
|test.local   |false                     |Allow the audit publisher to show partial file events|audit_show_partial_fim_events|0         |bool|false                                  |
|test.local   |false                     |Shows warnings about untracked processes (started before osquery)|audit_show_untracked_res_warnings|0         |bool|false                                  |
|test.local   |/usr/share/osquery/lenses |Directory that contains augeas lenses files|augeas_lenses|0         |string|/usr/share/osquery/lenses              |
|test.local   |                          |AWS access key ID|aws_access_key_id|0         |string|                                       |
|test.local   |false                     |Enable proxying of HTTP/HTTPS requests in AWS client config|aws_enable_proxy|0         |bool|false                                  |
|test.local   |10                        |Seconds between flushing logs to Firehose (default 10)|aws_firehose_period|0         |uint64|10                                     |
|test.local   |                          |Name of Firehose stream for logging|aws_firehose_stream|0         |string|                                       |
|test.local   |10                        |Seconds between flushing logs to Kinesis (default 10)|aws_kinesis_period|0         |uint64|10                                     |
|test.local   |false                     |Enable random kinesis partition keys|aws_kinesis_random_partition_key|0         |bool|false                                  |
|test.local   |                          |Name of Kinesis stream for logging|aws_kinesis_stream|0         |string|                                       |
|test.local   |                          |AWS profile for authentication and region configuration|aws_profile_name|0         |string|                                       |
|test.local   |                          |Proxy host for use in AWS client config|aws_proxy_host|0         |string|                                       |
|test.local   |                          |Proxy password for use in AWS client config|aws_proxy_password|0         |string|                                       |
|test.local   |0                         |Proxy port for use in AWS client config|aws_proxy_port|0         |uint32|0                                      |
|test.local   |https                     |Proxy HTTP scheme for use in AWS client config (http or https, default https)|aws_proxy_scheme|0         |string|https                                  |
|test.local   |                          |Proxy username for use in AWS client config|aws_proxy_username|0         |string|                                       |
|test.local   |                          |AWS region |aws_region|0         |string|                                       |
|test.local   |                          |AWS secret access key|aws_secret_access_key|0         |string|                                       |
|test.local   |                          |AWS STS session token|aws_session_token|0         |string|                                       |
|test.local   |                          |AWS STS ARN role|aws_sts_arn_role|0         |string|                                       |
|test.local   |                          |AWS STS region|aws_sts_region|0         |string|                                       |
|test.local   |default                   |AWS STS session name|aws_sts_session_name|0         |string|default                                |
|test.local   |3600                      |AWS STS assume role credential validity in seconds (default 3600)|aws_sts_timeout|0         |uint64|3600                                   |
|test.local   |1000000                   |Maximum number of logs in buffered output plugins (0 = unlimited)|buffered_log_max|0         |uint64|1000000                                |
|test.local   |8192                      |Size of blocks used for POSTing data back to remote endpoints|carver_block_size|0         |uint32|8192                                   |
|test.local   |false                     |Compress archives using zstd prior to upload (default false)|carver_compression|0         |bool|false                                  |
|test.local   |                          |TLS/HTTPS endpoint that receives carved content after session creation|carver_continue_endpoint|0         |string|                                       |
|test.local   |true                      |Disable the osquery file carver function (default true)|carver_disable_function|0         |bool|true                                   |
|test.local   |                          |TLS/HTTPS init endpoint for forensic carver|carver_start_endpoint|0         |string|                                       |
|test.local   |300                       |Interval to wait if reading a configuration fails|config_accelerated_refresh|0         |uint64|300                                    |
|test.local   |false                     |Check the format of an osquery config and exit|config_check|0         |bool|false                                  |
|test.local   |false                     |Dump the contents of the configuration, then exit|config_dump|0         |bool|false                                  |
|test.local   |false                     |Backup config and use it when refresh fails|config_enable_backup|0         |bool|false                                  |
|test.local   |/etc/osquery/osquery.conf |Path to JSON config file|config_path|0         |string|/etc/osquery/osquery.conf              |
|test.local   |filesystem                |Config plugin name|config_plugin|0         |string|tls                                    |
|test.local   |0                         |Optional interval in seconds to re-read configuration|config_refresh|0         |uint64|180                                    |
|test.local   |                          |TLS/HTTPS endpoint for config retrieval|config_tls_endpoint|0         |string|/api/v1/osquery/config                 |
|test.local   |3                         |Number of attempts to retry a TLS config request|config_tls_max_attempts|0         |uint64|3                                      |
|test.local   |false                     |Set output mode to 'csv'|csv |1         |bool|false                                  |
|test.local   |false                     |Attempt to daemonize (POSIX only)|daemonize|0         |bool|false                                  |
|test.local   |false                     |Dump the contents of the backing store|database_dump|0         |bool|false                                  |
|test.local   |/var/osquery/osquery.db   |If using a disk-based backing store, specify a path|database_path|0         |string|/var/osquery/osquery.db                |
|test.local   |false                     |Add decorators as top level JSON objects|decorations_top_level|0         |bool|false                                  |
|test.local   |true                      |Disable receiving events from the audit subsystem|disable_audit|0         |bool|false                                  |
|test.local   |false                     |Disable scheduled query caching|disable_caching|0         |bool|false                                  |
|test.local   |true                      |Disable the osquery file carver (default true)|disable_carver|0         |bool|true                                   |
|test.local   |false                     |Disable the persistent RocksDB storage|disable_database|0         |bool|false                                  |
|test.local   |false                     |Disable log result decoration|disable_decorators|0         |bool|false                                  |
|test.local   |true                      |Disable distributed queries (default true)|disable_distributed|0         |bool|false                                  |
|test.local   |false                     |Disable enrollment functions on related config/logger plugins|disable_enrollment|0         |bool|false                                  |
|test.local   |false                     |Disable osquery publish/subscribe system|disable_events|0         |bool|false                                  |
|test.local   |false                     |Disable extension API|disable_extensions|0         |bool|false                                  |
|test.local   |true                      |Disable atime/mtime preservation|disable_forensic|0         |bool|true                                   |
|test.local   |false                     |Cache calculated file hashes, re-calculate only if inode times change|disable_hash_cache|0         |bool|false                                  |
|test.local   |false                     |Disable ERROR/INFO logging|disable_logging|0         |bool|false                                  |
|test.local   |false                     |Disable physical memory reads|disable_memory|0         |bool|false                                  |
|test.local   |false                     |Disable re-enrollment attempts if related plugins return invalid|disable_reenrollment|0         |bool|false                                  |
|test.local   |                          |Comma-delimited list of table names to be disabled|disable_tables|0         |string|                                       |
|test.local   |false                     |Disable userland watchdog process|disable_watchdog|0         |bool|true                                   |
|test.local   |60                        |Seconds between polling for new queries (default 60)|distributed_interval|0         |uint64|60                                     |
|test.local   |tls                       |Distributed plugin name|distributed_plugin|0         |string|tls                                    |
|test.local   |3                         |Number of times to attempt a request|distributed_tls_max_attempts|0         |uint64|3                                      |
|test.local   |                          |TLS/HTTPS endpoint for distributed query retrieval|distributed_tls_read_endpoint|0         |string|/api/v1/osquery/distributed/read       |
|test.local   |                          |TLS/HTTPS endpoint for distributed query results|distributed_tls_write_endpoint|0         |string|/api/v1/osquery/distributed/write      |
|test.local   |/var/run/docker.sock      |Docker UNIX domain socket path|docker_socket|0         |string|/var/run/docker.sock                   |
|test.local   |false                     |Enable userland watchdog for extensions processes|enable_extensions_watchdog|0         |bool|false                                  |
|test.local   |false                     |Enable no-op foreign virtual tables|enable_foreign|0         |bool|false                                  |
|test.local   |false                     |Enable numeric monitoring system|enable_numeric_monitoring|0         |bool|false                                  |
|test.local   |false                     |Enable the syslog ingestion event publisher|enable_syslog|0         |bool|false                                  |
|test.local   |                          |Comma-delimited list of table names to be enabled|enable_tables|0         |string|                                       |
|test.local   |false                     |On startup, send a new enrollment request|enroll_always|0         |bool|false                                  |
|test.local   |                          |Name of environment variable holding enrollment-auth secret|enroll_secret_env|0         |string|                                       |
|test.local   |                          |Path to an optional client enrollment-auth secret|enroll_secret_path|0         |string|/etc/osquery/enrollment_secret         |
|test.local   |                          |TLS/HTTPS endpoint for client enrollment|enroll_tls_endpoint|0         |string|/api/v1/osquery/enroll                 |
|test.local   |false                     |Skip pidfile and database state checks|ephemeral|0         |bool|false                                  |
|test.local   |3600                      |Timeout to expire event subscriber results|events_expiry|0         |uint64|1                                      |
|test.local   |50000                     |Maximum number of events per type to buffer|events_max|0         |uint64|50000                                  |
|test.local   |true                      |Optimize subscriber select queries (scheduler only)|events_optimize|0         |bool|true                                   |
|test.local   |                          |Path to a single extension to autoload|extension|1         |string|                                       |
|test.local   |/etc/osquery/extensions.load|Optional path to a list of autoloaded & managed extensions|extensions_autoload|0         |string|/etc/osquery/extensions.load           |
|test.local   |true                      |Enable INDEX on all extension table columns (default true)|extensions_default_index|0         |bool|true                                   |
|test.local   |3                         |Seconds delay between connectivity checks|extensions_interval|0         |string|3                                      |
|test.local   |                          |Comma-separated list of required extensions|extensions_require|0         |string|                                       |
|test.local   |/var/osquery/osquery.em   |Path to the extensions UNIX domain socket|extensions_socket|0         |string|/var/osquery/osquery.em                |
|test.local   |3                         |Seconds to wait for autoloaded extensions|extensions_timeout|0         |string|3                                      |
|test.local   |false                     |Force osqueryd to kill previously-running daemons|force|0         |bool|true                                   |
|test.local   |partition                 |List of disabled hardware event types|hardware_disabled_types|0         |string|partition                              |
|test.local   |500                       |Size of LRU file hash cache|hash_cache_max|0         |uint32|500                                    |
|test.local   |20                        |Number of milliseconds to delay after hashing|hash_delay|0         |uint32|20                                     |
|test.local   |true                      |Toggle column headers true/false|header|1         |bool|true                                   |
|test.local   |hostname                  |Field used to identify the host running osquery (hostname, uuid, instance, ephemeral, specified)|host_identifier|0         |string|hostname                               |
|test.local   |false                     |Install osqueryd as a service|install|0         |bool|false                                  |
|test.local   |false                     |Set output mode to 'json'|json|1         |bool|false                                  |
|test.local   |false                     |Set output mode to 'line'|line|1         |bool|false                                  |
|test.local   |false                     |Set output mode to 'list'|list|1         |bool|false                                  |
|test.local   |true                      |Log scheduled results as events|logger_event_type|0         |bool|true                                   |
|test.local   |all                       |The number of acknowledgments the leader has to receive (0, 1, 'all')|logger_kafka_acks|0         |string|all                                    |
|test.local   |localhost                 |Bootstrap broker(s) as a comma-separated list of host or host:port (default port 9092)|logger_kafka_brokers|0         |string|localhost                              |
|test.local   |none                      |Compression codec to use for compressing message sets ('none' or 'gzip')|logger_kafka_compression|0         |string|none                                   |
|test.local   |                          |Kafka topic to publish logs under|logger_kafka_topic|0         |string|                                       |
|test.local   |0                         |Minimum level for status log recording|logger_min_status|0         |int32|2                                      |
|test.local   |0                         |Minimum level for statuses written to stderr|logger_min_stderr|0         |int32|2                                      |
|test.local   |416                       |Decimal mode for log files (default '0640')|logger_mode|0         |int32|416                                    |
|test.local   |false                     |Use numeric JSON syntax for numeric values|logger_numerics|0         |bool|false                                  |
|test.local   |/var/log/osquery/         |Directory path for ERROR/WARN/INFO and results logging|logger_path|0         |string|/var/log/osquery/                      |
|test.local   |filesystem                |Logger plugin name|logger_plugin|0         |string|syslog                                 |
|test.local   |false                     |Log scheduled snapshot results as events|logger_snapshot_event_type|0         |bool|true                                   |
|test.local   |false                     |Always send status logs synchronously|logger_status_sync|0         |bool|false                                  |
|test.local   |true                      |Write status logs to stderr|logger_stderr|0         |bool|true                                   |
|test.local   |19                        |Syslog facility for status and results logs (0-23, default 19)|logger_syslog_facility|0         |int32|19                                     |
|test.local   |false                     |Prepend @cee: tag to logged JSON messages|logger_syslog_prepend_cee|0         |bool|false                                  |
|test.local   |false                     |GZip compress TLS/HTTPS request body|logger_tls_compress|0         |bool|false                                  |
|test.local   |                          |TLS/HTTPS endpoint for results logging|logger_tls_endpoint|0         |string|                                       |
|test.local   |1024                      |Max number of logs to send per period|logger_tls_max_lines|0         |uint64|1024                                   |
|test.local   |1048576                   |Max size in bytes allowed per log line|logger_tls_max_linesize|0         |uint64|1048576                                |
|test.local   |4                         |Seconds between flushing logs over TLS/HTTPS|logger_tls_period|0         |uint64|4                                      |
|test.local   |false                     |Log messages to stderr in addition to the logger plugin(s)|logtostderr|0         |bool|true                                   |
|test.local   |                          |Set string for NULL values, default ''|nullvalue|0         |string|                                       |
|test.local   |/var/log/osquery/numeric_monitoring.log|File to dump numeric monitoring records one per line. The format of the line is <PATH><TAB><VALUE><TAB><TIMESTAMP>.|numeric_monitoring_filesystem_path|0         |string|/var/log/osquery/numeric_monitoring.log|
|test.local   |filesystem                |Comma separated numeric monitoring plugins names|numeric_monitoring_plugins|0         |string|filesystem                             |
|test.local   |60                        |Time period in seconds for numeric monitoring pre-aggreagation buffer.|numeric_monitoring_pre_aggregation_time|0         |uint64|60                                     |
|test.local   |                          |Run all queries in a pack|pack|1         |string|                                       |
|test.local   |_                         |Delimiter for pack and query names|pack_delimiter|0         |string|/                                      |
|test.local   |3600                      |Cache expiration for a packs discovery queries|pack_refresh_interval|0         |uint64|3600                                   |
|test.local   |/var/run/osqueryd.pidfile |Path to the daemon pidfile mutex|pidfile|0         |string|/var/run/osqueryd.pidfile              |
|test.local   |false                     |Enable osquery runtime planner output|planner|1         |bool|false                                  |
|test.local   |0                         |Enable profile mode when non-0, set number of iterations|profile|1         |int32|0                                      |
|test.local   |0                         |Sleep a number of seconds before and after the profiling|profile_delay|0         |int32|0                                      |
|test.local   |                          |Optional HTTP proxy hostname|proxy_hostname|0         |string|                                       |
|test.local   |52428800                  |Maximum file read size|read_max|0         |uint64|52428800                               |
|test.local   |false                     |Allow plugin exceptions|registry_exceptions|0         |bool|false                                  |
|test.local   |4                         |Max background flushes|rocksdb_background_flushes|0         |int32|4                                      |
|test.local   |256                       |Write buffer blocks (4k)|rocksdb_buffer_blocks|0         |uint64|256                                    |
|test.local   |4                         |Min write buffer number to merge|rocksdb_merge_number|0         |int32|4                                      |
|test.local   |16                        |Max write buffer number|rocksdb_write_buffer|0         |int32|16                                     |
|test.local   |3600                      |Query interval to use if none is provided|schedule_default_interval|0         |uint64|3600                                   |
|test.local   |0                         |Epoch for scheduled queries|schedule_epoch|0         |uint64|0                                      |
|test.local   |60                        |Max time drift in seconds|schedule_max_drift|0         |uint64|60                                     |
|test.local   |300                       |Interval in seconds to reload database arenas|schedule_reload|0         |uint64|300                                    |
|test.local   |false                     |Reload the SQL implementation during schedule reload|schedule_reload_sql|0         |bool|false                                  |
|test.local   |10                        |Percent to splay config times|schedule_splay_percent|0         |uint64|10                                     |
|test.local   |0                         |Limit the schedule, 0 for no limit|schedule_timeout|0         |uint64|0                                      |
|test.local   |&#124;                         |Set output field separator, default '&#124;'|separator|1         |string|&#124;                                      |
|test.local   |                          |Field used to specify the host_identifier when set to \|specified_identifier|0         |string|                                       |
|test.local   |2                         |Stderr log level threshold|stderrthreshold|0         |int32|2                                      |
|test.local   |2592000                   |Timeout to expire event subscriber results|syslog_events_expiry|0         |uint64|2592000                                |
|test.local   |100000                    |Maximum number of events per type to buffer|syslog_events_max|0         |uint64|100000                                 |
|test.local   |/var/osquery/syslog_pipe  |Path to the named pipe used for forwarding rsyslog events|syslog_pipe_path|0         |string|/var/osquery/syslog_pipe               |
|test.local   |100                       |Maximum number of logs to ingest per run (~200ms between runs)|syslog_rate_limit|0         |uint64|100                                    |
|test.local   |0                         |Add an optional microsecond delay between table scans|table_delay|0         |uint64|0                                      |
|test.local   |                          |Optional path to a TLS client-auth PEM certificate|tls_client_cert|0         |string|                                       |
|test.local   |                          |Optional path to a TLS client-auth PEM private key|tls_client_key|0         |string|                                       |
|test.local   |false                     |Print remote requests and responses|tls_dump|0         |bool|false                                  |
|test.local   |3                         |Number of attempts to retry a TLS enroll request, it used to be the same as [config_tls_max_attempts]|tls_enroll_max_attempts|0         |uint64|3                                      |
|test.local   |enroll_secret             |Override the TLS enroll secret key name|tls_enroll_override|0         |string|enroll_secret                          |
|test.local   |                          |TLS/HTTPS hostname for Config, Logger, and Enroll plugins|tls_hostname|0         |string|kolide-server.local:8412               |
|test.local   |false                     |Use node key as TLS endpoints|tls_node_api|0         |bool|false                                  |
|test.local   |false                     |Include TLS enroll secret in every request|tls_secret_always|0         |bool|false                                  |
|test.local   |/usr/share/osquery/certs/certs.pem|Optional path to a TLS server PEM certificate(s) bundle|tls_server_certs|0         |string|/etc/osquery/server.pem                |
|test.local   |true                      |Reuse TLS session sockets|tls_session_reuse|0         |bool|true                                   |
|test.local   |3600                      |TLS session keep alive timeout in seconds|tls_session_timeout|0         |uint32|3600                                   |
|test.local   |false                     |Uninstall osqueryd as a service|uninstall|0         |bool|false                                  |
|test.local   |true                      |Convert all UNIX times to UTC|utc |0         |bool|true                                   |
|test.local   |false                     |Enable verbose informational messages|verbose|0         |bool|false                                  |
|test.local   |60                        |Initial delay in seconds before watchdog starts|watchdog_delay|0         |uint64|480                                    |
|test.local   |0                         |Performance limit level (0=normal, 1=restrictive, -1=off)|watchdog_level|0         |int32|0                                      |
|test.local   |600                       |Max delay in seconds between worker respawns|watchdog_max_delay|0         |uint64|600                                    |
|test.local   |0                         |Override watchdog profile memory limit (e.g., 300, for 300MB)|watchdog_memory_limit|0         |uint64|550                                    |
|test.local   |0                         |Override watchdog profile CPU utilization limit|watchdog_utilization_limit|0         |uint64|720                                    |
|test.local   |4                         |Number of work dispatch threads|worker_threads|0         |int32|4                                      |
|test.local   |50                        |Time in ms to sleep after scan of each file (default 50) to reduce memory spikes|yara_delay|0         |uint32|50                                     |
|test.local   |true                      |Call malloc_trim() after YARA scans (linux)|yara_malloc_trim|0         |bool|true                                   |

**Comment by zwass** [comment]
In order to debug this, you'll need to turn on `--verbose --tls_dump` in the flags for osqueryd, so that we can verify it is making a config request and see the configuration that is returned by Fleet. It may help to turn `config_refresh` to something like `60` so that osqueryd tries to update configs every minute.

**Comment by macEar** [comment]
The reason was I didn't set `--config_tls_refresh` flag in osquery flags file. Initially I thought it would be enough to set it on the Kolide side.
