### ISSUE TITLE
Websocket Endpoint for Getting Fleet Results

### ISSUE THREAD

**Issue by saifkamaal** [kolide/fleet#2264]
the websocket is somewhat like this wss://server.domain.name/api/v1/kolide/results/386/pci42o5r/websocket. Can someone throw some light as to what are the two parts after results that needs to be passed.

I dont wanna use the fleetcli for my usecase.

Same as: https://github.com/kolide/fleet/issues/2013

**Comment by saifkamaal** [comment]
anyone ?

anyone ?

**Comment by ToxicRoot** [comment]
You need to send 2 request to the socket:
{'type': 'auth', 'data': {'token': <your_token>}}
{'type': 'select_campaign', 'data': {'campaign_id': <campaign_id>}}

so I guess in your wss://server.domain.name/api/v1/kolide/results/386/pci42o5r/websocket, "385" in the campaign_id and "pci42o5r" could be the token. 

If you want, I can provide a python function that communicates with Kolide's websocket and retrieves query results from it, until all results were retrieved

**Comment by saifkamaal** [comment]
@ToxicRoot thank you. Would love if you can share the phyton function.

**Comment by zwass** [comment]
https://github.com/kolide/fleet/issues/2013#issuecomment-472126583 should point you in the right direction.

**Comment by saifkamaal** [comment]
So i was checking the code but the values of 

{'type': 'auth', 'data': {'token': <your_token>}}
{'type': 'select_campaign', 'data': {'campaign_id': <campaign_id>}}

are not like the ones passed via the websocket call. 

For eg:

Before the websocket is invoked the `run` api is called which returns the campaign id. Soon after this, the web socket is invoked but the campaign id passed to the websocket is not the one received via the `run` api.

Response of `run` api 

```
{
  "campaign": {
    "created_at": "0001-01-01T00:00:00Z",
    "updated_at": "0001-01-01T00:00:00Z",
    "deleted_at": null,
    "deleted": false,
    "Metrics": {
      "TotalHosts": 26,
      "OnlineHosts": 3,
      "OfflineHosts": 22,
      "MissingInActionHosts": 1,
      "NewHosts": 0
    },
    "id": 547,
    "query_id": 876,
    "status": 0,
    "user_id": somenumber
  }
}
```
The auth token too is not the one stored in my local storage of the browser.
