### ISSUE TITLE
Feature Request: Allow multiple packs with the same name if they have different targets

### ISSUE THREAD

**Issue by jalseth** [kolide/fleet#2288]
It would be nice to be able to have multiple packs (and queries) with the same name if they have different targets. This would enable us to normalize the fields for some common types of information that you want to collect from endpoints running different operating systems. For example, if I wanted to create an inventory of the installed applications on both Windows and macOS laptops, they would need different pack and query names which means my processing backend has to know how to handle those.

In this example, I would create two `inventory` packs, one targeting macOS and one Windows using labels. Then, each of those would have and `apps` query for getting the application name and version. These queries would differ, but they would return the same columns. For example, the macOS query would be `select name, bundle_version as version, path from apps;` and the Windows query would be `select name, version, install_location as path from programs;`.

**Comment by zwass** [comment]
It's not necessarily possible to ensure that pack targets are exclusive (what if the targets change later?), but this may be easier to implement using platform as the differentiator (similar to how configuration overrides work).

**Comment by jalseth** [comment]
That's a fair point, that does seem relatively difficult for Fleet to handle. I think I will instead have the packs have a shared prefix in their name and normalize the returned fields from the queries so that I can group them by matching on the pack name prefix and still set alerts based on the query result columns.

**Comment by zwass** [comment]
Great! Glad you have a solution that works.

We can revisit this if it becomes necessary at some later time.
