### ISSUE TITLE
Fleet constantly querying mysql causing performance issues. 

### ISSUE THREAD

**Issue by anelshaer** [kolide/fleet#2293]
### What version of `fleet` are you using (`fleet version --full`)?
Fleet 2.6.0

### What operating system are you using?
CentOS

### What did you do?
trying to add a Host Label to a Query Pack to enable scheduled queries on them. 

### What did you expect to see?
i should be able to add a host or a label to the pack's targets. 

### What did you see instead?
Fleet keep searching and then doesn't find host or pack. 

##Information around our setup.
we have 11K host connected to fleet. our DB server is 12 CPU and 24 GB RAM.

we noticed that fleet is constantly hitting the DB server and it seems it does so many activities updating hosts maybe. 
and it's always OOM and get killed. which affect the simple host search or label search on the UI. 

![image](https://user-images.githubusercontent.com/4087461/91564926-aa728780-e941-11ea-83b1-f24c6a1d5fa4.png)
![image](https://user-images.githubusercontent.com/4087461/91564994-c8d88300-e941-11ea-9240-e5c8cde8d3d0.png)

**Comment by anelshaer** [comment]
we have been trying to see what slow queries or frequent queries and we saw


```
INSERT INTO hosts (
                        detail_update_time,
                        osquery_host_id,
                        seen_time,
                        node_key
                ) VALUES ('1970-01-02 00:00:00', 'web01', '2020-09-02 13:50:33.053319', 'REDACTEDREDACTED')
                ON DUPLICATE KEY UPDATE
                        node_key = VALUES(node_key),
                        deleted = FALSE;

```
i think the bottleneck is table host due to write activity: the `seen_time` is updated whenever a host is accessed?

there is` innodb_flush_log_at_trx_commit` setting with innodb config, which is a tradeoff between speed and durability. currently set at 1, which is` flush to disk at each commit`

the top two queries are

```
UPDATE hosts SET
                        seen_time = '2020-09-03 01:18:25.675845'
                WHERE node_key='REDACTEDREDACTED'

```
which is executed frequently, causing memory/io bottleneck.

and the other is the select query
```
SELECT DISTINCT dqc.id, q.query
                FROM distributed_query_campaigns dqc
                JOIN distributed_query_campaign_targets dqct
                    ON (dqc.id = dqct.distributed_query_campaign_id)
                LEFT JOIN label_query_executions lqe
                    ON (dqct.type = 0 AND dqct.target_id = lqe.label_id AND lqe.matches)
                LEFT JOIN hosts h
                    ON ((dqct.type = 0 AND lqe.host_id = h.id) OR (dqct.type = 1 AND dqct.target_id = h.id))
                LEFT JOIN distributed_query_executions dqe
                    ON (h.id = dqe.host_id AND dqc.id = dqe.distributed_query_campaign_id)
                JOIN queries q
                    ON (dqc.query_id = q.id)
                WHERE dqe.status IS NULL AND dqc.status = 1 AND h.id = 4862
                        AND NOT q.deleted
                        AND NOT dqc.deleted
```

**Comment by anelshaer** [comment]
Another query that causing most user wait.

```
SELECT DISTINCT *  
FROM hosts  
WHERE ( id IN  
   (  
   SELECT id  
   FROM hosts  
   WHERE MATCH ( host_name , uuid ) AGAINST ( ? IN BOOLEAN MODE )  
   )  
OR id IN  
   (  
   SELECT host_id  
   FROM network_interfaces  
   WHERE MATCH ( ip_address ) AGAINST ( ? IN BOOLEAN MODE )  
   ) )  
AND NOT deleted LIMIT ?
```

**Comment by directionless** [comment]
On slack, it was discussed that this was 2.6.0, and version 3 likely has improvements.

**Comment by anelshaer** [comment]
as mentioned in the slack i will test the new version and see if that fixed. 
we were able to capture the query that is caused by the search. and i guess these queries needs some optimization just in case it wasnot optimised in the new version. 

```
        STATE: Fulltext initialization
           INFO: SELECT DISTINCT *
                FROM hosts
                WHERE
                (
                        id IN (
                                SELECT id
                                FROM hosts
                                WHERE
                                MATCH(host_name, uuid) AGAINST('ju*' IN BOOLEAN MODE)
                        )
                OR
                        id IN (
                                SELECT host_id
                                FROM network_interfaces
                                WHERE
                                MATCH(ip_address) AGAINST('\"ju\"' IN BOOLEAN MODE)
                        )
                )
                AND NOT deleted
                LIMIT 10
```

**Comment by zwass** [comment]
Please test the latest version and open a new issue if you continue to have problems. Much of the MySQL was changed and the information in this issue will probably mostly be extraneous if there are further issues.
