### ISSUE TITLE
API responding with  INTERNAL_ERROR

### ISSUE THREAD

**Issue by anelshaer** [kolide/fleet#2294]
### What version of `fleet` are you using (`fleet version --full`)?
V2.6.0
### What operating system are you using?
Centos
### What did you do?
Updating Packs with labels using API. 
```
curl 'https://fleet.com:31443/api/v1/kolide/packs/38' \
       -X 'PATCH' \
       -H 'authority: fleet.com:31443' \
       -H 'accept: application/json' \
       -H 'authorization: Bearer REDACTEDREDACTEDREDACTED' \
       -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36' \
       -H 'content-type: application/json' \
       -H 'origin: https://fleet.com:31443' \
       -H 'sec-fetch-site: same-origin' \
       -H 'sec-fetch-mode: cors' \
       -H 'sec-fetch-dest: empty' \
       -H 'referer: https://fleet.com:31443/packs/manage?selectedPack=38' \
       -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
       -H 'cookie: _ga=GA1.2.640156389.1597663848; _gid=GA1.2.1168283613.1598860350' \
       --data-binary '{"host_ids":[],"label_ids":[36]}' \
       --compressed
```
### What did you expect to see?
success update.
### What did you see instead?
`curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)`

**Comment by anelshaer** [comment]
after many many attempts, that change took affect but i was still getting that error. which does not give any explanation on what is the issue. hopefully there is some logging we can enable around that.

**Comment by zwass** [comment]
Are you able to find the corresponding error log from the Fleet server? It's hard to debug this without that.

**Comment by anelshaer** [comment]
i have upgraded to fleet 3.1.0 so i will close this ticket. really appreciate taking a look at it. 
already started some API testing on the new version will report if any issues found. 
the only thing i see missing is a good docs for API but i'm using this which is really fine as well [Link](https://github.com/kolide/fleet/blob/master/server/service/handler.go)
