### ISSUE TITLE
Kolide Slack is down

### ISSUE THREAD

**Issue by flyfei-cmd** [kolide/fleet#2299]

**Comment by Zartch** [comment]
I run to the same issue.
just above the button u just pressed there is a text: "Join us in the **osquery slack** team at **#kolide**"

**Comment by zwass** [comment]
Ah, the link was just changed. This is the new link: https://osquery.slack.com/join/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw#/

I will update the documentation.
