### ISSUE TITLE
Live queries fail and cause the query to be run over and over on the host

### ISSUE THREAD

**Issue by crimsonknave** [kolide/fleet#2302]
### What version of `fleet` are you using (`fleet version --full`)?
`3.1.0`

### What operating system are you using?
We are using the official `kolide/fleet:3.1.0` docker image in kubernetes

### What did you do?
Attempted to run a live query

### What did you expect to see?
Results

### What did you see instead?
In our production deployment the results never come back. In staging the results do come back. The websockets request doesn't work in either, but that's likely due to our networking/load balancer config. However, in staging, the results do come back using the xhr calls.

Additionally, when they fail, the osqueryd agents seem to continue to retry that query forever. We have been able to successfully clean it up by removing the live queries from redis and then restarting osqueryd. When the queries are running over and over

All of our hosts are running osquery version `4.0.2`. 

Both our staging and production deployments are deployed in multiple clusters pointing to their own redis instance. The only difference between them is that prod has two replicas of the fleet pod in each cluster and staging has one (and they each have their own redis). Our staging server has two hosts enrolled and prod has ~6600 online.

##### Production Fails
![production_fleet_live_query](https://user-images.githubusercontent.com/352979/93492126-77843980-f8d8-11ea-90e4-60c7ce5a0ccd.png)

##### Staging works
![staging_fleet_live_query](https://user-images.githubusercontent.com/352979/93492129-794dfd00-f8d8-11ea-8cff-2153a5843dc8.png)

##### `osqueryd` logs
![osqueryd_logs](https://user-images.githubusercontent.com/352979/93492779-32143c00-f8d9-11ea-8b84-29d579cbb501.png)

**Comment by zwass** [comment]
Fleet is definitely supposed to clean up queries that are in weird execution states, so that's likely a bug that I will have to look into.

Are you able to connect the browser directly to one of the Fleet servers rather than the load balancer? It would be great to see if queries work over standard websocket, or at least rule out that the issue is to do with the SockJS XHR transport.

**Comment by crimsonknave** [comment]
I was able to connect directly (or, at least directly to the k8s service url) and websockets work perfectly. However, I need to be on the load balancer url for our SSO/SAML integration to work. I had to use a service account that doesn't have SAML to connect.

I am also able to get queries working via `fleetctl`. I can certainly work with that and don't need live queries working in the UI, but it would be great to get a fix for the isssues that arise when a live query is run in the ui when websockets don't work.

I guess for the the issues are:
1. Staging works via xhr and prod does not
1. Production gets stuck in a bad state when a live query is run via the 'official' url

I'm very confused by the fact that in prod the first request to xhr_send gets a 200 and the second gets a 404. Unless that error code is being thrown for a very abnormal reason the url should be present, it was just successful a moment ago.

**Comment by zwass** [comment]
I am going to address the clean up issue for queries that end up in a bad state.

Can you provide more details about your LB so that I can try to reproduce the XHR issue locally?

**Comment by zwass** [comment]
I think the XHR issue between staging and production is the multiple Fleet servers behind the load balancer.

Are you able to configure the LB to make the connections sticky? With Websockets the connection is persistent, so it doesn't much matter what the LB does. For XHR to work, the consecutive requests have to hit the same backend server.

Our XHR fallback (via SockJS) is a relatively simple workaround and would require substantial modifications to support load balancing with non-sticky connections.

**Comment by zwass** [comment]
If you need it to achieve sticky sessions, we can configure Fleet/SockJS to set a `JSESSIONID` cookie (or any other name necessary).

**Comment by crimsonknave** [comment]
@zwass I don't think I'm going to have time to debug the LB issues anytime soon. I'm satisfied with running the queries via `fleetctl` using a service account dedicated to it (pointing to the kubernetes service url). If I never get the live queries to work in the UI that's fine for right now, but it'll be great when the cleanup ships and we don't have to worry about someone who doesn't know/remember get Fleet in an unhappy state.

The LB stuff is going to be a bit complicated. It's an nginx proxy that integrates with Okta to check if you are allowed to access the url. So, it's a load balancer as well as IAM tool. There was a setting that was supposed to enable websockets that we tried, but didn't have any luck. In addition, that load balancer points to the kubernetes service url for all the clusters, so there's another layer to add complexity to.

**Comment by zwass** [comment]
Thank you for the details on the LB. Ultimately I think you're going to have to invest the time into sorting that out to get the full live query functionality.

I'm going to continue investigating the "unhappy state" issue and see if we can get that sorted for you.

**Comment by zwass** [comment]
I believe I have resolved the cleanup issue in #2316. I'd like to close out this issue with the merge of that PR. Please feel free to follow up with a new issue if we need to make additional changes to support sticky connection with your LB.
