### ISSUE TITLE
Allow programmatic user management

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#2306]
Users often want to be able to manage Fleet users without configuring email, or programmatically.

Proposal:
Add support for admin users to add a user and retrieve the invitation URL via `fleetctl`.

**Comment by anelshaer** [comment]
that would be great, specially if it can take a single user or a  list of users to create/delete/update like csv file.

**Comment by jalseth** [comment]
Strong +1 to this, we would like to programmatically sync users from our IDP into Fleet and then they can sign in via SAML SSO. 

As a tangentially related point for the need for this, I invited a new user to my instance today and Gmail marked the email as potential phishing, despite it coming from an authenticated user in the same domain and passing SPF, DKIM, and DMARC checks. This warning was shown to the user:

```
This message seems dangerous
Many people marked similar messages as phishing scams, so this might contain unsafe content. Avoid clicking links, downloading attachments, or replying with personal information.
```
