### ISSUE TITLE
Integer conversion errors in 32-bit builds

### ISSUE THREAD

**Issue by zwass** [kolide/fleet#2314]
@kevensen reported in https://github.com/kolide/fleet/issues/2297#issuecomment-703319819 an issue with hosts enrolling.

Looking at the error message in https://github.com/kolide/fleet/issues/2297#issuecomment-703786350, `failed to ingest result: ingesting query kolide_detail_query_system_info: strconv.Atoi: parsing \"67314212864\": value out of range`, it seems that the issue comes from parsing the string to a 32 bit integer.

This implies - but we are waiting for confirmation - that the user has a 32 bit build of Fleet.

We need to understand how/why folks are running 32 bit builds of the Fleet server, and then choose a course of action:

1) Decide and document that Fleet expects a 64 bit build.

2) Ensure that `int64` types and conversions are used explicitly anywhere this is necessary.

**Comment by zwass** [comment]
@kevensen confirmed that they are running a 32 bit build: https://github.com/kolide/fleet/issues/2297#issuecomment-703803327

**Comment by zwass** [comment]
@kevensen want to pull down #2315 and see if it resolves your issue? I'm curious if anything else will come up.

**Comment by kevensen** [comment]
Sure thing.  I can try in a little bit.

**Comment by kevensen** [comment]
Well, the host info is populated now and I do not see any issues with the `atoi`.

**Comment by kevensen** [comment]
I've added other hosts and am observing the desired behavior.

**Comment by zwass** [comment]
Thank you for testing that out! Let me know if any other issues come up.
