### ISSUE TITLE
Logs on local machine with launcher started

### ISSUE THREAD

**Issue by epifanoviv** [kolide/fleet#2328]
Good day!

I start launcher with such parametres:
/opt/osquery/launcher   --enroll_secret=aaaaaaaaaaa   --hostname=192.168.192.168:443   --root_directory=/opt/osquery/tmp   --insecure -- --osqueryd_path=/opt/osquery/osqueryd
I get logs on kolide host. 
Please tell me how I can start the launcher so that the logs are saved on the local machine, but not sent to the kolide server
fleet - version 3.1.0
Centos 7

**Comment by zwass** [comment]
You probably need to configure `config_plugin` to `filesystem`. See https://github.com/kolide/fleet/blob/master/docs/cli/setup-guide.md#update-osquery-options.

**Comment by epifanoviv** [comment]
Hello! I'm not be able to try changes yet.
Now fleetctl get options:
kind: option
spec:
  config:
    decorators:
      load:
      - SELECT uuid AS host_uuid FROM system_info;
      - SELECT hostname AS hostname FROM system_info;
    options:
      disable_distributed: false
      distributed_interval: 10
      distributed_plugin: tls
      distributed_tls_max_attempts: 3
      logger_plugin: filesystem
      pack_delimiter: /
  overrides: {}
But i still get logs locally on fleet server.
If there is any way to put logs locally on the fleet clients?

**Comment by zwass** [comment]
Is the the actual indentation of your yaml? If so that is likely the issue.

The next debugging step is run osquery with `--verbose --tls_dump` and see what configuration osquery receives from the Fleet server.

**Comment by epifanoviv** [comment]
I1029 06:45:45.541636 10856 scheduler.cpp:96] Executing scheduled query pack/OS Version/os version: SELECT * FROM os_version
I1029 06:45:47.542469 10852 config.cpp:1213] Refreshing configuration state
I1029 06:45:47.542841 10852 tls.cpp:253] TLS/HTTPS POST request to URI: https://kelk.iac.local:443/api/v1/osquery/config
{"node_key":"VhyGOqL9EyEzWRz81zm4j8/bKQY7rma8"}
{
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT hostname AS hostname FROM system_info;"
    ]
  },
  "options": {
    "disable_distributed": false,
    "distributed_interval": 10,
    "distributed_plugin": "tls",
    "distributed_tls_max_attempts": 3,
    "logger_plugin": "filesystem",
    "logger_tls_endpoint": "/api/v1/osquery/log",
    "logger_tls_period": 10,
    "pack_delimiter": "/"
  },
  "packs": {
    "OS Version": {
      "queries": {
        "os version": {
          "query": "SELECT * FROM os_version",
          "interval": 10,
          "platform": "",
          "version": "",
          "snapshot": true,
          "removed": false,
          "shard": 100
        }
      }
    }
  }
}

**Comment by epifanoviv** [comment]
Now i get logs on host there /var/log/osquery/osqueryd.snapshots.log using that command
# /usr/bin/osqueryd --enroll_secret_path=/var/osquery/enroll_secret  --tls_server_certs=/var/osquery/server.pem  --tls_hostname=kelk.iac.local:443  --host_identifier=hostname  --enroll_tls_endpoint=/api/v1/osquery/enroll  --config_plugin=tls  --config_tls_endpoint=/api/v1/osquery/config  --config_refresh=10 --disable_distributed=false  --distributed_plugin=tls  --distributed_interval=3  --distributed_tls_max_attempts=3  --distributed_tls_read_endpoint=/api/v1/osquery/distributed/read  --distributed_tls_write_endpoint=/api/v1/osquery/distributed/write  --logger_plugin=filesystem

But there is not anything on host connected with launcher 

/opt/osquery/launcher --enroll_secret=InventariosationSED --hostname=192.168.23.48:443 --root_directory=/tmp/osquery --insecure --osqueryd_path=/opt/osquery/osqueryd

How can i solve it?

May be you cat tell the way to send logs to kafka using launcher or osqueryd?
