### ISSUE TITLE
fleet prepare db   with  Specified key was too long error

### ISSUE THREAD

**Issue by QDSD0** [kolide/fleet#2334]
### What version of `fleet` are you using (`fleet version --full`)?
fleet - version 3.1.0
  branch: 	HEAD
  revision: 	c6ce648fef3bb39b6e604333ec47cff0e625ff8e
  build date: 	2020-08-07T00:09:34Z
  build user: 	zwass
  go version: 	go1.14.4

### What operating system are you using?
CentOS Linux release 7.5.1804 (Core)
### What did you do?
`fleet prepare db --config fleet_test.yml`
### What did you expect to see?
execute success
### What did you see instead?
mysql version:5.6.36

```
2020/10/20 18:08:56 FAIL 20170306075207_UseUTF8MB.go (alter table file_integrity_monitoring_files: Error 1071: Specified key was too long; max key length is 767 bytes), quitting migration.

```

I want to know how to troubleshoot this problem

**Comment by zwass** [comment]
This is an [issue with MySQL 5.6](https://stackoverflow.com/a/1814594). Please upgrade to MySQL 5.7.
