### ISSUE TITLE
Execute commands on the agent side

### ISSUE THREAD

**Issue by thatcashcow** [kolide/fleet#2337]
Hi,
Is there any way to execute commands(shell commands) on the agent where osquery is deployed? Also is it possible to quarantine the system once a particular alert is triggered?

**Comment by zwass** [comment]
Osquery doesn't have any built-in response capabilities. You could use [Trail of Bits' extension](https://github.com/trailofbits/osquery-extensions) tables that do provide a limited amount of response capabilities with Fleet.

Typically users use osquery and Fleet to generate alerts and other tools to perform any response actions.
