### ISSUE TITLE
Import Config - /config/import

### ISSUE THREAD

**Issue by terracatta** [kolide/fleet#366]
## Wireframe
![import osquery config](https://cloud.githubusercontent.com/assets/315873/19905285/6e1adfcc-a04c-11e6-9ba1-c5a02e734dab.png)

## Mocks
[Zeplin - Osquery Import](https://app.zeplin.io/project.html#pid=57e17b71c5b31ff827f26ba6&dashboard&tags=osquery-import)

![import-osquery-config-base 2x](https://cloud.githubusercontent.com/assets/931724/19902876/bf64a958-a042-11e6-9fc9-c1635257048a.png)
![import-osquery-config-import-tooltip-1 2x](https://cloud.githubusercontent.com/assets/931724/19902871/bf5fb98e-a042-11e6-8cbf-f9cd4fc3f620.png)
![import-osquery-config-import-tooltip-3 2x](https://cloud.githubusercontent.com/assets/931724/19902873/bf6011b8-a042-11e6-90ba-d09c67c0e183.png)
![import-osquery-config-import-tooltip-2 2x](https://cloud.githubusercontent.com/assets/931724/19902875/bf649a44-a042-11e6-801c-1e756363896e.png)
![import-osquery-config-post-import-missing-files 2x](https://cloud.githubusercontent.com/assets/931724/19902874/bf604836-a042-11e6-9036-64eb80794a2d.png)
![import-osquery-config-import-tooltip-4 2x](https://cloud.githubusercontent.com/assets/931724/19902872/bf5ff0fc-a042-11e6-9588-16e848eab361.png)
![import-osquery-config-invalid-json 2x](https://cloud.githubusercontent.com/assets/931724/19902870/bf5a5bb0-a042-11e6-8573-e8bdd841b8ff.png)

## Story
As a user with an existing osquery installation/fleet I want the ability to import my configuration so that Kolide can manage osquery fleet with the queries and packs I've already used in the past.

### Idempotent
A user can perform this import with as many different/same configs as they want. The import automatically rejects duplicates items.

### For All Users
This feature is open for any user not just admins, the rationale being that normal users can create all the items this feature generates automatically so it would make no sense to hide this from normal users since they can achieve the same result using their existing feature set.

##  Engineering Tasks
 - [ ] #416 
 - [ ] #417 
 - [ ] #418  
 - [ ] #424

**Comment by marpaia** [comment]
Closing this in favor of `fleetctl`
