### ISSUE TITLE
Alert the user when their updated smtp settings are broken

### ISSUE THREAD

**Issue by mikestone14** [kolide/fleet#704]
### Server handling of SMTP settings

Anytime the user changes an smtp setting the settings are re-tested against the smtp server for to determine if the new smtp configuration works.  If it doesn’t work, the details of the failure are available in the SMTPTestError key in the response.  The ‘configured’ key is also changed from true to false (assuming that the old configuration was correct).

### Design changes

[The app settings page](https://zpl.io/2muj6X) displays a flash message when the account email is not configured. This may be enough, but we also may want to use the explanation given in the server response to provide more information to the user on that page.

<img width="570" alt="screen shot 2016-12-23 at 1 34 58 pm" src="https://cloud.githubusercontent.com/assets/2905145/21460296/aa675938-c914-11e6-99e0-c4330443706b.png">

**Comment by zwass** [comment]
This has been fixed at some point. Perhaps by https://github.com/kolide/fleet/pull/1903?

![mail_config](https://user-images.githubusercontent.com/575602/50529023-ce176780-0aa6-11e9-89ec-52b82fbcde53.gif)
