### ISSUE TITLE
Stop talking like nerds in error messages

### ISSUE THREAD

**Issue by terracatta** [kolide/fleet#757]
I recently came across this in PR 730 which exposes server-side errors in forms.

![image](https://cloud.githubusercontent.com/assets/315873/21660067/cf678164-d29b-11e6-847d-a033818cbc53.png)

Can we make this error message and others like written as if users may see them? For example, "datastore" is an abstract concept. Perhaps a better error message would be... 

> This email address not recognized. Please enter the email associated with your kolide account.

**Comment by marpaia** [comment]
This is no longer necessary
