### ISSUE TITLE
Getting lots of mysql deadlock errors submitting distributed query results

### ISSUE THREAD

**Issue by groob** [kolide/fleet#845]
The issue appears to be coming from here: https://github.com/kolide/kolide-ose/blob/ee3940e1638834ad737fe367c865d79645953aee/server/datastore/mysql/hosts.go#L213-L217

```
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=963.841818ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=629.534269ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=956.276357ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=3.995755211s
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=898.475581ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=470.400522ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=344.661257ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=475.22221ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=480.896582ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=366.386519ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=1.627645899s
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=1.630009013s
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=1.954320753s
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=388.714246ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=380.664697ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=192.867325ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=536.7162ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=538.737568ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=306.813972ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=337.334551ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=549.164375ms
ts=2017-01-10T06:32:16Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=242.798862ms
ts=2017-01-10T06:32:17Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=270.624848ms
ts=2017-01-10T06:32:37Z component=service method=SubmitDistributedQueryResults err="failed to update host details: updating nics: Error 1213: Deadlock found when trying to get lock; try restarting transaction" took=42.408006ms```

**Comment by 4ndygu** [comment]
Hi! Are there any updates to this issue? We're seeing the deadlock occur with ~9K hosts connected, running v3.3.0.

**Comment by billcobbler** [comment]
Running into this issue too with ~3k hosts.

I know updateNicsForHost's use of INSERT INTO ... ON DUPLICATE KEY UPDATE statement is causing the locks, but I'm not QUITE sure why (even after reading the MySQL docs on [locks](https://dev.mysql.com/doc/refman/5.7/en/innodb-locks-set.html)).


Details from `SHOW ENGINE INNODB STATUS;`:

> ------------------------
> LATEST DETECTED DEADLOCK
> ------------------------
> 2020-01-20 00:09:06 0x2b033abd2700
> *** (1) TRANSACTION:
> TRANSACTION 78516922, ACTIVE 0 sec inserting
> mysql tables in use 1, locked 1
> LOCK WAIT 5 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 2
> MySQL thread id 286926, OS thread handle 47297573750528, query id 1045761878 10.107.51.236 username update
> INSERT INTO network_interfaces (
>                         host_id,
>                         mac,
>                         ip_address,
>                         broadcast,
>                         ibytes,
>                         interface,
>                         ipackets,
>                         last_change,
>                         mask,
>                         metric,
>                         mtu,
>                         obytes,
>                         ierrors,
>                         oerrors,
>                         opackets,
>                         point_to_point,
>                         type
>                 ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
>                 ON DUPLICATE KEY UPDATE
>                         id = LAST_INSERT_ID(id),
>                         mac = VALUES(mac),
>                         broadcast = VALUES(broadcast),
>                         ibytes = VALUES(ibytes),
>                         ipackets = VALUES(ipackets),
>                         last_change = VALUES(last_change),
>                         mask = VALUES(mask),
>                         metric = VALUES(metric),
>                         mtu = VALUES(mtu),
>                         obytes = VALUES(obytes),
>                         ierrors = VALUES(ierrors),
>                         oerrors = VALUES(oerrors),
>                         opackets = VALUES(opackets),
>                         point_to_point = VALUES(point_to_point),
>                         type = VALUES(type)
> *** (1) WAITING FOR THIS LOCK TO BE GRANTED:
> RECORD LOCKS space id 258 page no 2729 n bits 408 index FTS_DOC_ID_INDEX of table `kolide`.`network_interfaces` trx id 78516922 lock_mode Xinsert intention waiting
> Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
>  0: len 8; hex 73757072656d756d; asc supremum;;
> 
> *** (2) TRANSACTION:
> TRANSACTION 78516915, ACTIVE 0 sec inserting
> mysql tables in use 1, locked 1
> 18 lock struct(s), heap size 1136, 33 row lock(s), undo log entries 12
> MySQL thread id 281276, OS thread handle 47292870371072, query id 1045761879 10.107.78.241 username update
> INSERT INTO network_interfaces (
>                         host_id,
>                         mac,
>                         ip_address,
>                         broadcast,
>                         ibytes,
>                         interface,
>                         ipackets,
>                         last_change,
>                         mask,
>                         metric,
>                         mtu,
>                         obytes,
>                         ierrors,
>                         oerrors,
>                         opackets,
>                         point_to_point,
>                         type
>                 ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
>                 ON DUPLICATE KEY UPDATE
>                         id = LAST_INSERT_ID(id),
>                         mac = VALUES(mac),
>                         broadcast = VALUES(broadcast),
>                         ibytes = VALUES(ibytes),
>                         ipackets = VALUES(ipackets),
>                         last_change = VALUES(last_change),
>                         mask = VALUES(mask),
>                         metric = VALUES(metric),
>                         mtu = VALUES(mtu),
>                         obytes = VALUES(obytes),
>                         ierrors = VALUES(ierrors),
>                         oerrors = VALUES(oerrors),
>                         opackets = VALUES(opackets),
>                         point_to_point = VALUES(point_to_point),
>                         type = VALUES(type)
> *** (2) HOLDS THE LOCK(S):
> RECORD LOCKS space id 258 page no 2729 n bits 408 index FTS_DOC_ID_INDEX of table `kolide`.`network_interfaces` trx id 78516915 lock_mode X
> Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
>  0: len 8; hex 73757072656d756d; asc supremum;;
> 
> *** (2) WAITING FOR THIS LOCK TO BE GRANTED:
> RECORD LOCKS space id 258 page no 2729 n bits 408 index FTS_DOC_ID_INDEX of table `kolide`.`network_interfaces` trx id 78516915 lock_mode Xinsert intention waiting
> Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
>  0: len 8; hex 73757072656d756d; asc supremum;;
> 
> *** WE ROLL BACK TRANSACTION (1)
