### ISSUE TITLE
Allow filtering the API call to GET hosts by ids

### ISSUE THREAD

**Issue by mikestone14** [kolide/fleet#847]
## The Problem

When viewing/editing a pack we need to see the selected targets in the pack. A target is either a host or a label. To view the targets we look at the pack's `host_ids` and `label_ids` attributes, grab the corresponding hosts and labels from state, make an API to get hosts and labels if we don't have them, and render the targets into the Select Targets Dropdown. This itself is not a problem, but if a Kolide instance has thousands of hosts we'll need to load all of them to guarantee we have all the pack's hosts loaded, which could be a performance problem.

## The Proposed Solution

Add a `filter` parameter to the hosts API which will return only the matching hosts. This filter parameter should either be a URL parameter to the current GET /hosts API or we should expose a POST to /hosts and send the filter as the request body.

#### Example:

The Pack:

```
{
  "pack": {
    "created_at": "2017-01-10T14:13:05Z",
    "updated_at": "2017-01-10T14:13:05Z",
    "deleted_at": null,
    "deleted": false,
    "id": 1,
    "name": "This pack has 1 label and 2 hosts",
    "description": "",
    "platform": "",
    "created_by": 1,
    "disabled": false,
    "query_count": 0,
    "total_hosts_count": 20,
    "host_ids": [19, 16],
    "label_ids": [6]
  }
}
```

Option 1 - The `GET /hosts` method:

```
GET /api/v1/kolide/hosts?filter[id]=19,16
```

Option 2 - The `POST /hosts` method:

```
POST /api/v1/kolide/hosts

{
  filter: {
    id: [19, 16],
  }
}
```

The response:

```
{
  hosts: [
    { ...host_body, id: 19 },
    { ...host_body, id: 16 },
  ]
}
```

By using a `filter` parameter and an `id` key we open up the door to add more filtering options as needed in the future.

**Comment by zwass** [comment]
I don't think we have a defined need for this in the frontend currently.
