### ISSUE TITLE
Create deployment documentation for different platforms

### ISSUE THREAD

**Issue by groob** [kolide/fleet#97]
The OSE project should have good docs for getting started on different platforms. 
- [x] heroku  
   Heroku should just have a deploy button right away, with some additional instructions. 
- [ ] GKE- Kubernetes  
   Should be similar to the tutorial for setting up wordpress
   https://cloud.google.com/container-engine/docs/tutorials/persistent-disk/
- [ ] Mac:  
  This one should be `docker compose up` with an optional darwin binary for people to try on their system. The darwin binary should just be for demo purposes and run with an inmem sql version. 
- [ ] Windows: I have no clue yet, but probably important to figure out. CI should at least build an exe...
- [ ] ESXI: I can build a template.

**Comment by marpaia** [comment]
We have some of these planned as blogs, no need for an issue since we have trello.
